apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: coordinator_api
      context: .
    - image: web_client
      context: web_client/
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    hooks:
      before:
        - host:
            command:
              - sh
              - -c
              - helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo add catalystcommunity https://raw.githubusercontent.com/catalystcommunity/charts/main
    releases:
      - name: reactorcide
        chartPath: ./helm_chart
        namespace: skaffoldreactorcide
        createNamespace: true
        skipBuildDependencies: true
        setValueTemplates:
          app.image.repository: "{{.IMAGE_REPO_coordinator_api}}"
          app.image.tag: "{{.IMAGE_TAG_coordinator_api}}@{{.IMAGE_DIGEST_coordinator_api}}"
          worker.image.repository: "{{.IMAGE_REPO_coordinator_api}}"
          worker.image.tag: "{{.IMAGE_TAG_coordinator_api}}@{{.IMAGE_DIGEST_coordinator_api}}"
          web.image.repository: "{{.IMAGE_REPO_web_client}}"
          web.image.tag: "{{.IMAGE_TAG_web_client}}@{{.IMAGE_DIGEST_web_client}}"
        valuesFiles:
          - values-skaffold-local.yaml
        recreatePods: true
        wait: true
portForward:
  # pf for postgresdb
  - resourceType: service
    resourceName: reactorcide-postgresql
    namespace: skaffoldreactorcide
    port: 5432
    localPort: 5432
  # pf for app server
  - resourceType: service
    resourceName: reactorcideapp
    namespace: skaffoldreactorcide
    port: 6080
    localPort: 6080
  # pf for app prometheus metrics
  - resourceType: service
    resourceName: reactorcideapp
    namespace: skaffoldreactorcide
    port: 9000
    localPort: 9000
  # pf for web app
  - resourceType: service
    resourceName: reactorcideweb
    namespace: skaffoldreactorcide
    port: 4080
    localPort: 4080
profiles:
  - name: no-app
    patches:
      # disable the app api deployment, so that consumers don't conflict with a
      # locally running version of the app api
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          app.enabled: false
          app.autoscaling.enabled: false
      - op: remove
        path: /portForward/1
      - op: remove
        path: /portForward/1
  - name: no-web
    patches:
      # disable the app api deployment, so that consumers don't conflict with a
      # locally running version of the app api
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          web.enabled: false
          web.autoscaling.enabled: false
      - op: remove
        path: /portForward/3
  # test profile that will deploy the app into a "test" namespace. this is
  # useful locally when you want to run tests, but don't want the tests to blow
  # away your local persistent storage.
  # usage:
  #
  #   skaffold dev --profile test
  #
  - name: test
    patches:
      - op: replace
        path: /deploy/helm/releases/0/namespace
        value: reactorcidetest
      - op: replace
        path: /portForward/0/namespace
        value: reactorcidetest
      - op: replace
        path: /portForward/1/namespace
        value: reactorcidetest
      - op: replace
        path: /portForward/2/namespace
        value: reactorcidetest
      - op: replace
        path: /portForward/3/namespace
        value: reactorcidetest
