// Package csilapi contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

import (
	"context"
)

// ReactorcideAuth defines the service interface
type ReactorcideAuth interface {
	GetAuthConfig(ctx context.Context, req GetAuthConfigRequest) (GetAuthConfigResponse, error)
	BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error)
	CompleteLogin(ctx context.Context, req CompleteLoginRequest) (CompleteLoginResponse, error)
	Authenticate(ctx context.Context, req AuthenticateRequest) (AuthenticateResponse, error)
	Logout(ctx context.Context, req LogoutRequest) (LogoutResponse, error)
	BootstrapAdmin(ctx context.Context, req BootstrapAdminRequest) (BootstrapAdminResponse, error)
}

// ReactorcideUi defines the service interface
type ReactorcideUi interface {
	GetCapabilities(ctx context.Context, req GetCapabilitiesRequest) (GetCapabilitiesResponse, error)
	ListOrgs(ctx context.Context, req ListOrgsRequest) (ListOrgsResponse, error)
	ListProjects(ctx context.Context, req ListProjectsRequest) (ListProjectsResponse, error)
	GetProject(ctx context.Context, req GetProjectRequest) (GetProjectResponse, error)
	CreateProject(ctx context.Context, req CreateProjectRequest) (CreateProjectResponse, error)
	UpdateProject(ctx context.Context, req UpdateProjectRequest) (UpdateProjectResponse, error)
	DeleteProject(ctx context.Context, req DeleteProjectRequest) (DeleteProjectResponse, error)
	ListGroups(ctx context.Context, req ListGroupsRequest) (ListGroupsResponse, error)
	CreateGroup(ctx context.Context, req CreateGroupRequest) (CreateGroupResponse, error)
	UpdateGroup(ctx context.Context, req UpdateGroupRequest) (UpdateGroupResponse, error)
	DeleteGroup(ctx context.Context, req DeleteGroupRequest) (DeleteGroupResponse, error)
	AddGroupMember(ctx context.Context, req AddGroupMemberRequest) (AddGroupMemberResponse, error)
	RemoveGroupMember(ctx context.Context, req RemoveGroupMemberRequest) (RemoveGroupMemberResponse, error)
	ListGroupMembers(ctx context.Context, req ListGroupMembersRequest) (ListGroupMembersResponse, error)
	ListRoleAssignments(ctx context.Context, req ListRoleAssignmentsRequest) (ListRoleAssignmentsResponse, error)
	AssignRole(ctx context.Context, req AssignRoleRequest) (AssignRoleResponse, error)
	RevokeRole(ctx context.Context, req RevokeRoleRequest) (RevokeRoleResponse, error)
	ListWebhookSecrets(ctx context.Context, req ListWebhookSecretsRequest) (ListWebhookSecretsResponse, error)
	AddWebhookSecret(ctx context.Context, req AddWebhookSecretRequest) (AddWebhookSecretResponse, error)
	DeactivateWebhookSecret(ctx context.Context, req DeactivateWebhookSecretRequest) (DeactivateWebhookSecretResponse, error)
	DeleteWebhookSecret(ctx context.Context, req DeleteWebhookSecretRequest) (DeleteWebhookSecretResponse, error)
	ListVcsCredentials(ctx context.Context, req ListVcsCredentialsRequest) (ListVcsCredentialsResponse, error)
	AddVcsCredential(ctx context.Context, req AddVcsCredentialRequest) (AddVcsCredentialResponse, error)
	DeactivateVcsCredential(ctx context.Context, req DeactivateVcsCredentialRequest) (DeactivateVcsCredentialResponse, error)
	DeleteVcsCredential(ctx context.Context, req DeleteVcsCredentialRequest) (DeleteVcsCredentialResponse, error)
	SetSecret(ctx context.Context, req SetSecretRequest) (SetSecretResponse, error)
	DeleteSecret(ctx context.Context, req DeleteSecretRequest) (DeleteSecretResponse, error)
	ListSecretPaths(ctx context.Context, req ListSecretPathsRequest) (ListSecretPathsResponse, error)
	ListSecretGrants(ctx context.Context, req ListSecretGrantsRequest) (ListSecretGrantsResponse, error)
	CreateSecretGrant(ctx context.Context, req CreateSecretGrantRequest) (CreateSecretGrantResponse, error)
	UpdateSecretGrant(ctx context.Context, req UpdateSecretGrantRequest) (UpdateSecretGrantResponse, error)
	DeleteSecretGrant(ctx context.Context, req DeleteSecretGrantRequest) (DeleteSecretGrantResponse, error)
	CancelJob(ctx context.Context, req CancelJobRequest) (CancelJobResponse, error)
	KillJob(ctx context.Context, req KillJobRequest) (KillJobResponse, error)
	CancelWorkflow(ctx context.Context, req CancelWorkflowRequest) (CancelWorkflowResponse, error)
	RetryJob(ctx context.Context, req RetryJobRequest) (RetryJobResponse, error)
	RetryWorkflow(ctx context.Context, req RetryWorkflowRequest) (RetryWorkflowResponse, error)
	RetryUnsuccessfulJobs(ctx context.Context, req RetryUnsuccessfulJobsRequest) (RetryUnsuccessfulJobsResponse, error)
	GetGlobalSettings(ctx context.Context, req GetGlobalSettingsRequest) (GetGlobalSettingsResponse, error)
	UpdateGlobalSettings(ctx context.Context, req UpdateGlobalSettingsRequest) (UpdateGlobalSettingsResponse, error)
	ListTrustedIdentities(ctx context.Context, req ListTrustedIdentitiesRequest) (ListTrustedIdentitiesResponse, error)
	AddTrustedIdentity(ctx context.Context, req AddTrustedIdentityRequest) (AddTrustedIdentityResponse, error)
	RemoveTrustedIdentity(ctx context.Context, req RemoveTrustedIdentityRequest) (RemoveTrustedIdentityResponse, error)
	ListTrustedDomainPatterns(ctx context.Context, req ListTrustedDomainPatternsRequest) (ListTrustedDomainPatternsResponse, error)
	AddTrustedDomainPattern(ctx context.Context, req AddTrustedDomainPatternRequest) (AddTrustedDomainPatternResponse, error)
	RemoveTrustedDomainPattern(ctx context.Context, req RemoveTrustedDomainPatternRequest) (RemoveTrustedDomainPatternResponse, error)
}
