// Package csilapi contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

// ServiceError represents a structured data type
type ServiceError struct {
	Code    string `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// RoleSummary represents a structured data type
type RoleSummary struct {
	ScopeType string  `json:"scope_type" yaml:"scope_type"`
	ScopeId   *string `json:"scope_id,omitempty" yaml:"scope_id,omitempty"`
	Role      string  `json:"role" yaml:"role"`
}

// AuthenticatedIdentity represents a structured data type
type AuthenticatedIdentity struct {
	UserId        string        `json:"user_id" yaml:"user_id"`
	Subject       string        `json:"subject" yaml:"subject"`
	Handle        string        `json:"handle" yaml:"handle"`
	Domain        string        `json:"domain" yaml:"domain"`
	DisplayName   string        `json:"display_name" yaml:"display_name"`
	IsGlobalAdmin bool          `json:"is_global_admin" yaml:"is_global_admin"`
	Roles         []RoleSummary `json:"roles" yaml:"roles"`
}

// GetAuthConfigRequest represents a structured data type
type GetAuthConfigRequest struct {
}

// GetAuthConfigResponse represents a structured data type
type GetAuthConfigResponse struct {
	AuthMode                string `json:"auth_mode" yaml:"auth_mode"`
	BootstrapAdminAvailable bool   `json:"bootstrap_admin_available" yaml:"bootstrap_admin_available"`
	HasGlobalAdmin          bool   `json:"has_global_admin" yaml:"has_global_admin"`
}

// BeginLoginRequest represents a structured data type
type BeginLoginRequest struct {
	IdentityHint *string `json:"identity_hint,omitempty" yaml:"identity_hint,omitempty"`
}

// BeginLoginResponse represents a structured data type
type BeginLoginResponse struct {
	RedirectUrl  string `json:"redirect_url" yaml:"redirect_url"`
	AttemptToken string `json:"attempt_token" yaml:"attempt_token"`
}

// CompleteLoginRequest represents a structured data type
type CompleteLoginRequest struct {
	AttemptToken   string `json:"attempt_token" yaml:"attempt_token"`
	EncryptedToken string `json:"encrypted_token" yaml:"encrypted_token"`
}

// CompleteLoginResponse represents a structured data type
type CompleteLoginResponse struct {
	SessionToken string                `json:"session_token" yaml:"session_token"`
	ExpiresAt    string                `json:"expires_at" yaml:"expires_at"`
	Identity     AuthenticatedIdentity `json:"identity" yaml:"identity"`
}

// AuthenticateRequest represents a structured data type
type AuthenticateRequest struct {
}

// AuthenticateResponse represents a structured data type
type AuthenticateResponse struct {
	Authenticated bool                   `json:"authenticated" yaml:"authenticated"`
	Identity      *AuthenticatedIdentity `json:"identity,omitempty" yaml:"identity,omitempty"`
}

// LogoutRequest represents a structured data type
type LogoutRequest struct {
}

// LogoutResponse represents a structured data type
type LogoutResponse struct {
	Ok bool `json:"ok" yaml:"ok"`
}

// BootstrapAdminRequest represents a structured data type
type BootstrapAdminRequest struct {
	BootstrapToken string `json:"bootstrap_token" yaml:"bootstrap_token"`
}

// BootstrapAdminResponse represents a structured data type
type BootstrapAdminResponse struct {
	SessionToken string `json:"session_token" yaml:"session_token"`
	ExpiresAt    string `json:"expires_at" yaml:"expires_at"`
}

// GetCapabilitiesRequest represents a structured data type
type GetCapabilitiesRequest struct {
	OrgId     *string `json:"org_id,omitempty" yaml:"org_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty"`
}

// GetCapabilitiesResponse represents a structured data type
type GetCapabilitiesResponse struct {
	ViewPrivate             bool `json:"view_private" yaml:"view_private"`
	CancelJob               bool `json:"cancel_job" yaml:"cancel_job"`
	KillJob                 bool `json:"kill_job" yaml:"kill_job"`
	RetryJob                bool `json:"retry_job" yaml:"retry_job"`
	CreateProject           bool `json:"create_project" yaml:"create_project"`
	DeleteProject           bool `json:"delete_project" yaml:"delete_project"`
	ManageWebhookSecrets    bool `json:"manage_webhook_secrets" yaml:"manage_webhook_secrets"`
	ManageVcsCredentials    bool `json:"manage_vcs_credentials" yaml:"manage_vcs_credentials"`
	ManageSecrets           bool `json:"manage_secrets" yaml:"manage_secrets"`
	ManageGroups            bool `json:"manage_groups" yaml:"manage_groups"`
	ManageProjectSettings   bool `json:"manage_project_settings" yaml:"manage_project_settings"`
	ManageTrustedIdentities bool `json:"manage_trusted_identities" yaml:"manage_trusted_identities"`
	ManageGlobalSettings    bool `json:"manage_global_settings" yaml:"manage_global_settings"`
	IsGlobalAdmin           bool `json:"is_global_admin" yaml:"is_global_admin"`
	IsOrgAdmin              bool `json:"is_org_admin" yaml:"is_org_admin"`
	IsProjectOwner          bool `json:"is_project_owner" yaml:"is_project_owner"`
}

// OrgSummary represents a structured data type
type OrgSummary struct {
	OrgId     string `json:"org_id" yaml:"org_id"`
	Name      string `json:"name" yaml:"name"`
	IsPrivate bool   `json:"is_private" yaml:"is_private"`
}

// ListOrgsRequest represents a structured data type
type ListOrgsRequest struct {
}

// ListOrgsResponse represents a structured data type
type ListOrgsResponse struct {
	Orgs []OrgSummary `json:"orgs" yaml:"orgs"`
}

// ProjectSummary represents a structured data type
type ProjectSummary struct {
	ProjectId   string `json:"project_id" yaml:"project_id"`
	OrgId       string `json:"org_id" yaml:"org_id"`
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
	RepoUrl     string `json:"repo_url" yaml:"repo_url"`
	IsPrivate   bool   `json:"is_private" yaml:"is_private"`
	Enabled     bool   `json:"enabled" yaml:"enabled"`
	CreatedAt   string `json:"created_at" yaml:"created_at"`
	UpdatedAt   string `json:"updated_at" yaml:"updated_at"`
}

// ListProjectsRequest represents a structured data type
type ListProjectsRequest struct {
	OrgId *string `json:"org_id,omitempty" yaml:"org_id,omitempty"`
}

// ListProjectsResponse represents a structured data type
type ListProjectsResponse struct {
	Projects []ProjectSummary `json:"projects" yaml:"projects"`
}

// ProjectDetail represents a structured data type
type ProjectDetail struct {
	ProjectId             string   `json:"project_id" yaml:"project_id"`
	OrgId                 string   `json:"org_id" yaml:"org_id"`
	Name                  string   `json:"name" yaml:"name"`
	Description           string   `json:"description" yaml:"description"`
	RepoUrl               string   `json:"repo_url" yaml:"repo_url"`
	IsPrivate             bool     `json:"is_private" yaml:"is_private"`
	Enabled               bool     `json:"enabled" yaml:"enabled"`
	TargetBranches        []string `json:"target_branches" yaml:"target_branches"`
	AllowedEventTypes     []string `json:"allowed_event_types" yaml:"allowed_event_types"`
	DefaultCiSourceType   string   `json:"default_ci_source_type" yaml:"default_ci_source_type"`
	DefaultCiSourceUrl    string   `json:"default_ci_source_url" yaml:"default_ci_source_url"`
	DefaultCiSourceRef    string   `json:"default_ci_source_ref" yaml:"default_ci_source_ref"`
	DefaultRunnerImage    string   `json:"default_runner_image" yaml:"default_runner_image"`
	DefaultJobCommand     string   `json:"default_job_command" yaml:"default_job_command"`
	DefaultTimeoutSeconds int64    `json:"default_timeout_seconds" yaml:"default_timeout_seconds"`
	DefaultQueueName      string   `json:"default_queue_name" yaml:"default_queue_name"`
	CreatedAt             string   `json:"created_at" yaml:"created_at"`
	UpdatedAt             string   `json:"updated_at" yaml:"updated_at"`
}

// GetProjectRequest represents a structured data type
type GetProjectRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
}

// GetProjectResponse represents a structured data type
type GetProjectResponse struct {
	Project ProjectDetail `json:"project" yaml:"project"`
}

// CreateProjectRequest represents a structured data type
type CreateProjectRequest struct {
	OrgId             string   `json:"org_id" yaml:"org_id"`
	Name              string   `json:"name" yaml:"name"`
	Description       *string  `json:"description,omitempty" yaml:"description,omitempty"`
	RepoUrl           string   `json:"repo_url" yaml:"repo_url"`
	IsPrivate         *bool    `json:"is_private,omitempty" yaml:"is_private,omitempty"`
	TargetBranches    []string `json:"target_branches,omitempty" yaml:"target_branches,omitempty"`
	AllowedEventTypes []string `json:"allowed_event_types,omitempty" yaml:"allowed_event_types,omitempty"`
}

// CreateProjectResponse represents a structured data type
type CreateProjectResponse struct {
	Project ProjectDetail `json:"project" yaml:"project"`
}

// UpdateProjectRequest represents a structured data type
type UpdateProjectRequest struct {
	ProjectId             string   `json:"project_id" yaml:"project_id"`
	Name                  *string  `json:"name,omitempty" yaml:"name,omitempty"`
	Description           *string  `json:"description,omitempty" yaml:"description,omitempty"`
	IsPrivate             *bool    `json:"is_private,omitempty" yaml:"is_private,omitempty"`
	Enabled               *bool    `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	TargetBranches        []string `json:"target_branches,omitempty" yaml:"target_branches,omitempty"`
	AllowedEventTypes     []string `json:"allowed_event_types,omitempty" yaml:"allowed_event_types,omitempty"`
	DefaultRunnerImage    *string  `json:"default_runner_image,omitempty" yaml:"default_runner_image,omitempty"`
	DefaultJobCommand     *string  `json:"default_job_command,omitempty" yaml:"default_job_command,omitempty"`
	DefaultTimeoutSeconds *int64   `json:"default_timeout_seconds,omitempty" yaml:"default_timeout_seconds,omitempty"`
	DefaultQueueName      *string  `json:"default_queue_name,omitempty" yaml:"default_queue_name,omitempty"`
}

// UpdateProjectResponse represents a structured data type
type UpdateProjectResponse struct {
	Project ProjectDetail `json:"project" yaml:"project"`
}

// DeleteProjectRequest represents a structured data type
type DeleteProjectRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
}

// DeleteProjectResponse represents a structured data type
type DeleteProjectResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// GroupSummary represents a structured data type
type GroupSummary struct {
	GroupId     string  `json:"group_id" yaml:"group_id"`
	OrgId       string  `json:"org_id" yaml:"org_id"`
	Name        string  `json:"name" yaml:"name"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt   string  `json:"created_at" yaml:"created_at"`
	UpdatedAt   string  `json:"updated_at" yaml:"updated_at"`
}

// ListGroupsRequest represents a structured data type
type ListGroupsRequest struct {
	OrgId string `json:"org_id" yaml:"org_id"`
}

// ListGroupsResponse represents a structured data type
type ListGroupsResponse struct {
	Groups []GroupSummary `json:"groups" yaml:"groups"`
}

// CreateGroupRequest represents a structured data type
type CreateGroupRequest struct {
	OrgId       string  `json:"org_id" yaml:"org_id"`
	Name        string  `json:"name" yaml:"name"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// CreateGroupResponse represents a structured data type
type CreateGroupResponse struct {
	Group GroupSummary `json:"group" yaml:"group"`
}

// UpdateGroupRequest represents a structured data type
type UpdateGroupRequest struct {
	GroupId     string  `json:"group_id" yaml:"group_id"`
	Name        *string `json:"name,omitempty" yaml:"name,omitempty"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// UpdateGroupResponse represents a structured data type
type UpdateGroupResponse struct {
	Group GroupSummary `json:"group" yaml:"group"`
}

// DeleteGroupRequest represents a structured data type
type DeleteGroupRequest struct {
	GroupId string `json:"group_id" yaml:"group_id"`
}

// DeleteGroupResponse represents a structured data type
type DeleteGroupResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// AddGroupMemberRequest represents a structured data type
type AddGroupMemberRequest struct {
	GroupId string `json:"group_id" yaml:"group_id"`
	UserId  string `json:"user_id" yaml:"user_id"`
}

// AddGroupMemberResponse represents a structured data type
type AddGroupMemberResponse struct {
	Added bool `json:"added" yaml:"added"`
}

// RemoveGroupMemberRequest represents a structured data type
type RemoveGroupMemberRequest struct {
	GroupId string `json:"group_id" yaml:"group_id"`
	UserId  string `json:"user_id" yaml:"user_id"`
}

// RemoveGroupMemberResponse represents a structured data type
type RemoveGroupMemberResponse struct {
	Removed bool `json:"removed" yaml:"removed"`
}

// GroupMemberEntry represents a structured data type
type GroupMemberEntry struct {
	UserId   string `json:"user_id" yaml:"user_id"`
	Username string `json:"username" yaml:"username"`
}

// ListGroupMembersRequest represents a structured data type
type ListGroupMembersRequest struct {
	GroupId string `json:"group_id" yaml:"group_id"`
}

// ListGroupMembersResponse represents a structured data type
type ListGroupMembersResponse struct {
	Members []GroupMemberEntry `json:"members" yaml:"members"`
}

// RoleAssignment represents a structured data type
type RoleAssignment struct {
	AssignmentId  string  `json:"assignment_id" yaml:"assignment_id"`
	PrincipalType string  `json:"principal_type" yaml:"principal_type"`
	PrincipalId   string  `json:"principal_id" yaml:"principal_id"`
	ScopeType     string  `json:"scope_type" yaml:"scope_type"`
	ScopeId       *string `json:"scope_id,omitempty" yaml:"scope_id,omitempty"`
	Role          string  `json:"role" yaml:"role"`
	CreatedAt     string  `json:"created_at" yaml:"created_at"`
	CreatedBy     *string `json:"created_by,omitempty" yaml:"created_by,omitempty"`
}

// ListRoleAssignmentsRequest represents a structured data type
type ListRoleAssignmentsRequest struct {
	ScopeType   *string `json:"scope_type,omitempty" yaml:"scope_type,omitempty"`
	ScopeId     *string `json:"scope_id,omitempty" yaml:"scope_id,omitempty"`
	PrincipalId *string `json:"principal_id,omitempty" yaml:"principal_id,omitempty"`
}

// ListRoleAssignmentsResponse represents a structured data type
type ListRoleAssignmentsResponse struct {
	Assignments []RoleAssignment `json:"assignments" yaml:"assignments"`
}

// AssignRoleRequest represents a structured data type
type AssignRoleRequest struct {
	PrincipalType string  `json:"principal_type" yaml:"principal_type"`
	PrincipalId   string  `json:"principal_id" yaml:"principal_id"`
	ScopeType     string  `json:"scope_type" yaml:"scope_type"`
	ScopeId       *string `json:"scope_id,omitempty" yaml:"scope_id,omitempty"`
	Role          string  `json:"role" yaml:"role"`
}

// AssignRoleResponse represents a structured data type
type AssignRoleResponse struct {
	Assignment RoleAssignment `json:"assignment" yaml:"assignment"`
}

// RevokeRoleRequest represents a structured data type
type RevokeRoleRequest struct {
	AssignmentId string `json:"assignment_id" yaml:"assignment_id"`
}

// RevokeRoleResponse represents a structured data type
type RevokeRoleResponse struct {
	Revoked bool `json:"revoked" yaml:"revoked"`
}

// WebhookSecretSummary represents a structured data type
type WebhookSecretSummary struct {
	Id            string  `json:"id" yaml:"id"`
	ProjectId     string  `json:"project_id" yaml:"project_id"`
	Provider      string  `json:"provider" yaml:"provider"`
	Name          string  `json:"name" yaml:"name"`
	IsActive      bool    `json:"is_active" yaml:"is_active"`
	LastUsedAt    *string `json:"last_used_at,omitempty" yaml:"last_used_at,omitempty"`
	CreatedAt     string  `json:"created_at" yaml:"created_at"`
	DeactivatedAt *string `json:"deactivated_at,omitempty" yaml:"deactivated_at,omitempty"`
}

// ListWebhookSecretsRequest represents a structured data type
type ListWebhookSecretsRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
}

// ListWebhookSecretsResponse represents a structured data type
type ListWebhookSecretsResponse struct {
	Secrets []WebhookSecretSummary `json:"secrets" yaml:"secrets"`
}

// AddWebhookSecretRequest represents a structured data type
type AddWebhookSecretRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
	Provider  string `json:"provider" yaml:"provider"`
	Name      string `json:"name" yaml:"name"`
	Value     string `json:"value" yaml:"value"`
}

// AddWebhookSecretResponse represents a structured data type
type AddWebhookSecretResponse struct {
	Secret WebhookSecretSummary `json:"secret" yaml:"secret"`
}

// DeactivateWebhookSecretRequest represents a structured data type
type DeactivateWebhookSecretRequest struct {
	Id string `json:"id" yaml:"id"`
}

// DeactivateWebhookSecretResponse represents a structured data type
type DeactivateWebhookSecretResponse struct {
	Secret WebhookSecretSummary `json:"secret" yaml:"secret"`
}

// DeleteWebhookSecretRequest represents a structured data type
type DeleteWebhookSecretRequest struct {
	Id string `json:"id" yaml:"id"`
}

// DeleteWebhookSecretResponse represents a structured data type
type DeleteWebhookSecretResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// VcsCredentialSummary represents a structured data type
type VcsCredentialSummary struct {
	Id            string  `json:"id" yaml:"id"`
	ProjectId     string  `json:"project_id" yaml:"project_id"`
	Provider      string  `json:"provider" yaml:"provider"`
	Name          string  `json:"name" yaml:"name"`
	IsActive      bool    `json:"is_active" yaml:"is_active"`
	LastUsedAt    *string `json:"last_used_at,omitempty" yaml:"last_used_at,omitempty"`
	CreatedAt     string  `json:"created_at" yaml:"created_at"`
	DeactivatedAt *string `json:"deactivated_at,omitempty" yaml:"deactivated_at,omitempty"`
}

// ListVcsCredentialsRequest represents a structured data type
type ListVcsCredentialsRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
}

// ListVcsCredentialsResponse represents a structured data type
type ListVcsCredentialsResponse struct {
	Credentials []VcsCredentialSummary `json:"credentials" yaml:"credentials"`
}

// AddVcsCredentialRequest represents a structured data type
type AddVcsCredentialRequest struct {
	ProjectId string `json:"project_id" yaml:"project_id"`
	Provider  string `json:"provider" yaml:"provider"`
	Name      string `json:"name" yaml:"name"`
	Value     string `json:"value" yaml:"value"`
}

// AddVcsCredentialResponse represents a structured data type
type AddVcsCredentialResponse struct {
	Credential VcsCredentialSummary `json:"credential" yaml:"credential"`
}

// DeactivateVcsCredentialRequest represents a structured data type
type DeactivateVcsCredentialRequest struct {
	Id string `json:"id" yaml:"id"`
}

// DeactivateVcsCredentialResponse represents a structured data type
type DeactivateVcsCredentialResponse struct {
	Credential VcsCredentialSummary `json:"credential" yaml:"credential"`
}

// DeleteVcsCredentialRequest represents a structured data type
type DeleteVcsCredentialRequest struct {
	Id string `json:"id" yaml:"id"`
}

// DeleteVcsCredentialResponse represents a structured data type
type DeleteVcsCredentialResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// SetSecretRequest represents a structured data type
type SetSecretRequest struct {
	OrgId string `json:"org_id" yaml:"org_id"`
	Path  string `json:"path" yaml:"path"`
	Key   string `json:"key" yaml:"key"`
	Value string `json:"value" yaml:"value"`
}

// SetSecretResponse represents a structured data type
type SetSecretResponse struct {
	Ok bool `json:"ok" yaml:"ok"`
}

// DeleteSecretRequest represents a structured data type
type DeleteSecretRequest struct {
	OrgId string `json:"org_id" yaml:"org_id"`
	Path  string `json:"path" yaml:"path"`
	Key   string `json:"key" yaml:"key"`
}

// DeleteSecretResponse represents a structured data type
type DeleteSecretResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// SecretPathEntry represents a structured data type
type SecretPathEntry struct {
	Path string   `json:"path" yaml:"path"`
	Keys []string `json:"keys" yaml:"keys"`
}

// ListSecretPathsRequest represents a structured data type
type ListSecretPathsRequest struct {
	OrgId      string  `json:"org_id" yaml:"org_id"`
	PathPrefix *string `json:"path_prefix,omitempty" yaml:"path_prefix,omitempty"`
}

// ListSecretPathsResponse represents a structured data type
type ListSecretPathsResponse struct {
	Paths []SecretPathEntry `json:"paths" yaml:"paths"`
}

// SecretGrant represents a structured data type
type SecretGrant struct {
	GrantId           string  `json:"grant_id" yaml:"grant_id"`
	OrgId             string  `json:"org_id" yaml:"org_id"`
	ProjectId         *string `json:"project_id,omitempty" yaml:"project_id,omitempty"`
	Name              string  `json:"name" yaml:"name"`
	SecretPathMatch   string  `json:"secret_path_match" yaml:"secret_path_match"`
	SecretPathPattern string  `json:"secret_path_pattern" yaml:"secret_path_pattern"`
	JobNameMatch      string  `json:"job_name_match" yaml:"job_name_match"`
	JobNamePattern    *string `json:"job_name_pattern,omitempty" yaml:"job_name_pattern,omitempty"`
	Description       *string `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedAt         string  `json:"created_at" yaml:"created_at"`
	UpdatedAt         string  `json:"updated_at" yaml:"updated_at"`
}

// ListSecretGrantsRequest represents a structured data type
type ListSecretGrantsRequest struct {
	OrgId string `json:"org_id" yaml:"org_id"`
}

// ListSecretGrantsResponse represents a structured data type
type ListSecretGrantsResponse struct {
	Grants []SecretGrant `json:"grants" yaml:"grants"`
}

// CreateSecretGrantRequest represents a structured data type
type CreateSecretGrantRequest struct {
	OrgId             string  `json:"org_id" yaml:"org_id"`
	ProjectId         *string `json:"project_id,omitempty" yaml:"project_id,omitempty"`
	Name              string  `json:"name" yaml:"name"`
	SecretPathMatch   string  `json:"secret_path_match" yaml:"secret_path_match"`
	SecretPathPattern string  `json:"secret_path_pattern" yaml:"secret_path_pattern"`
	JobNameMatch      *string `json:"job_name_match,omitempty" yaml:"job_name_match,omitempty"`
	JobNamePattern    *string `json:"job_name_pattern,omitempty" yaml:"job_name_pattern,omitempty"`
	Description       *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// CreateSecretGrantResponse represents a structured data type
type CreateSecretGrantResponse struct {
	Grant SecretGrant `json:"grant" yaml:"grant"`
}

// UpdateSecretGrantRequest represents a structured data type
type UpdateSecretGrantRequest struct {
	GrantId           string  `json:"grant_id" yaml:"grant_id"`
	Name              *string `json:"name,omitempty" yaml:"name,omitempty"`
	SecretPathMatch   *string `json:"secret_path_match,omitempty" yaml:"secret_path_match,omitempty"`
	SecretPathPattern *string `json:"secret_path_pattern,omitempty" yaml:"secret_path_pattern,omitempty"`
	JobNameMatch      *string `json:"job_name_match,omitempty" yaml:"job_name_match,omitempty"`
	JobNamePattern    *string `json:"job_name_pattern,omitempty" yaml:"job_name_pattern,omitempty"`
	Description       *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// UpdateSecretGrantResponse represents a structured data type
type UpdateSecretGrantResponse struct {
	Grant SecretGrant `json:"grant" yaml:"grant"`
}

// DeleteSecretGrantRequest represents a structured data type
type DeleteSecretGrantRequest struct {
	GrantId string `json:"grant_id" yaml:"grant_id"`
}

// DeleteSecretGrantResponse represents a structured data type
type DeleteSecretGrantResponse struct {
	Deleted bool `json:"deleted" yaml:"deleted"`
}

// CancelJobRequest represents a structured data type
type CancelJobRequest struct {
	JobId string `json:"job_id" yaml:"job_id"`
}

// CancelJobResponse represents a structured data type
type CancelJobResponse struct {
	JobId  string `json:"job_id" yaml:"job_id"`
	Status string `json:"status" yaml:"status"`
}

// KillJobRequest represents a structured data type
type KillJobRequest struct {
	JobId string `json:"job_id" yaml:"job_id"`
}

// KillJobResponse represents a structured data type
type KillJobResponse struct {
	JobId  string `json:"job_id" yaml:"job_id"`
	Status string `json:"status" yaml:"status"`
}

// CancelWorkflowRequest represents a structured data type
type CancelWorkflowRequest struct {
	WorkflowInstanceId string `json:"workflow_instance_id" yaml:"workflow_instance_id"`
}

// CancelWorkflowResponse represents a structured data type
type CancelWorkflowResponse struct {
	WorkflowInstanceId string `json:"workflow_instance_id" yaml:"workflow_instance_id"`
	Status             string `json:"status" yaml:"status"`
}

// RetryJobRequest represents a structured data type
type RetryJobRequest struct {
	JobId string `json:"job_id" yaml:"job_id"`
}

// RetryJobResponse represents a structured data type
type RetryJobResponse struct {
	JobId  string `json:"job_id" yaml:"job_id"`
	Status string `json:"status" yaml:"status"`
}

// RetryWorkflowRequest represents a structured data type
type RetryWorkflowRequest struct {
	WorkflowInstanceId string `json:"workflow_instance_id" yaml:"workflow_instance_id"`
}

// RetryWorkflowResponse represents a structured data type
type RetryWorkflowResponse struct {
	WorkflowInstanceId string `json:"workflow_instance_id" yaml:"workflow_instance_id"`
	Status             string `json:"status" yaml:"status"`
}

// RetryUnsuccessfulJobsRequest represents a structured data type
type RetryUnsuccessfulJobsRequest struct {
	WorkflowInstanceId string `json:"workflow_instance_id" yaml:"workflow_instance_id"`
}

// RetryUnsuccessfulJobsResponse represents a structured data type
type RetryUnsuccessfulJobsResponse struct {
	JobIds       []string `json:"job_ids" yaml:"job_ids"`
	RetriedCount int64    `json:"retried_count" yaml:"retried_count"`
	SkippedCount int64    `json:"skipped_count" yaml:"skipped_count"`
}

// GlobalSettingEntry represents a structured data type
type GlobalSettingEntry struct {
	Key       string `json:"key" yaml:"key"`
	Value     any    `json:"value" yaml:"value"`
	UpdatedAt string `json:"updated_at" yaml:"updated_at"`
}

// GetGlobalSettingsRequest represents a structured data type
type GetGlobalSettingsRequest struct {
}

// GetGlobalSettingsResponse represents a structured data type
type GetGlobalSettingsResponse struct {
	NewProjectsPrivate bool                 `json:"new_projects_private" yaml:"new_projects_private"`
	Settings           []GlobalSettingEntry `json:"settings" yaml:"settings"`
}

// UpdateGlobalSettingsRequest represents a structured data type
type UpdateGlobalSettingsRequest struct {
	NewProjectsPrivate *bool                `json:"new_projects_private,omitempty" yaml:"new_projects_private,omitempty"`
	Settings           []GlobalSettingEntry `json:"settings,omitempty" yaml:"settings,omitempty"`
}

// UpdateGlobalSettingsResponse represents a structured data type
type UpdateGlobalSettingsResponse struct {
	NewProjectsPrivate bool                 `json:"new_projects_private" yaml:"new_projects_private"`
	Settings           []GlobalSettingEntry `json:"settings" yaml:"settings"`
}

// TrustedIdentity represents a structured data type
type TrustedIdentity struct {
	Domain    string `json:"domain" yaml:"domain"`
	Handle    string `json:"handle" yaml:"handle"`
	Source    string `json:"source" yaml:"source"`
	CreatedAt string `json:"created_at" yaml:"created_at"`
}

// ListTrustedIdentitiesRequest represents a structured data type
type ListTrustedIdentitiesRequest struct {
}

// ListTrustedIdentitiesResponse represents a structured data type
type ListTrustedIdentitiesResponse struct {
	Identities []TrustedIdentity `json:"identities" yaml:"identities"`
}

// AddTrustedIdentityRequest represents a structured data type
type AddTrustedIdentityRequest struct {
	Domain string  `json:"domain" yaml:"domain"`
	Handle *string `json:"handle,omitempty" yaml:"handle,omitempty"`
}

// AddTrustedIdentityResponse represents a structured data type
type AddTrustedIdentityResponse struct {
	Identity TrustedIdentity `json:"identity" yaml:"identity"`
}

// RemoveTrustedIdentityRequest represents a structured data type
type RemoveTrustedIdentityRequest struct {
	Domain string  `json:"domain" yaml:"domain"`
	Handle *string `json:"handle,omitempty" yaml:"handle,omitempty"`
}

// RemoveTrustedIdentityResponse represents a structured data type
type RemoveTrustedIdentityResponse struct {
	Removed bool `json:"removed" yaml:"removed"`
}

// TrustedDomainPattern represents a structured data type
type TrustedDomainPattern struct {
	PatternId   string  `json:"pattern_id" yaml:"pattern_id"`
	Pattern     string  `json:"pattern" yaml:"pattern"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty" yaml:"created_by,omitempty"`
	CreatedAt   string  `json:"created_at" yaml:"created_at"`
}

// ListTrustedDomainPatternsRequest represents a structured data type
type ListTrustedDomainPatternsRequest struct {
}

// ListTrustedDomainPatternsResponse represents a structured data type
type ListTrustedDomainPatternsResponse struct {
	Patterns []TrustedDomainPattern `json:"patterns" yaml:"patterns"`
}

// AddTrustedDomainPatternRequest represents a structured data type
type AddTrustedDomainPatternRequest struct {
	Pattern     string  `json:"pattern" yaml:"pattern"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
}

// AddTrustedDomainPatternResponse represents a structured data type
type AddTrustedDomainPatternResponse struct {
	Pattern TrustedDomainPattern `json:"pattern" yaml:"pattern"`
}

// RemoveTrustedDomainPatternRequest represents a structured data type
type RemoveTrustedDomainPatternRequest struct {
	PatternId string `json:"pattern_id" yaml:"pattern_id"`
}

// RemoveTrustedDomainPatternResponse represents a structured data type
type RemoveTrustedDomainPatternResponse struct {
	Removed bool `json:"removed" yaml:"removed"`
}
