apiVersion: v1
kind: Service
metadata:
  name: {{ include "corndogs.fullname" . }}
  labels:
    {{- include "corndogs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # CSIL-RPC over TCP — what clients connect to.
    - port: {{ .Values.service.port }}
      targetPort: corndogsrpc
      protocol: TCP
      name: corndogsrpc
    {{- if .Values.appconfig.prometheusEnabled }}
    - port: 8080
      targetPort: corndogsops
      protocol: TCP
      name: corndogsops
    {{- end }}
  selector:
    {{- include "corndogs.selectorLabels" . | nindent 4 }}
