name: conventional-commits
description: "Validate all pull-request commits with the conventional commit format"
triggers:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main
job:
  image: containers.catalystsquad.com/public/reactorcide/runnerbase:dev
  command: "runnerlib run --job-command true"
  timeout: 300
  priority: 10
  working_dir: /job
environment:
  REACTORCIDE_CI_JOB: conventional-commits
run_local:
  user: host
