// Package csilapi contains the self-contained canonical-CBOR codec.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

import (
	"fmt"
	"math"
)

// cborValue is a minimal canonical-CBOR value tree: a closed set of variants the
// generated codec builds and walks. The marker method keeps the set closed.
type cborValue interface{ isCbor() }

type cborUint uint64
type cborInt int64
type cborBool bool
type cborFloat float64
type cborNull struct{}
type cborText string
type cborBytes []byte
type cborArray []cborValue

// cborEntry is one map key/value pair; cborMap keeps entries ordered (a CBOR map is
// an ordered list of pairs), so the encoder controls the wire order explicitly.
type cborEntry struct {
	key cborValue
	val cborValue
}
type cborMap []cborEntry
type cborTag struct {
	num   uint64
	inner cborValue
}

func cborEqual(a, b cborValue) bool {
	switch x := a.(type) {
	case cborUint:
		y, ok := b.(cborUint)
		return ok && x == y
	case cborInt:
		y, ok := b.(cborInt)
		return ok && x == y
	case cborBool:
		y, ok := b.(cborBool)
		return ok && x == y
	case cborFloat:
		y, ok := b.(cborFloat)
		return ok && x == y
	case cborNull:
		_, ok := b.(cborNull)
		return ok
	case cborText:
		y, ok := b.(cborText)
		return ok && x == y
	case cborBytes:
		y, ok := b.(cborBytes)
		if !ok || len(x) != len(y) {
			return false
		}
		for i := range x {
			if x[i] != y[i] {
				return false
			}
		}
		return true
	case cborArray:
		y, ok := b.(cborArray)
		if !ok || len(x) != len(y) {
			return false
		}
		for i := range x {
			if !cborEqual(x[i], y[i]) {
				return false
			}
		}
		return true
	default:
		return false
	}
}

func (cborUint) isCbor()  {}
func (cborInt) isCbor()   {}
func (cborBool) isCbor()  {}
func (cborFloat) isCbor() {}
func (cborNull) isCbor()  {}
func (cborText) isCbor()  {}
func (cborBytes) isCbor() {}
func (cborArray) isCbor() {}
func (cborMap) isCbor()   {}
func (cborTag) isCbor()   {}

// cborEncode serializes a value tree to canonical CBOR bytes.
func cborEncode(v cborValue) []byte {
	var out []byte
	cborEnc(v, &out)
	return out
}

func cborHead(major byte, n uint64, out *[]byte) {
	mt := major << 5
	switch {
	case n < 24:
		*out = append(*out, mt|byte(n))
	case n < 0x100:
		*out = append(*out, mt|24, byte(n))
	case n < 0x10000:
		*out = append(*out, mt|25, byte(n>>8), byte(n))
	case n < 0x100000000:
		*out = append(*out, mt|26, byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	default:
		*out = append(*out, mt|27,
			byte(n>>56), byte(n>>48), byte(n>>40), byte(n>>32),
			byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	}
}

func cborEnc(v cborValue, out *[]byte) {
	switch x := v.(type) {
	case cborUint:
		cborHead(0, uint64(x), out)
	case cborInt:
		if x >= 0 {
			cborHead(0, uint64(x), out)
		} else {
			cborHead(1, uint64(-(int64(x) + 1)), out)
		}
	case cborBool:
		if bool(x) {
			*out = append(*out, 0xf5)
		} else {
			*out = append(*out, 0xf4)
		}
	case cborNull:
		*out = append(*out, 0xf6)
	case cborFloat:
		bits := math.Float64bits(float64(x))
		*out = append(*out, 0xfb,
			byte(bits>>56), byte(bits>>48), byte(bits>>40), byte(bits>>32),
			byte(bits>>24), byte(bits>>16), byte(bits>>8), byte(bits))
	case cborText:
		s := []byte(x)
		cborHead(3, uint64(len(s)), out)
		*out = append(*out, s...)
	case cborBytes:
		cborHead(2, uint64(len(x)), out)
		*out = append(*out, x...)
	case cborArray:
		cborHead(4, uint64(len(x)), out)
		for _, e := range x {
			cborEnc(e, out)
		}
	case cborMap:
		cborHead(5, uint64(len(x)), out)
		for _, e := range x {
			cborEnc(e.key, out)
			cborEnc(e.val, out)
		}
	case cborTag:
		cborHead(6, x.num, out)
		cborEnc(x.inner, out)
	}
}

// cborDecode parses a full CBOR item and rejects trailing bytes, so a payload that
// is not exactly one value is an error rather than a silently-truncated read.
func cborDecode(b []byte) (cborValue, error) {
	pos := 0
	v, err := cborDec(b, &pos)
	if err != nil {
		return nil, err
	}
	if pos != len(b) {
		return nil, fmt.Errorf("csil cbor: %d trailing bytes", len(b)-pos)
	}
	return v, nil
}

func cborReadArg(b []byte, pos *int, low byte) (uint64, error) {
	if low < 24 {
		*pos++
		return uint64(low), nil
	}
	switch low {
	case 24:
		if *pos+2 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		v := uint64(b[*pos+1])
		*pos += 2
		return v, nil
	case 25:
		if *pos+3 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		v := uint64(b[*pos+1])<<8 | uint64(b[*pos+2])
		*pos += 3
		return v, nil
	case 26:
		if *pos+5 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		var v uint64
		for i := 1; i <= 4; i++ {
			v = v<<8 | uint64(b[*pos+i])
		}
		*pos += 5
		return v, nil
	case 27:
		if *pos+9 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		var v uint64
		for i := 1; i <= 8; i++ {
			v = v<<8 | uint64(b[*pos+i])
		}
		*pos += 9
		return v, nil
	default:
		return 0, fmt.Errorf("csil cbor: reserved additional info %d", low)
	}
}

func cborDec(b []byte, pos *int) (cborValue, error) {
	if *pos >= len(b) {
		return nil, fmt.Errorf("csil cbor: unexpected end of input")
	}
	ib := b[*pos]
	major := ib >> 5
	low := ib & 0x1f
	if major == 7 {
		switch low {
		case 20:
			*pos++
			return cborBool(false), nil
		case 21:
			*pos++
			return cborBool(true), nil
		case 22, 23:
			*pos++
			return cborNull{}, nil
		case 26:
			bits, err := cborReadArg(b, pos, low)
			if err != nil {
				return nil, err
			}
			return cborFloat(float64(math.Float32frombits(uint32(bits)))), nil
		case 27:
			bits, err := cborReadArg(b, pos, low)
			if err != nil {
				return nil, err
			}
			return cborFloat(math.Float64frombits(bits)), nil
		default:
			return nil, fmt.Errorf("csil cbor: unsupported simple value %d", low)
		}
	}
	arg, err := cborReadArg(b, pos, low)
	if err != nil {
		return nil, err
	}
	switch major {
	case 0:
		return cborUint(arg), nil
	case 1:
		if arg > uint64(math.MaxInt64) {
			return nil, fmt.Errorf("csil cbor: negative integer out of range")
		}
		return cborInt(-1 - int64(arg)), nil
	case 2:
		n := int(arg)
		if *pos+n > len(b) {
			return nil, fmt.Errorf("csil cbor: truncated byte string")
		}
		slice := make([]byte, n)
		copy(slice, b[*pos:*pos+n])
		*pos += n
		return cborBytes(slice), nil
	case 3:
		n := int(arg)
		if *pos+n > len(b) {
			return nil, fmt.Errorf("csil cbor: truncated text string")
		}
		s := string(b[*pos : *pos+n])
		*pos += n
		return cborText(s), nil
	case 4:
		n := int(arg)
		items := make(cborArray, 0, n)
		for i := 0; i < n; i++ {
			item, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	case 5:
		n := int(arg)
		entries := make(cborMap, 0, n)
		for i := 0; i < n; i++ {
			k, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			val, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			entries = append(entries, cborEntry{k, val})
		}
		return entries, nil
	case 6:
		inner, err := cborDec(b, pos)
		if err != nil {
			return nil, err
		}
		return cborTag{num: arg, inner: inner}, nil
	default:
		return nil, fmt.Errorf("csil cbor: unexpected major type %d", major)
	}
}

// cborEncArray maps a typed slice to a CBOR array via the per-element encoder.
func cborEncArray[E any](xs []E, f func(E) cborValue) cborValue {
	items := make(cborArray, 0, len(xs))
	for _, x := range xs {
		items = append(items, f(x))
	}
	return items
}

// cborEncMap maps a typed map to a CBOR map. Go map iteration is unordered, so the
// inner map's entry order is not canonicalized; the record's own keys (laid down at
// generation time) are what the cross-language wire contract pins.
func cborEncMap[K comparable, V any](m map[K]V, kf func(K) cborValue, vf func(V) cborValue) cborValue {
	entries := make(cborMap, 0, len(m))
	for k, v := range m {
		entries = append(entries, cborEntry{kf(k), vf(v)})
	}
	return entries
}

func cborDecArray[E any](v cborValue, f func(cborValue) (E, error)) ([]E, error) {
	arr, err := cborAsArray(v)
	if err != nil {
		return nil, err
	}
	out := make([]E, 0, len(arr))
	for _, e := range arr {
		x, err := f(e)
		if err != nil {
			return nil, err
		}
		out = append(out, x)
	}
	return out, nil
}

func cborDecMap[K comparable, V any](v cborValue, kf func(cborValue) (K, error), vf func(cborValue) (V, error)) (map[K]V, error) {
	entries, err := cborAsMap(v)
	if err != nil {
		return nil, err
	}
	out := make(map[K]V, len(entries))
	for _, e := range entries {
		k, err := kf(e.key)
		if err != nil {
			return nil, err
		}
		val, err := vf(e.val)
		if err != nil {
			return nil, err
		}
		out[k] = val
	}
	return out, nil
}

func cborMapGet(v cborValue, key string) (cborValue, bool) {
	if m, ok := v.(cborMap); ok {
		for _, e := range m {
			if k, ok := e.key.(cborText); ok && string(k) == key {
				return e.val, true
			}
		}
	}
	return nil, false
}

func cborRequire(v cborValue, key string) (cborValue, error) {
	if x, ok := cborMapGet(v, key); ok {
		return x, nil
	}
	return nil, fmt.Errorf("csil cbor: missing field %q", key)
}

func cborAsI64(v cborValue) (int64, error) {
	switch x := v.(type) {
	case cborUint:
		if uint64(x) > uint64(math.MaxInt64) {
			return 0, fmt.Errorf("csil cbor: integer overflows int64")
		}
		return int64(x), nil
	case cborInt:
		return int64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected integer, got %T", v)
	}
}

func cborAsU64(v cborValue) (uint64, error) {
	switch x := v.(type) {
	case cborUint:
		return uint64(x), nil
	case cborInt:
		if x < 0 {
			return 0, fmt.Errorf("csil cbor: negative integer where unsigned expected")
		}
		return uint64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected unsigned integer, got %T", v)
	}
}

func cborAsF64(v cborValue) (float64, error) {
	switch x := v.(type) {
	case cborFloat:
		return float64(x), nil
	case cborUint:
		return float64(x), nil
	case cborInt:
		return float64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected float, got %T", v)
	}
}

func cborAsBool(v cborValue) (bool, error) {
	if b, ok := v.(cborBool); ok {
		return bool(b), nil
	}
	return false, fmt.Errorf("csil cbor: expected bool, got %T", v)
}

func cborAsText(v cborValue) (string, error) {
	if s, ok := v.(cborText); ok {
		return string(s), nil
	}
	return "", fmt.Errorf("csil cbor: expected text, got %T", v)
}

func cborAsBytes(v cborValue) ([]byte, error) {
	if b, ok := v.(cborBytes); ok {
		return []byte(b), nil
	}
	return nil, fmt.Errorf("csil cbor: expected byte string, got %T", v)
}

func cborAsArray(v cborValue) ([]cborValue, error) {
	if a, ok := v.(cborArray); ok {
		return []cborValue(a), nil
	}
	return nil, fmt.Errorf("csil cbor: expected array, got %T", v)
}

func cborAsMap(v cborValue) (cborMap, error) {
	if m, ok := v.(cborMap); ok {
		return m, nil
	}
	return nil, fmt.Errorf("csil cbor: expected map, got %T", v)
}

// csilEncServiceError builds the canonical CBOR value tree for a ServiceError.
func csilEncServiceError(csilV ServiceError) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("code"), cborText(csilV.Code)})
	csilEntries = append(csilEntries, cborEntry{cborText("message"), cborText(csilV.Message)})
	return csilEntries
}

// csilDecServiceError reconstructs a ServiceError from a decoded CBOR value tree.
func csilDecServiceError(csilRoot cborValue) (ServiceError, error) {
	var csilOut ServiceError
	{
		csilField, csilErr := cborRequire(csilRoot, "code")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Code = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "message")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Message = csilVal
	}
	return csilOut, nil
}

// EncodeServiceError encodes a ServiceError to canonical CSIL CBOR bytes.
func EncodeServiceError(csilV ServiceError) []byte {
	return cborEncode(csilEncServiceError(csilV))
}

// DecodeServiceError decodes canonical CSIL CBOR bytes into a ServiceError.
func DecodeServiceError(csilData []byte) (ServiceError, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero ServiceError
		return csilZero, csilErr
	}
	return csilDecServiceError(csilRoot)
}

// csilEncCustomCharacteristic builds the canonical CBOR value tree for a CustomCharacteristic.
func csilEncCustomCharacteristic(csilV CustomCharacteristic) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("key"), cborText(csilV.Key)})
	csilEntries = append(csilEntries, cborEntry{cborText("value"), csilEncCharacteristicValue(csilV.Value)})
	return csilEntries
}

// csilDecCustomCharacteristic reconstructs a CustomCharacteristic from a decoded CBOR value tree.
func csilDecCustomCharacteristic(csilRoot cborValue) (CustomCharacteristic, error) {
	var csilOut CustomCharacteristic
	{
		csilField, csilErr := cborRequire(csilRoot, "key")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Key = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "value")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (csilDecCharacteristicValue)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Value = csilVal
	}
	return csilOut, nil
}

// EncodeCustomCharacteristic encodes a CustomCharacteristic to canonical CSIL CBOR bytes.
func EncodeCustomCharacteristic(csilV CustomCharacteristic) []byte {
	return cborEncode(csilEncCustomCharacteristic(csilV))
}

// DecodeCustomCharacteristic decodes canonical CSIL CBOR bytes into a CustomCharacteristic.
func DecodeCustomCharacteristic(csilData []byte) (CustomCharacteristic, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CustomCharacteristic
		return csilZero, csilErr
	}
	return csilDecCustomCharacteristic(csilRoot)
}

// csilEncWorkerInfo builds the canonical CBOR value tree for a WorkerInfo.
func csilEncWorkerInfo(csilV WorkerInfo) cborValue {
	csilEntries := make(cborMap, 0, 6)
	csilEntries = append(csilEntries, cborEntry{cborText("os"), cborText(csilV.Os)})
	csilEntries = append(csilEntries, cborEntry{cborText("arch"), cborText(csilV.Arch)})
	csilEntries = append(csilEntries, cborEntry{cborText("custom"), cborEncArray(csilV.Custom, func(csilElem CustomCharacteristic) cborValue { return csilEncCustomCharacteristic(csilElem) })})
	if csilV.Hostname != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("hostname"), cborText((*csilV.Hostname))})
	}
	csilEntries = append(csilEntries, cborEntry{cborText("worker_key"), cborText(csilV.WorkerKey)})
	if csilV.WorkerVersion != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("worker_version"), cborText((*csilV.WorkerVersion))})
	}
	return csilEntries
}

// csilDecWorkerInfo reconstructs a WorkerInfo from a decoded CBOR value tree.
func csilDecWorkerInfo(csilRoot cborValue) (WorkerInfo, error) {
	var csilOut WorkerInfo
	{
		csilField, csilErr := cborRequire(csilRoot, "worker_key")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerKey = csilVal
	}
	if csilField, csilOk := cborMapGet(csilRoot, "hostname"); csilOk {
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Hostname = &csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "os")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Os = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "arch")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Arch = csilVal
	}
	if csilField, csilOk := cborMapGet(csilRoot, "worker_version"); csilOk {
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerVersion = &csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "custom")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]CustomCharacteristic, error) {
			return cborDecArray(csilV, csilDecCustomCharacteristic)
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Custom = csilVal
	}
	return csilOut, nil
}

// EncodeWorkerInfo encodes a WorkerInfo to canonical CSIL CBOR bytes.
func EncodeWorkerInfo(csilV WorkerInfo) []byte {
	return cborEncode(csilEncWorkerInfo(csilV))
}

// DecodeWorkerInfo decodes canonical CSIL CBOR bytes into a WorkerInfo.
func DecodeWorkerInfo(csilData []byte) (WorkerInfo, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero WorkerInfo
		return csilZero, csilErr
	}
	return csilDecWorkerInfo(csilRoot)
}

// csilEncRegisterRequest builds the canonical CBOR value tree for a RegisterRequest.
func csilEncRegisterRequest(csilV RegisterRequest) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("worker_info"), csilEncWorkerInfo(csilV.WorkerInfo)})
	csilEntries = append(csilEntries, cborEntry{cborText("enrollment_token"), cborText(csilV.EnrollmentToken)})
	return csilEntries
}

// csilDecRegisterRequest reconstructs a RegisterRequest from a decoded CBOR value tree.
func csilDecRegisterRequest(csilRoot cborValue) (RegisterRequest, error) {
	var csilOut RegisterRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "enrollment_token")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.EnrollmentToken = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "worker_info")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (csilDecWorkerInfo)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerInfo = csilVal
	}
	return csilOut, nil
}

// EncodeRegisterRequest encodes a RegisterRequest to canonical CSIL CBOR bytes.
func EncodeRegisterRequest(csilV RegisterRequest) []byte {
	return cborEncode(csilEncRegisterRequest(csilV))
}

// DecodeRegisterRequest decodes canonical CSIL CBOR bytes into a RegisterRequest.
func DecodeRegisterRequest(csilData []byte) (RegisterRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero RegisterRequest
		return csilZero, csilErr
	}
	return csilDecRegisterRequest(csilRoot)
}

// csilEncRegisterResponse builds the canonical CBOR value tree for a RegisterResponse.
func csilEncRegisterResponse(csilV RegisterResponse) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("worker_id"), cborText(csilV.WorkerId)})
	csilEntries = append(csilEntries, cborEntry{cborText("worker_session"), cborText(csilV.WorkerSession)})
	csilEntries = append(csilEntries, cborEntry{cborText("heartbeat_interval"), cborInt(csilV.HeartbeatInterval)})
	return csilEntries
}

// csilDecRegisterResponse reconstructs a RegisterResponse from a decoded CBOR value tree.
func csilDecRegisterResponse(csilRoot cborValue) (RegisterResponse, error) {
	var csilOut RegisterResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "worker_session")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerSession = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "worker_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "heartbeat_interval")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.HeartbeatInterval = csilVal
	}
	return csilOut, nil
}

// EncodeRegisterResponse encodes a RegisterResponse to canonical CSIL CBOR bytes.
func EncodeRegisterResponse(csilV RegisterResponse) []byte {
	return cborEncode(csilEncRegisterResponse(csilV))
}

// DecodeRegisterResponse decodes canonical CSIL CBOR bytes into a RegisterResponse.
func DecodeRegisterResponse(csilData []byte) (RegisterResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero RegisterResponse
		return csilZero, csilErr
	}
	return csilDecRegisterResponse(csilRoot)
}

// csilEncWorkerCharacteristics builds the canonical CBOR value tree for a WorkerCharacteristics.
func csilEncWorkerCharacteristics(csilV WorkerCharacteristics) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("os"), cborText(csilV.Os)})
	csilEntries = append(csilEntries, cborEntry{cborText("arch"), cborText(csilV.Arch)})
	csilEntries = append(csilEntries, cborEntry{cborText("custom"), cborEncArray(csilV.Custom, func(csilElem CustomCharacteristic) cborValue { return csilEncCustomCharacteristic(csilElem) })})
	return csilEntries
}

// csilDecWorkerCharacteristics reconstructs a WorkerCharacteristics from a decoded CBOR value tree.
func csilDecWorkerCharacteristics(csilRoot cborValue) (WorkerCharacteristics, error) {
	var csilOut WorkerCharacteristics
	{
		csilField, csilErr := cborRequire(csilRoot, "os")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Os = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "arch")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Arch = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "custom")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]CustomCharacteristic, error) {
			return cborDecArray(csilV, csilDecCustomCharacteristic)
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Custom = csilVal
	}
	return csilOut, nil
}

// EncodeWorkerCharacteristics encodes a WorkerCharacteristics to canonical CSIL CBOR bytes.
func EncodeWorkerCharacteristics(csilV WorkerCharacteristics) []byte {
	return cborEncode(csilEncWorkerCharacteristics(csilV))
}

// DecodeWorkerCharacteristics decodes canonical CSIL CBOR bytes into a WorkerCharacteristics.
func DecodeWorkerCharacteristics(csilData []byte) (WorkerCharacteristics, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero WorkerCharacteristics
		return csilZero, csilErr
	}
	return csilDecWorkerCharacteristics(csilRoot)
}

// csilEncRequestJobRequest builds the canonical CBOR value tree for a RequestJobRequest.
func csilEncRequestJobRequest(csilV RequestJobRequest) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("worker_characteristics"), csilEncWorkerCharacteristics(csilV.WorkerCharacteristics)})
	return csilEntries
}

// csilDecRequestJobRequest reconstructs a RequestJobRequest from a decoded CBOR value tree.
func csilDecRequestJobRequest(csilRoot cborValue) (RequestJobRequest, error) {
	var csilOut RequestJobRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "worker_characteristics")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (csilDecWorkerCharacteristics)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkerCharacteristics = csilVal
	}
	return csilOut, nil
}

// EncodeRequestJobRequest encodes a RequestJobRequest to canonical CSIL CBOR bytes.
func EncodeRequestJobRequest(csilV RequestJobRequest) []byte {
	return cborEncode(csilEncRequestJobRequest(csilV))
}

// DecodeRequestJobRequest decodes canonical CSIL CBOR bytes into a RequestJobRequest.
func DecodeRequestJobRequest(csilData []byte) (RequestJobRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero RequestJobRequest
		return csilZero, csilErr
	}
	return csilDecRequestJobRequest(csilRoot)
}

// csilEncEnvVar builds the canonical CBOR value tree for a EnvVar.
func csilEncEnvVar(csilV EnvVar) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("key"), cborText(csilV.Key)})
	csilEntries = append(csilEntries, cborEntry{cborText("value"), cborText(csilV.Value)})
	return csilEntries
}

// csilDecEnvVar reconstructs a EnvVar from a decoded CBOR value tree.
func csilDecEnvVar(csilRoot cborValue) (EnvVar, error) {
	var csilOut EnvVar
	{
		csilField, csilErr := cborRequire(csilRoot, "key")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Key = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "value")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Value = csilVal
	}
	return csilOut, nil
}

// EncodeEnvVar encodes a EnvVar to canonical CSIL CBOR bytes.
func EncodeEnvVar(csilV EnvVar) []byte {
	return cborEncode(csilEncEnvVar(csilV))
}

// DecodeEnvVar decodes canonical CSIL CBOR bytes into a EnvVar.
func DecodeEnvVar(csilData []byte) (EnvVar, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero EnvVar
		return csilZero, csilErr
	}
	return csilDecEnvVar(csilRoot)
}

// csilEncResources builds the canonical CBOR value tree for a Resources.
func csilEncResources(csilV Resources) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("cpu_limit"), cborText(csilV.CpuLimit)})
	csilEntries = append(csilEntries, cborEntry{cborText("cpu_request"), cborText(csilV.CpuRequest)})
	csilEntries = append(csilEntries, cborEntry{cborText("memory_limit"), cborText(csilV.MemoryLimit)})
	return csilEntries
}

// csilDecResources reconstructs a Resources from a decoded CBOR value tree.
func csilDecResources(csilRoot cborValue) (Resources, error) {
	var csilOut Resources
	{
		csilField, csilErr := cborRequire(csilRoot, "cpu_request")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CpuRequest = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "cpu_limit")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CpuLimit = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "memory_limit")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.MemoryLimit = csilVal
	}
	return csilOut, nil
}

// EncodeResources encodes a Resources to canonical CSIL CBOR bytes.
func EncodeResources(csilV Resources) []byte {
	return cborEncode(csilEncResources(csilV))
}

// DecodeResources decodes canonical CSIL CBOR bytes into a Resources.
func DecodeResources(csilData []byte) (Resources, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero Resources
		return csilZero, csilErr
	}
	return csilDecResources(csilRoot)
}

// csilEncVCSAuth builds the canonical CBOR value tree for a VCSAuth.
func csilEncVCSAuth(csilV VCSAuth) cborValue {
	csilEntries := make(cborMap, 0, 4)
	csilEntries = append(csilEntries, cborEntry{cborText("url"), cborText(csilV.Url)})
	csilEntries = append(csilEntries, cborEntry{cborText("token"), cborText(csilV.Token)})
	csilEntries = append(csilEntries, cborEntry{cborText("provider"), cborText(csilV.Provider)})
	csilEntries = append(csilEntries, cborEntry{cborText("username"), cborText(csilV.Username)})
	return csilEntries
}

// csilDecVCSAuth reconstructs a VCSAuth from a decoded CBOR value tree.
func csilDecVCSAuth(csilRoot cborValue) (VCSAuth, error) {
	var csilOut VCSAuth
	{
		csilField, csilErr := cborRequire(csilRoot, "provider")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Provider = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "url")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Url = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "username")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Username = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "token")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Token = csilVal
	}
	return csilOut, nil
}

// EncodeVCSAuth encodes a VCSAuth to canonical CSIL CBOR bytes.
func EncodeVCSAuth(csilV VCSAuth) []byte {
	return cborEncode(csilEncVCSAuth(csilV))
}

// DecodeVCSAuth decodes canonical CSIL CBOR bytes into a VCSAuth.
func DecodeVCSAuth(csilData []byte) (VCSAuth, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero VCSAuth
		return csilZero, csilErr
	}
	return csilDecVCSAuth(csilRoot)
}

// csilEncLease builds the canonical CBOR value tree for a Lease.
func csilEncLease(csilV Lease) cborValue {
	csilEntries := make(cborMap, 0, 13)
	csilEntries = append(csilEntries, cborEntry{cborText("env"), cborEncArray(csilV.Env, func(csilElem EnvVar) cborValue { return csilEncEnvVar(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("image"), cborText(csilV.Image)})
	csilEntries = append(csilEntries, cborEntry{cborText("job_id"), cborText(csilV.JobId)})
	csilEntries = append(csilEntries, cborEntry{cborText("command"), cborEncArray(csilV.Command, func(csilElem string) cborValue { return cborText(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("secrets"), cborEncArray(csilV.Secrets, func(csilElem EnvVar) cborValue { return csilEncEnvVar(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	if csilV.VcsAuth != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("vcs_auth"), csilEncVCSAuth((*csilV.VcsAuth))})
	}
	csilEntries = append(csilEntries, cborEntry{cborText("resources"), csilEncResources(csilV.Resources)})
	csilEntries = append(csilEntries, cborEntry{cborText("run_as_user"), cborText(csilV.RunAsUser)})
	csilEntries = append(csilEntries, cborEntry{cborText("working_dir"), cborText(csilV.WorkingDir)})
	csilEntries = append(csilEntries, cborEntry{cborText("capabilities"), cborEncArray(csilV.Capabilities, func(csilElem string) cborValue { return cborText(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("timeout_seconds"), cborInt(csilV.TimeoutSeconds)})
	csilEntries = append(csilEntries, cborEntry{cborText("cancel_grace_seconds"), cborInt(csilV.CancelGraceSeconds)})
	return csilEntries
}

// csilDecLease reconstructs a Lease from a decoded CBOR value tree.
func csilDecLease(csilRoot cborValue) (Lease, error) {
	var csilOut Lease
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "job_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.JobId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "image")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Image = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "command")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]string, error) { return cborDecArray(csilV, cborAsText) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Command = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "working_dir")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.WorkingDir = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "env")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]EnvVar, error) { return cborDecArray(csilV, csilDecEnvVar) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Env = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "secrets")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]EnvVar, error) { return cborDecArray(csilV, csilDecEnvVar) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Secrets = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "resources")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (csilDecResources)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Resources = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "timeout_seconds")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.TimeoutSeconds = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "cancel_grace_seconds")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CancelGraceSeconds = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "capabilities")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]string, error) { return cborDecArray(csilV, cborAsText) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Capabilities = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "run_as_user")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.RunAsUser = csilVal
	}
	if csilField, csilOk := cborMapGet(csilRoot, "vcs_auth"); csilOk {
		csilVal, csilErr := (csilDecVCSAuth)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.VcsAuth = &csilVal
	}
	return csilOut, nil
}

// EncodeLease encodes a Lease to canonical CSIL CBOR bytes.
func EncodeLease(csilV Lease) []byte {
	return cborEncode(csilEncLease(csilV))
}

// DecodeLease decodes canonical CSIL CBOR bytes into a Lease.
func DecodeLease(csilData []byte) (Lease, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero Lease
		return csilZero, csilErr
	}
	return csilDecLease(csilRoot)
}

// csilEncRequestJobResponse builds the canonical CBOR value tree for a RequestJobResponse.
func csilEncRequestJobResponse(csilV RequestJobResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	if csilV.Lease != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("lease"), csilEncLease((*csilV.Lease))})
	}
	csilEntries = append(csilEntries, cborEntry{cborText("has_lease"), cborBool(csilV.HasLease)})
	return csilEntries
}

// csilDecRequestJobResponse reconstructs a RequestJobResponse from a decoded CBOR value tree.
func csilDecRequestJobResponse(csilRoot cborValue) (RequestJobResponse, error) {
	var csilOut RequestJobResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "has_lease")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.HasLease = csilVal
	}
	if csilField, csilOk := cborMapGet(csilRoot, "lease"); csilOk {
		csilVal, csilErr := (csilDecLease)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Lease = &csilVal
	}
	return csilOut, nil
}

// EncodeRequestJobResponse encodes a RequestJobResponse to canonical CSIL CBOR bytes.
func EncodeRequestJobResponse(csilV RequestJobResponse) []byte {
	return cborEncode(csilEncRequestJobResponse(csilV))
}

// DecodeRequestJobResponse decodes canonical CSIL CBOR bytes into a RequestJobResponse.
func DecodeRequestJobResponse(csilData []byte) (RequestJobResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero RequestJobResponse
		return csilZero, csilErr
	}
	return csilDecRequestJobResponse(csilRoot)
}

// csilEncRunningLease builds the canonical CBOR value tree for a RunningLease.
func csilEncRunningLease(csilV RunningLease) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	return csilEntries
}

// csilDecRunningLease reconstructs a RunningLease from a decoded CBOR value tree.
func csilDecRunningLease(csilRoot cborValue) (RunningLease, error) {
	var csilOut RunningLease
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	return csilOut, nil
}

// EncodeRunningLease encodes a RunningLease to canonical CSIL CBOR bytes.
func EncodeRunningLease(csilV RunningLease) []byte {
	return cborEncode(csilEncRunningLease(csilV))
}

// DecodeRunningLease decodes canonical CSIL CBOR bytes into a RunningLease.
func DecodeRunningLease(csilData []byte) (RunningLease, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero RunningLease
		return csilZero, csilErr
	}
	return csilDecRunningLease(csilRoot)
}

// csilEncHeartbeatRequest builds the canonical CBOR value tree for a HeartbeatRequest.
func csilEncHeartbeatRequest(csilV HeartbeatRequest) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("status"), cborText(csilV.Status)})
	csilEntries = append(csilEntries, cborEntry{cborText("running_leases"), cborEncArray(csilV.RunningLeases, func(csilElem RunningLease) cborValue { return csilEncRunningLease(csilElem) })})
	return csilEntries
}

// csilDecHeartbeatRequest reconstructs a HeartbeatRequest from a decoded CBOR value tree.
func csilDecHeartbeatRequest(csilRoot cborValue) (HeartbeatRequest, error) {
	var csilOut HeartbeatRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "status")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Status = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "running_leases")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]RunningLease, error) { return cborDecArray(csilV, csilDecRunningLease) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.RunningLeases = csilVal
	}
	return csilOut, nil
}

// EncodeHeartbeatRequest encodes a HeartbeatRequest to canonical CSIL CBOR bytes.
func EncodeHeartbeatRequest(csilV HeartbeatRequest) []byte {
	return cborEncode(csilEncHeartbeatRequest(csilV))
}

// DecodeHeartbeatRequest decodes canonical CSIL CBOR bytes into a HeartbeatRequest.
func DecodeHeartbeatRequest(csilData []byte) (HeartbeatRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero HeartbeatRequest
		return csilZero, csilErr
	}
	return csilDecHeartbeatRequest(csilRoot)
}

// csilEncDirective builds the canonical CBOR value tree for a Directive.
func csilEncDirective(csilV Directive) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("action"), cborText(csilV.Action)})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	return csilEntries
}

// csilDecDirective reconstructs a Directive from a decoded CBOR value tree.
func csilDecDirective(csilRoot cborValue) (Directive, error) {
	var csilOut Directive
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "action")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Action = csilVal
	}
	return csilOut, nil
}

// EncodeDirective encodes a Directive to canonical CSIL CBOR bytes.
func EncodeDirective(csilV Directive) []byte {
	return cborEncode(csilEncDirective(csilV))
}

// DecodeDirective decodes canonical CSIL CBOR bytes into a Directive.
func DecodeDirective(csilData []byte) (Directive, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero Directive
		return csilZero, csilErr
	}
	return csilDecDirective(csilRoot)
}

// csilEncHeartbeatResponse builds the canonical CBOR value tree for a HeartbeatResponse.
func csilEncHeartbeatResponse(csilV HeartbeatResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("draining"), cborBool(csilV.Draining)})
	csilEntries = append(csilEntries, cborEntry{cborText("directives"), cborEncArray(csilV.Directives, func(csilElem Directive) cborValue { return csilEncDirective(csilElem) })})
	return csilEntries
}

// csilDecHeartbeatResponse reconstructs a HeartbeatResponse from a decoded CBOR value tree.
func csilDecHeartbeatResponse(csilRoot cborValue) (HeartbeatResponse, error) {
	var csilOut HeartbeatResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "directives")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]Directive, error) { return cborDecArray(csilV, csilDecDirective) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Directives = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "draining")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Draining = csilVal
	}
	return csilOut, nil
}

// EncodeHeartbeatResponse encodes a HeartbeatResponse to canonical CSIL CBOR bytes.
func EncodeHeartbeatResponse(csilV HeartbeatResponse) []byte {
	return cborEncode(csilEncHeartbeatResponse(csilV))
}

// DecodeHeartbeatResponse decodes canonical CSIL CBOR bytes into a HeartbeatResponse.
func DecodeHeartbeatResponse(csilData []byte) (HeartbeatResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero HeartbeatResponse
		return csilZero, csilErr
	}
	return csilDecHeartbeatResponse(csilRoot)
}

// csilEncAppendLogsRequest builds the canonical CBOR value tree for a AppendLogsRequest.
func csilEncAppendLogsRequest(csilV AppendLogsRequest) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("chunk"), cborText(csilV.Chunk)})
	csilEntries = append(csilEntries, cborEntry{cborText("stream"), cborText(csilV.Stream)})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	return csilEntries
}

// csilDecAppendLogsRequest reconstructs a AppendLogsRequest from a decoded CBOR value tree.
func csilDecAppendLogsRequest(csilRoot cborValue) (AppendLogsRequest, error) {
	var csilOut AppendLogsRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "stream")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Stream = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "chunk")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Chunk = csilVal
	}
	return csilOut, nil
}

// EncodeAppendLogsRequest encodes a AppendLogsRequest to canonical CSIL CBOR bytes.
func EncodeAppendLogsRequest(csilV AppendLogsRequest) []byte {
	return cborEncode(csilEncAppendLogsRequest(csilV))
}

// DecodeAppendLogsRequest decodes canonical CSIL CBOR bytes into a AppendLogsRequest.
func DecodeAppendLogsRequest(csilData []byte) (AppendLogsRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendLogsRequest
		return csilZero, csilErr
	}
	return csilDecAppendLogsRequest(csilRoot)
}

// csilEncAppendLogsResponse builds the canonical CBOR value tree for a AppendLogsResponse.
func csilEncAppendLogsResponse(csilV AppendLogsResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("ok"), cborBool(csilV.Ok)})
	return csilEntries
}

// csilDecAppendLogsResponse reconstructs a AppendLogsResponse from a decoded CBOR value tree.
func csilDecAppendLogsResponse(csilRoot cborValue) (AppendLogsResponse, error) {
	var csilOut AppendLogsResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "ok")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Ok = csilVal
	}
	return csilOut, nil
}

// EncodeAppendLogsResponse encodes a AppendLogsResponse to canonical CSIL CBOR bytes.
func EncodeAppendLogsResponse(csilV AppendLogsResponse) []byte {
	return cborEncode(csilEncAppendLogsResponse(csilV))
}

// DecodeAppendLogsResponse decodes canonical CSIL CBOR bytes into a AppendLogsResponse.
func DecodeAppendLogsResponse(csilData []byte) (AppendLogsResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendLogsResponse
		return csilZero, csilErr
	}
	return csilDecAppendLogsResponse(csilRoot)
}

// csilEncLogBatchEntry builds the canonical CBOR value tree for a LogBatchEntry.
func csilEncLogBatchEntry(csilV LogBatchEntry) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("level"), cborText(csilV.Level)})
	csilEntries = append(csilEntries, cborEntry{cborText("message"), cborText(csilV.Message)})
	csilEntries = append(csilEntries, cborEntry{cborText("observed_at"), cborText(csilV.ObservedAt)})
	return csilEntries
}

// csilDecLogBatchEntry reconstructs a LogBatchEntry from a decoded CBOR value tree.
func csilDecLogBatchEntry(csilRoot cborValue) (LogBatchEntry, error) {
	var csilOut LogBatchEntry
	{
		csilField, csilErr := cborRequire(csilRoot, "observed_at")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.ObservedAt = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "level")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Level = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "message")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Message = csilVal
	}
	return csilOut, nil
}

// EncodeLogBatchEntry encodes a LogBatchEntry to canonical CSIL CBOR bytes.
func EncodeLogBatchEntry(csilV LogBatchEntry) []byte {
	return cborEncode(csilEncLogBatchEntry(csilV))
}

// DecodeLogBatchEntry decodes canonical CSIL CBOR bytes into a LogBatchEntry.
func DecodeLogBatchEntry(csilData []byte) (LogBatchEntry, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero LogBatchEntry
		return csilZero, csilErr
	}
	return csilDecLogBatchEntry(csilRoot)
}

// csilEncAppendLogBatchRequest builds the canonical CBOR value tree for a AppendLogBatchRequest.
func csilEncAppendLogBatchRequest(csilV AppendLogBatchRequest) cborValue {
	csilEntries := make(cborMap, 0, 4)
	csilEntries = append(csilEntries, cborEntry{cborText("stream"), cborText(csilV.Stream)})
	csilEntries = append(csilEntries, cborEntry{cborText("entries"), cborEncArray(csilV.Entries, func(csilElem LogBatchEntry) cborValue { return csilEncLogBatchEntry(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	csilEntries = append(csilEntries, cborEntry{cborText("sequence"), cborInt(csilV.Sequence)})
	return csilEntries
}

// csilDecAppendLogBatchRequest reconstructs a AppendLogBatchRequest from a decoded CBOR value tree.
func csilDecAppendLogBatchRequest(csilRoot cborValue) (AppendLogBatchRequest, error) {
	var csilOut AppendLogBatchRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "stream")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Stream = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "sequence")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Sequence = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "entries")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]LogBatchEntry, error) { return cborDecArray(csilV, csilDecLogBatchEntry) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Entries = csilVal
	}
	return csilOut, nil
}

// EncodeAppendLogBatchRequest encodes a AppendLogBatchRequest to canonical CSIL CBOR bytes.
func EncodeAppendLogBatchRequest(csilV AppendLogBatchRequest) []byte {
	return cborEncode(csilEncAppendLogBatchRequest(csilV))
}

// DecodeAppendLogBatchRequest decodes canonical CSIL CBOR bytes into a AppendLogBatchRequest.
func DecodeAppendLogBatchRequest(csilData []byte) (AppendLogBatchRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendLogBatchRequest
		return csilZero, csilErr
	}
	return csilDecAppendLogBatchRequest(csilRoot)
}

// csilEncAppendLogBatchResponse builds the canonical CBOR value tree for a AppendLogBatchResponse.
func csilEncAppendLogBatchResponse(csilV AppendLogBatchResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("ok"), cborBool(csilV.Ok)})
	csilEntries = append(csilEntries, cborEntry{cborText("accepted_sequence"), cborInt(csilV.AcceptedSequence)})
	return csilEntries
}

// csilDecAppendLogBatchResponse reconstructs a AppendLogBatchResponse from a decoded CBOR value tree.
func csilDecAppendLogBatchResponse(csilRoot cborValue) (AppendLogBatchResponse, error) {
	var csilOut AppendLogBatchResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "ok")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Ok = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "accepted_sequence")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AcceptedSequence = csilVal
	}
	return csilOut, nil
}

// EncodeAppendLogBatchResponse encodes a AppendLogBatchResponse to canonical CSIL CBOR bytes.
func EncodeAppendLogBatchResponse(csilV AppendLogBatchResponse) []byte {
	return cborEncode(csilEncAppendLogBatchResponse(csilV))
}

// DecodeAppendLogBatchResponse decodes canonical CSIL CBOR bytes into a AppendLogBatchResponse.
func DecodeAppendLogBatchResponse(csilData []byte) (AppendLogBatchResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendLogBatchResponse
		return csilZero, csilErr
	}
	return csilDecAppendLogBatchResponse(csilRoot)
}

// csilEncMetricLabel builds the canonical CBOR value tree for a MetricLabel.
func csilEncMetricLabel(csilV MetricLabel) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("key"), cborText(csilV.Key)})
	csilEntries = append(csilEntries, cborEntry{cborText("value"), cborText(csilV.Value)})
	return csilEntries
}

// csilDecMetricLabel reconstructs a MetricLabel from a decoded CBOR value tree.
func csilDecMetricLabel(csilRoot cborValue) (MetricLabel, error) {
	var csilOut MetricLabel
	{
		csilField, csilErr := cborRequire(csilRoot, "key")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Key = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "value")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Value = csilVal
	}
	return csilOut, nil
}

// EncodeMetricLabel encodes a MetricLabel to canonical CSIL CBOR bytes.
func EncodeMetricLabel(csilV MetricLabel) []byte {
	return cborEncode(csilEncMetricLabel(csilV))
}

// DecodeMetricLabel decodes canonical CSIL CBOR bytes into a MetricLabel.
func DecodeMetricLabel(csilData []byte) (MetricLabel, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero MetricLabel
		return csilZero, csilErr
	}
	return csilDecMetricLabel(csilRoot)
}

// csilEncMetricSeriesDefinition builds the canonical CBOR value tree for a MetricSeriesDefinition.
func csilEncMetricSeriesDefinition(csilV MetricSeriesDefinition) cborValue {
	csilEntries := make(cborMap, 0, 5)
	csilEntries = append(csilEntries, cborEntry{cborText("kind"), cborText(csilV.Kind)})
	csilEntries = append(csilEntries, cborEntry{cborText("name"), cborText(csilV.Name)})
	csilEntries = append(csilEntries, cborEntry{cborText("unit"), cborText(csilV.Unit)})
	csilEntries = append(csilEntries, cborEntry{cborText("labels"), cborEncArray(csilV.Labels, func(csilElem MetricLabel) cborValue { return csilEncMetricLabel(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("series_id"), cborInt(csilV.SeriesId)})
	return csilEntries
}

// csilDecMetricSeriesDefinition reconstructs a MetricSeriesDefinition from a decoded CBOR value tree.
func csilDecMetricSeriesDefinition(csilRoot cborValue) (MetricSeriesDefinition, error) {
	var csilOut MetricSeriesDefinition
	{
		csilField, csilErr := cborRequire(csilRoot, "series_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.SeriesId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "name")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Name = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "unit")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Unit = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "kind")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Kind = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "labels")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]MetricLabel, error) { return cborDecArray(csilV, csilDecMetricLabel) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Labels = csilVal
	}
	return csilOut, nil
}

// EncodeMetricSeriesDefinition encodes a MetricSeriesDefinition to canonical CSIL CBOR bytes.
func EncodeMetricSeriesDefinition(csilV MetricSeriesDefinition) []byte {
	return cborEncode(csilEncMetricSeriesDefinition(csilV))
}

// DecodeMetricSeriesDefinition decodes canonical CSIL CBOR bytes into a MetricSeriesDefinition.
func DecodeMetricSeriesDefinition(csilData []byte) (MetricSeriesDefinition, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero MetricSeriesDefinition
		return csilZero, csilErr
	}
	return csilDecMetricSeriesDefinition(csilRoot)
}

// csilEncMetricValue builds the canonical CBOR value tree for a MetricValue.
func csilEncMetricValue(csilV MetricValue) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("value"), cborInt(csilV.Value)})
	csilEntries = append(csilEntries, cborEntry{cborText("series_id"), cborInt(csilV.SeriesId)})
	return csilEntries
}

// csilDecMetricValue reconstructs a MetricValue from a decoded CBOR value tree.
func csilDecMetricValue(csilRoot cborValue) (MetricValue, error) {
	var csilOut MetricValue
	{
		csilField, csilErr := cborRequire(csilRoot, "series_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.SeriesId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "value")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Value = csilVal
	}
	return csilOut, nil
}

// EncodeMetricValue encodes a MetricValue to canonical CSIL CBOR bytes.
func EncodeMetricValue(csilV MetricValue) []byte {
	return cborEncode(csilEncMetricValue(csilV))
}

// DecodeMetricValue decodes canonical CSIL CBOR bytes into a MetricValue.
func DecodeMetricValue(csilData []byte) (MetricValue, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero MetricValue
		return csilZero, csilErr
	}
	return csilDecMetricValue(csilRoot)
}

// csilEncMetricSample builds the canonical CBOR value tree for a MetricSample.
func csilEncMetricSample(csilV MetricSample) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("values"), cborEncArray(csilV.Values, func(csilElem MetricValue) cborValue { return csilEncMetricValue(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("observed_at"), cborText(csilV.ObservedAt)})
	return csilEntries
}

// csilDecMetricSample reconstructs a MetricSample from a decoded CBOR value tree.
func csilDecMetricSample(csilRoot cborValue) (MetricSample, error) {
	var csilOut MetricSample
	{
		csilField, csilErr := cborRequire(csilRoot, "observed_at")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.ObservedAt = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "values")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]MetricValue, error) { return cborDecArray(csilV, csilDecMetricValue) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Values = csilVal
	}
	return csilOut, nil
}

// EncodeMetricSample encodes a MetricSample to canonical CSIL CBOR bytes.
func EncodeMetricSample(csilV MetricSample) []byte {
	return cborEncode(csilEncMetricSample(csilV))
}

// DecodeMetricSample decodes canonical CSIL CBOR bytes into a MetricSample.
func DecodeMetricSample(csilData []byte) (MetricSample, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero MetricSample
		return csilZero, csilErr
	}
	return csilDecMetricSample(csilRoot)
}

// csilEncMetricUnavailable builds the canonical CBOR value tree for a MetricUnavailable.
func csilEncMetricUnavailable(csilV MetricUnavailable) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("reason"), cborText(csilV.Reason)})
	csilEntries = append(csilEntries, cborEntry{cborText("metric_prefix"), cborText(csilV.MetricPrefix)})
	return csilEntries
}

// csilDecMetricUnavailable reconstructs a MetricUnavailable from a decoded CBOR value tree.
func csilDecMetricUnavailable(csilRoot cborValue) (MetricUnavailable, error) {
	var csilOut MetricUnavailable
	{
		csilField, csilErr := cborRequire(csilRoot, "metric_prefix")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.MetricPrefix = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "reason")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Reason = csilVal
	}
	return csilOut, nil
}

// EncodeMetricUnavailable encodes a MetricUnavailable to canonical CSIL CBOR bytes.
func EncodeMetricUnavailable(csilV MetricUnavailable) []byte {
	return cborEncode(csilEncMetricUnavailable(csilV))
}

// DecodeMetricUnavailable decodes canonical CSIL CBOR bytes into a MetricUnavailable.
func DecodeMetricUnavailable(csilData []byte) (MetricUnavailable, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero MetricUnavailable
		return csilZero, csilErr
	}
	return csilDecMetricUnavailable(csilRoot)
}

// csilEncAppendMetricBatchRequest builds the canonical CBOR value tree for a AppendMetricBatchRequest.
func csilEncAppendMetricBatchRequest(csilV AppendMetricBatchRequest) cborValue {
	csilEntries := make(cborMap, 0, 5)
	csilEntries = append(csilEntries, cborEntry{cborText("series"), cborEncArray(csilV.Series, func(csilElem MetricSeriesDefinition) cborValue { return csilEncMetricSeriesDefinition(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("samples"), cborEncArray(csilV.Samples, func(csilElem MetricSample) cborValue { return csilEncMetricSample(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	csilEntries = append(csilEntries, cborEntry{cborText("sequence"), cborInt(csilV.Sequence)})
	csilEntries = append(csilEntries, cborEntry{cborText("unavailable"), cborEncArray(csilV.Unavailable, func(csilElem MetricUnavailable) cborValue { return csilEncMetricUnavailable(csilElem) })})
	return csilEntries
}

// csilDecAppendMetricBatchRequest reconstructs a AppendMetricBatchRequest from a decoded CBOR value tree.
func csilDecAppendMetricBatchRequest(csilRoot cborValue) (AppendMetricBatchRequest, error) {
	var csilOut AppendMetricBatchRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "sequence")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Sequence = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "series")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]MetricSeriesDefinition, error) {
			return cborDecArray(csilV, csilDecMetricSeriesDefinition)
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Series = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "samples")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]MetricSample, error) { return cborDecArray(csilV, csilDecMetricSample) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Samples = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "unavailable")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]MetricUnavailable, error) {
			return cborDecArray(csilV, csilDecMetricUnavailable)
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Unavailable = csilVal
	}
	return csilOut, nil
}

// EncodeAppendMetricBatchRequest encodes a AppendMetricBatchRequest to canonical CSIL CBOR bytes.
func EncodeAppendMetricBatchRequest(csilV AppendMetricBatchRequest) []byte {
	return cborEncode(csilEncAppendMetricBatchRequest(csilV))
}

// DecodeAppendMetricBatchRequest decodes canonical CSIL CBOR bytes into a AppendMetricBatchRequest.
func DecodeAppendMetricBatchRequest(csilData []byte) (AppendMetricBatchRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendMetricBatchRequest
		return csilZero, csilErr
	}
	return csilDecAppendMetricBatchRequest(csilRoot)
}

// csilEncAppendMetricBatchResponse builds the canonical CBOR value tree for a AppendMetricBatchResponse.
func csilEncAppendMetricBatchResponse(csilV AppendMetricBatchResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("ok"), cborBool(csilV.Ok)})
	csilEntries = append(csilEntries, cborEntry{cborText("accepted_sequence"), cborInt(csilV.AcceptedSequence)})
	return csilEntries
}

// csilDecAppendMetricBatchResponse reconstructs a AppendMetricBatchResponse from a decoded CBOR value tree.
func csilDecAppendMetricBatchResponse(csilRoot cborValue) (AppendMetricBatchResponse, error) {
	var csilOut AppendMetricBatchResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "ok")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Ok = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "accepted_sequence")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AcceptedSequence = csilVal
	}
	return csilOut, nil
}

// EncodeAppendMetricBatchResponse encodes a AppendMetricBatchResponse to canonical CSIL CBOR bytes.
func EncodeAppendMetricBatchResponse(csilV AppendMetricBatchResponse) []byte {
	return cborEncode(csilEncAppendMetricBatchResponse(csilV))
}

// DecodeAppendMetricBatchResponse decodes canonical CSIL CBOR bytes into a AppendMetricBatchResponse.
func DecodeAppendMetricBatchResponse(csilData []byte) (AppendMetricBatchResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero AppendMetricBatchResponse
		return csilZero, csilErr
	}
	return csilDecAppendMetricBatchResponse(csilRoot)
}

// csilEncReportResultRequest builds the canonical CBOR value tree for a ReportResultRequest.
func csilEncReportResultRequest(csilV ReportResultRequest) cborValue {
	csilEntries := make(cborMap, 0, 4)
	if csilV.Error != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("error"), cborText((*csilV.Error))})
	}
	csilEntries = append(csilEntries, cborEntry{cborText("status"), cborText(csilV.Status)})
	csilEntries = append(csilEntries, cborEntry{cborText("lease_id"), cborText(csilV.LeaseId)})
	csilEntries = append(csilEntries, cborEntry{cborText("exit_code"), cborInt(csilV.ExitCode)})
	return csilEntries
}

// csilDecReportResultRequest reconstructs a ReportResultRequest from a decoded CBOR value tree.
func csilDecReportResultRequest(csilRoot cborValue) (ReportResultRequest, error) {
	var csilOut ReportResultRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "lease_id")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.LeaseId = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "exit_code")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.ExitCode = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "status")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Status = csilVal
	}
	if csilField, csilOk := cborMapGet(csilRoot, "error"); csilOk {
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Error = &csilVal
	}
	return csilOut, nil
}

// EncodeReportResultRequest encodes a ReportResultRequest to canonical CSIL CBOR bytes.
func EncodeReportResultRequest(csilV ReportResultRequest) []byte {
	return cborEncode(csilEncReportResultRequest(csilV))
}

// DecodeReportResultRequest decodes canonical CSIL CBOR bytes into a ReportResultRequest.
func DecodeReportResultRequest(csilData []byte) (ReportResultRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero ReportResultRequest
		return csilZero, csilErr
	}
	return csilDecReportResultRequest(csilRoot)
}

// csilEncReportResultResponse builds the canonical CBOR value tree for a ReportResultResponse.
func csilEncReportResultResponse(csilV ReportResultResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("ok"), cborBool(csilV.Ok)})
	return csilEntries
}

// csilDecReportResultResponse reconstructs a ReportResultResponse from a decoded CBOR value tree.
func csilDecReportResultResponse(csilRoot cborValue) (ReportResultResponse, error) {
	var csilOut ReportResultResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "ok")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBool)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Ok = csilVal
	}
	return csilOut, nil
}

// EncodeReportResultResponse encodes a ReportResultResponse to canonical CSIL CBOR bytes.
func EncodeReportResultResponse(csilV ReportResultResponse) []byte {
	return cborEncode(csilEncReportResultResponse(csilV))
}

// DecodeReportResultResponse decodes canonical CSIL CBOR bytes into a ReportResultResponse.
func DecodeReportResultResponse(csilData []byte) (ReportResultResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero ReportResultResponse
		return csilZero, csilErr
	}
	return csilDecReportResultResponse(csilRoot)
}

// csilEncCharacteristicValue encodes a CharacteristicValue union as a tagged sum [variant_index, value].
func csilEncCharacteristicValue(csilV CharacteristicValue) cborValue {
	switch csilX := csilV.(type) {
	case string:
		return cborArray{cborUint(0), cborText(csilX)}
	case int64:
		return cborArray{cborUint(1), cborInt(csilX)}
	case bool:
		return cborArray{cborUint(2), cborBool(csilX)}
	case []string:
		return cborArray{cborUint(3), cborEncArray(csilX, func(csilElem string) cborValue { return cborText(csilElem) })}
	case []int64:
		return cborArray{cborUint(4), cborEncArray(csilX, func(csilElem int64) cborValue { return cborInt(csilElem) })}
	case []bool:
		return cborArray{cborUint(5), cborEncArray(csilX, func(csilElem bool) cborValue { return cborBool(csilElem) })}
	default:
		return cborNull{}
	}
}

// csilDecCharacteristicValue decodes a tagged sum [variant_index, value] into a CharacteristicValue union.
func csilDecCharacteristicValue(csilV cborValue) (CharacteristicValue, error) {
	csilArr, csilOk := csilV.(cborArray)
	if !csilOk || len(csilArr) != 2 {
		var csilZero CharacteristicValue
		return csilZero, fmt.Errorf("csil cbor: CharacteristicValue union expects a 2-element array")
	}
	csilIdx, csilIdxErr := cborAsU64(csilArr[0])
	if csilIdxErr != nil {
		var csilZero CharacteristicValue
		return csilZero, csilIdxErr
	}
	switch csilIdx {
	case 0:
		csilVal, csilErr := (cborAsText)(csilArr[1])
		return csilVal, csilErr
	case 1:
		csilVal, csilErr := (cborAsI64)(csilArr[1])
		return csilVal, csilErr
	case 2:
		csilVal, csilErr := (cborAsBool)(csilArr[1])
		return csilVal, csilErr
	case 3:
		csilVal, csilErr := (func(csilV cborValue) ([]string, error) { return cborDecArray(csilV, cborAsText) })(csilArr[1])
		return csilVal, csilErr
	case 4:
		csilVal, csilErr := (func(csilV cborValue) ([]int64, error) { return cborDecArray(csilV, cborAsI64) })(csilArr[1])
		return csilVal, csilErr
	case 5:
		csilVal, csilErr := (func(csilV cborValue) ([]bool, error) { return cborDecArray(csilV, cborAsBool) })(csilArr[1])
		return csilVal, csilErr
	default:
		var csilZero CharacteristicValue
		return csilZero, fmt.Errorf("csil cbor: unknown CharacteristicValue variant %d", csilIdx)
	}
}
