// Package csilapi contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

import (
	"context"
)

// ReactorcideWorker defines the service interface
type ReactorcideWorker interface {
	Register(ctx context.Context, req RegisterRequest) (RegisterResponse, error)
	RequestJob(ctx context.Context, req RequestJobRequest) (RequestJobResponse, error)
	Heartbeat(ctx context.Context, req HeartbeatRequest) (HeartbeatResponse, error)
	AppendLogs(ctx context.Context, req AppendLogsRequest) (AppendLogsResponse, error)
	ReportResult(ctx context.Context, req ReportResultRequest) (ReportResultResponse, error)
}
