// Package csilapi contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. Both names are the verbatim CSIL names (service as written,
// op in kebab-case as written), ready to go on the wire unmodified. The generated
// client owns (de)serialization via the codec; the carrier only moves bytes, so
// it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// ReactorcideWorkerClient is a typed client for the ReactorcideWorker service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ReactorcideWorkerClient struct {
	transport Transport
}

func NewReactorcideWorkerClient(transport Transport) *ReactorcideWorkerClient {
	return &ReactorcideWorkerClient{transport: transport}
}

func (c *ReactorcideWorkerClient) Register(ctx context.Context, req RegisterRequest) (RegisterResponse, error) {
	var csilZero RegisterResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideWorker", "register", EncodeRegisterRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRegisterResponse(csilResp)
}

func (c *ReactorcideWorkerClient) RequestJob(ctx context.Context, req RequestJobRequest) (RequestJobResponse, error) {
	var csilZero RequestJobResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideWorker", "request-job", EncodeRequestJobRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRequestJobResponse(csilResp)
}

func (c *ReactorcideWorkerClient) Heartbeat(ctx context.Context, req HeartbeatRequest) (HeartbeatResponse, error) {
	var csilZero HeartbeatResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideWorker", "heartbeat", EncodeHeartbeatRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeHeartbeatResponse(csilResp)
}

func (c *ReactorcideWorkerClient) AppendLogs(ctx context.Context, req AppendLogsRequest) (AppendLogsResponse, error) {
	var csilZero AppendLogsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideWorker", "append-logs", EncodeAppendLogsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAppendLogsResponse(csilResp)
}

func (c *ReactorcideWorkerClient) ReportResult(ctx context.Context, req ReportResultRequest) (ReportResultResponse, error) {
	var csilZero ReportResultResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideWorker", "report-result", EncodeReportResultRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeReportResultResponse(csilResp)
}
