// Package csilapi contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

// ServiceError represents a structured data type
type ServiceError struct {
	Code    string `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// CharacteristicValue is a type alias
type CharacteristicValue interface{}

// CustomCharacteristic represents a structured data type
type CustomCharacteristic struct {
	Key   string              `json:"key" yaml:"key"`
	Value CharacteristicValue `json:"value" yaml:"value"`
}

// WorkerInfo represents a structured data type
type WorkerInfo struct {
	WorkerKey     string                 `json:"worker_key" yaml:"worker_key"`
	Hostname      *string                `json:"hostname,omitempty" yaml:"hostname,omitempty"`
	Os            string                 `json:"os" yaml:"os"`
	Arch          string                 `json:"arch" yaml:"arch"`
	WorkerVersion *string                `json:"worker_version,omitempty" yaml:"worker_version,omitempty"`
	Custom        []CustomCharacteristic `json:"custom" yaml:"custom"`
}

// RegisterRequest represents a structured data type
type RegisterRequest struct {
	EnrollmentToken string     `json:"enrollment_token" yaml:"enrollment_token"`
	WorkerInfo      WorkerInfo `json:"worker_info" yaml:"worker_info"`
}

// RegisterResponse represents a structured data type
type RegisterResponse struct {
	WorkerSession     string `json:"worker_session" yaml:"worker_session"`
	WorkerId          string `json:"worker_id" yaml:"worker_id"`
	HeartbeatInterval int64  `json:"heartbeat_interval" yaml:"heartbeat_interval"`
}

// WorkerCharacteristics represents a structured data type
type WorkerCharacteristics struct {
	Os     string                 `json:"os" yaml:"os"`
	Arch   string                 `json:"arch" yaml:"arch"`
	Custom []CustomCharacteristic `json:"custom" yaml:"custom"`
}

// RequestJobRequest represents a structured data type
type RequestJobRequest struct {
	WorkerCharacteristics WorkerCharacteristics `json:"worker_characteristics" yaml:"worker_characteristics"`
}

// EnvVar represents a structured data type
type EnvVar struct {
	Key   string `json:"key" yaml:"key"`
	Value string `json:"value" yaml:"value"`
}

// Resources represents a structured data type
type Resources struct {
	CpuRequest  string `json:"cpu_request" yaml:"cpu_request"`
	CpuLimit    string `json:"cpu_limit" yaml:"cpu_limit"`
	MemoryLimit string `json:"memory_limit" yaml:"memory_limit"`
}

// VCSAuth represents a structured data type
type VCSAuth struct {
	Provider string `json:"provider" yaml:"provider"`
	Url      string `json:"url" yaml:"url"`
	Username string `json:"username" yaml:"username"`
	Token    string `json:"token" yaml:"token"`
}

// Lease represents a structured data type
type Lease struct {
	LeaseId            string    `json:"lease_id" yaml:"lease_id"`
	JobId              string    `json:"job_id" yaml:"job_id"`
	Image              string    `json:"image" yaml:"image"`
	Command            []string  `json:"command" yaml:"command"`
	WorkingDir         string    `json:"working_dir" yaml:"working_dir"`
	Env                []EnvVar  `json:"env" yaml:"env"`
	Secrets            []EnvVar  `json:"secrets" yaml:"secrets"`
	Resources          Resources `json:"resources" yaml:"resources"`
	TimeoutSeconds     int64     `json:"timeout_seconds" yaml:"timeout_seconds"`
	CancelGraceSeconds int64     `json:"cancel_grace_seconds" yaml:"cancel_grace_seconds"`
	Capabilities       []string  `json:"capabilities" yaml:"capabilities"`
	RunAsUser          string    `json:"run_as_user" yaml:"run_as_user"`
	VcsAuth            *VCSAuth  `json:"vcs_auth,omitempty" yaml:"vcs_auth,omitempty"`
}

// RequestJobResponse represents a structured data type
type RequestJobResponse struct {
	HasLease bool   `json:"has_lease" yaml:"has_lease"`
	Lease    *Lease `json:"lease,omitempty" yaml:"lease,omitempty"`
}

// RunningLease represents a structured data type
type RunningLease struct {
	LeaseId string `json:"lease_id" yaml:"lease_id"`
}

// HeartbeatRequest represents a structured data type
type HeartbeatRequest struct {
	Status        string         `json:"status" yaml:"status"`
	RunningLeases []RunningLease `json:"running_leases" yaml:"running_leases"`
}

// Directive represents a structured data type
type Directive struct {
	LeaseId string `json:"lease_id" yaml:"lease_id"`
	Action  string `json:"action" yaml:"action"`
}

// HeartbeatResponse represents a structured data type
type HeartbeatResponse struct {
	Directives []Directive `json:"directives" yaml:"directives"`
	Draining   bool        `json:"draining" yaml:"draining"`
}

// AppendLogsRequest represents a structured data type
type AppendLogsRequest struct {
	LeaseId string `json:"lease_id" yaml:"lease_id"`
	Stream  string `json:"stream" yaml:"stream"`
	Chunk   string `json:"chunk" yaml:"chunk"`
}

// AppendLogsResponse represents a structured data type
type AppendLogsResponse struct {
	Ok bool `json:"ok" yaml:"ok"`
}

// ReportResultRequest represents a structured data type
type ReportResultRequest struct {
	LeaseId  string  `json:"lease_id" yaml:"lease_id"`
	ExitCode int64   `json:"exit_code" yaml:"exit_code"`
	Status   string  `json:"status" yaml:"status"`
	Error    *string `json:"error,omitempty" yaml:"error,omitempty"`
}

// ReportResultResponse represents a structured data type
type ReportResultResponse struct {
	Ok bool `json:"ok" yaml:"ok"`
}
