// Package csilapi contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package csilapi

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. Both names are the verbatim CSIL names (service as written,
// op in kebab-case as written), ready to go on the wire unmodified. The generated
// client owns (de)serialization via the codec; the carrier only moves bytes, so
// it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// ReactorcideAuthClient is a typed client for the ReactorcideAuth service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ReactorcideAuthClient struct {
	transport Transport
}

func NewReactorcideAuthClient(transport Transport) *ReactorcideAuthClient {
	return &ReactorcideAuthClient{transport: transport}
}

func (c *ReactorcideAuthClient) GetAuthConfig(ctx context.Context, req GetAuthConfigRequest) (GetAuthConfigResponse, error) {
	var csilZero GetAuthConfigResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "get-auth-config", EncodeGetAuthConfigRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetAuthConfigResponse(csilResp)
}

func (c *ReactorcideAuthClient) BeginLogin(ctx context.Context, req BeginLoginRequest) (BeginLoginResponse, error) {
	var csilZero BeginLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "begin-login", EncodeBeginLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBeginLoginResponse(csilResp)
}

func (c *ReactorcideAuthClient) CompleteLogin(ctx context.Context, req CompleteLoginRequest) (CompleteLoginResponse, error) {
	var csilZero CompleteLoginResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "complete-login", EncodeCompleteLoginRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCompleteLoginResponse(csilResp)
}

func (c *ReactorcideAuthClient) Authenticate(ctx context.Context, req AuthenticateRequest) (AuthenticateResponse, error) {
	var csilZero AuthenticateResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "authenticate", EncodeAuthenticateRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAuthenticateResponse(csilResp)
}

func (c *ReactorcideAuthClient) Logout(ctx context.Context, req LogoutRequest) (LogoutResponse, error) {
	var csilZero LogoutResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "logout", EncodeLogoutRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeLogoutResponse(csilResp)
}

func (c *ReactorcideAuthClient) BootstrapAdmin(ctx context.Context, req BootstrapAdminRequest) (BootstrapAdminResponse, error) {
	var csilZero BootstrapAdminResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideAuth", "bootstrap-admin", EncodeBootstrapAdminRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeBootstrapAdminResponse(csilResp)
}

// ReactorcideUiClient is a typed client for the ReactorcideUi service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type ReactorcideUiClient struct {
	transport Transport
}

func NewReactorcideUiClient(transport Transport) *ReactorcideUiClient {
	return &ReactorcideUiClient{transport: transport}
}

func (c *ReactorcideUiClient) GetCapabilities(ctx context.Context, req GetCapabilitiesRequest) (GetCapabilitiesResponse, error) {
	var csilZero GetCapabilitiesResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "get-capabilities", EncodeGetCapabilitiesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetCapabilitiesResponse(csilResp)
}

func (c *ReactorcideUiClient) ListOrgs(ctx context.Context, req ListOrgsRequest) (ListOrgsResponse, error) {
	var csilZero ListOrgsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-orgs", EncodeListOrgsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListOrgsResponse(csilResp)
}

func (c *ReactorcideUiClient) ListProjects(ctx context.Context, req ListProjectsRequest) (ListProjectsResponse, error) {
	var csilZero ListProjectsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-projects", EncodeListProjectsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListProjectsResponse(csilResp)
}

func (c *ReactorcideUiClient) GetProject(ctx context.Context, req GetProjectRequest) (GetProjectResponse, error) {
	var csilZero GetProjectResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "get-project", EncodeGetProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetProjectResponse(csilResp)
}

func (c *ReactorcideUiClient) CreateProject(ctx context.Context, req CreateProjectRequest) (CreateProjectResponse, error) {
	var csilZero CreateProjectResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "create-project", EncodeCreateProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCreateProjectResponse(csilResp)
}

func (c *ReactorcideUiClient) UpdateProject(ctx context.Context, req UpdateProjectRequest) (UpdateProjectResponse, error) {
	var csilZero UpdateProjectResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "update-project", EncodeUpdateProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUpdateProjectResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteProject(ctx context.Context, req DeleteProjectRequest) (DeleteProjectResponse, error) {
	var csilZero DeleteProjectResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-project", EncodeDeleteProjectRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteProjectResponse(csilResp)
}

func (c *ReactorcideUiClient) ListGroups(ctx context.Context, req ListGroupsRequest) (ListGroupsResponse, error) {
	var csilZero ListGroupsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-groups", EncodeListGroupsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListGroupsResponse(csilResp)
}

func (c *ReactorcideUiClient) CreateGroup(ctx context.Context, req CreateGroupRequest) (CreateGroupResponse, error) {
	var csilZero CreateGroupResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "create-group", EncodeCreateGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCreateGroupResponse(csilResp)
}

func (c *ReactorcideUiClient) UpdateGroup(ctx context.Context, req UpdateGroupRequest) (UpdateGroupResponse, error) {
	var csilZero UpdateGroupResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "update-group", EncodeUpdateGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUpdateGroupResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteGroup(ctx context.Context, req DeleteGroupRequest) (DeleteGroupResponse, error) {
	var csilZero DeleteGroupResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-group", EncodeDeleteGroupRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteGroupResponse(csilResp)
}

func (c *ReactorcideUiClient) AddGroupMember(ctx context.Context, req AddGroupMemberRequest) (AddGroupMemberResponse, error) {
	var csilZero AddGroupMemberResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "add-group-member", EncodeAddGroupMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAddGroupMemberResponse(csilResp)
}

func (c *ReactorcideUiClient) RemoveGroupMember(ctx context.Context, req RemoveGroupMemberRequest) (RemoveGroupMemberResponse, error) {
	var csilZero RemoveGroupMemberResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "remove-group-member", EncodeRemoveGroupMemberRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRemoveGroupMemberResponse(csilResp)
}

func (c *ReactorcideUiClient) ListGroupMembers(ctx context.Context, req ListGroupMembersRequest) (ListGroupMembersResponse, error) {
	var csilZero ListGroupMembersResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-group-members", EncodeListGroupMembersRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListGroupMembersResponse(csilResp)
}

func (c *ReactorcideUiClient) ListRoleAssignments(ctx context.Context, req ListRoleAssignmentsRequest) (ListRoleAssignmentsResponse, error) {
	var csilZero ListRoleAssignmentsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-role-assignments", EncodeListRoleAssignmentsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListRoleAssignmentsResponse(csilResp)
}

func (c *ReactorcideUiClient) AssignRole(ctx context.Context, req AssignRoleRequest) (AssignRoleResponse, error) {
	var csilZero AssignRoleResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "assign-role", EncodeAssignRoleRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAssignRoleResponse(csilResp)
}

func (c *ReactorcideUiClient) RevokeRole(ctx context.Context, req RevokeRoleRequest) (RevokeRoleResponse, error) {
	var csilZero RevokeRoleResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "revoke-role", EncodeRevokeRoleRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRevokeRoleResponse(csilResp)
}

func (c *ReactorcideUiClient) ListWebhookSecrets(ctx context.Context, req ListWebhookSecretsRequest) (ListWebhookSecretsResponse, error) {
	var csilZero ListWebhookSecretsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-webhook-secrets", EncodeListWebhookSecretsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListWebhookSecretsResponse(csilResp)
}

func (c *ReactorcideUiClient) AddWebhookSecret(ctx context.Context, req AddWebhookSecretRequest) (AddWebhookSecretResponse, error) {
	var csilZero AddWebhookSecretResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "add-webhook-secret", EncodeAddWebhookSecretRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAddWebhookSecretResponse(csilResp)
}

func (c *ReactorcideUiClient) DeactivateWebhookSecret(ctx context.Context, req DeactivateWebhookSecretRequest) (DeactivateWebhookSecretResponse, error) {
	var csilZero DeactivateWebhookSecretResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "deactivate-webhook-secret", EncodeDeactivateWebhookSecretRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeactivateWebhookSecretResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteWebhookSecret(ctx context.Context, req DeleteWebhookSecretRequest) (DeleteWebhookSecretResponse, error) {
	var csilZero DeleteWebhookSecretResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-webhook-secret", EncodeDeleteWebhookSecretRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteWebhookSecretResponse(csilResp)
}

func (c *ReactorcideUiClient) ListVcsCredentials(ctx context.Context, req ListVcsCredentialsRequest) (ListVcsCredentialsResponse, error) {
	var csilZero ListVcsCredentialsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-vcs-credentials", EncodeListVcsCredentialsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListVcsCredentialsResponse(csilResp)
}

func (c *ReactorcideUiClient) AddVcsCredential(ctx context.Context, req AddVcsCredentialRequest) (AddVcsCredentialResponse, error) {
	var csilZero AddVcsCredentialResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "add-vcs-credential", EncodeAddVcsCredentialRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAddVcsCredentialResponse(csilResp)
}

func (c *ReactorcideUiClient) DeactivateVcsCredential(ctx context.Context, req DeactivateVcsCredentialRequest) (DeactivateVcsCredentialResponse, error) {
	var csilZero DeactivateVcsCredentialResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "deactivate-vcs-credential", EncodeDeactivateVcsCredentialRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeactivateVcsCredentialResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteVcsCredential(ctx context.Context, req DeleteVcsCredentialRequest) (DeleteVcsCredentialResponse, error) {
	var csilZero DeleteVcsCredentialResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-vcs-credential", EncodeDeleteVcsCredentialRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteVcsCredentialResponse(csilResp)
}

func (c *ReactorcideUiClient) SetSecret(ctx context.Context, req SetSecretRequest) (SetSecretResponse, error) {
	var csilZero SetSecretResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "set-secret", EncodeSetSecretRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSetSecretResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteSecret(ctx context.Context, req DeleteSecretRequest) (DeleteSecretResponse, error) {
	var csilZero DeleteSecretResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-secret", EncodeDeleteSecretRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteSecretResponse(csilResp)
}

func (c *ReactorcideUiClient) ListSecretPaths(ctx context.Context, req ListSecretPathsRequest) (ListSecretPathsResponse, error) {
	var csilZero ListSecretPathsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-secret-paths", EncodeListSecretPathsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListSecretPathsResponse(csilResp)
}

func (c *ReactorcideUiClient) ListSecretGrants(ctx context.Context, req ListSecretGrantsRequest) (ListSecretGrantsResponse, error) {
	var csilZero ListSecretGrantsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-secret-grants", EncodeListSecretGrantsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListSecretGrantsResponse(csilResp)
}

func (c *ReactorcideUiClient) CreateSecretGrant(ctx context.Context, req CreateSecretGrantRequest) (CreateSecretGrantResponse, error) {
	var csilZero CreateSecretGrantResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "create-secret-grant", EncodeCreateSecretGrantRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCreateSecretGrantResponse(csilResp)
}

func (c *ReactorcideUiClient) UpdateSecretGrant(ctx context.Context, req UpdateSecretGrantRequest) (UpdateSecretGrantResponse, error) {
	var csilZero UpdateSecretGrantResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "update-secret-grant", EncodeUpdateSecretGrantRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUpdateSecretGrantResponse(csilResp)
}

func (c *ReactorcideUiClient) DeleteSecretGrant(ctx context.Context, req DeleteSecretGrantRequest) (DeleteSecretGrantResponse, error) {
	var csilZero DeleteSecretGrantResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "delete-secret-grant", EncodeDeleteSecretGrantRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeDeleteSecretGrantResponse(csilResp)
}

func (c *ReactorcideUiClient) CancelJob(ctx context.Context, req CancelJobRequest) (CancelJobResponse, error) {
	var csilZero CancelJobResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "cancel-job", EncodeCancelJobRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCancelJobResponse(csilResp)
}

func (c *ReactorcideUiClient) KillJob(ctx context.Context, req KillJobRequest) (KillJobResponse, error) {
	var csilZero KillJobResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "kill-job", EncodeKillJobRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeKillJobResponse(csilResp)
}

func (c *ReactorcideUiClient) CancelWorkflow(ctx context.Context, req CancelWorkflowRequest) (CancelWorkflowResponse, error) {
	var csilZero CancelWorkflowResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "cancel-workflow", EncodeCancelWorkflowRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCancelWorkflowResponse(csilResp)
}

func (c *ReactorcideUiClient) RetryJob(ctx context.Context, req RetryJobRequest) (RetryJobResponse, error) {
	var csilZero RetryJobResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "retry-job", EncodeRetryJobRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRetryJobResponse(csilResp)
}

func (c *ReactorcideUiClient) RetryWorkflow(ctx context.Context, req RetryWorkflowRequest) (RetryWorkflowResponse, error) {
	var csilZero RetryWorkflowResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "retry-workflow", EncodeRetryWorkflowRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRetryWorkflowResponse(csilResp)
}

func (c *ReactorcideUiClient) RetryUnsuccessfulJobs(ctx context.Context, req RetryUnsuccessfulJobsRequest) (RetryUnsuccessfulJobsResponse, error) {
	var csilZero RetryUnsuccessfulJobsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "retry-unsuccessful-jobs", EncodeRetryUnsuccessfulJobsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRetryUnsuccessfulJobsResponse(csilResp)
}

func (c *ReactorcideUiClient) GetGlobalSettings(ctx context.Context, req GetGlobalSettingsRequest) (GetGlobalSettingsResponse, error) {
	var csilZero GetGlobalSettingsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "get-global-settings", EncodeGetGlobalSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetGlobalSettingsResponse(csilResp)
}

func (c *ReactorcideUiClient) UpdateGlobalSettings(ctx context.Context, req UpdateGlobalSettingsRequest) (UpdateGlobalSettingsResponse, error) {
	var csilZero UpdateGlobalSettingsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "update-global-settings", EncodeUpdateGlobalSettingsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUpdateGlobalSettingsResponse(csilResp)
}

func (c *ReactorcideUiClient) ListTrustedIdentities(ctx context.Context, req ListTrustedIdentitiesRequest) (ListTrustedIdentitiesResponse, error) {
	var csilZero ListTrustedIdentitiesResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-trusted-identities", EncodeListTrustedIdentitiesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListTrustedIdentitiesResponse(csilResp)
}

func (c *ReactorcideUiClient) AddTrustedIdentity(ctx context.Context, req AddTrustedIdentityRequest) (AddTrustedIdentityResponse, error) {
	var csilZero AddTrustedIdentityResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "add-trusted-identity", EncodeAddTrustedIdentityRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAddTrustedIdentityResponse(csilResp)
}

func (c *ReactorcideUiClient) RemoveTrustedIdentity(ctx context.Context, req RemoveTrustedIdentityRequest) (RemoveTrustedIdentityResponse, error) {
	var csilZero RemoveTrustedIdentityResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "remove-trusted-identity", EncodeRemoveTrustedIdentityRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRemoveTrustedIdentityResponse(csilResp)
}

func (c *ReactorcideUiClient) ListTrustedDomainPatterns(ctx context.Context, req ListTrustedDomainPatternsRequest) (ListTrustedDomainPatternsResponse, error) {
	var csilZero ListTrustedDomainPatternsResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "list-trusted-domain-patterns", EncodeListTrustedDomainPatternsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeListTrustedDomainPatternsResponse(csilResp)
}

func (c *ReactorcideUiClient) AddTrustedDomainPattern(ctx context.Context, req AddTrustedDomainPatternRequest) (AddTrustedDomainPatternResponse, error) {
	var csilZero AddTrustedDomainPatternResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "add-trusted-domain-pattern", EncodeAddTrustedDomainPatternRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeAddTrustedDomainPatternResponse(csilResp)
}

func (c *ReactorcideUiClient) RemoveTrustedDomainPattern(ctx context.Context, req RemoveTrustedDomainPatternRequest) (RemoveTrustedDomainPatternResponse, error) {
	var csilZero RemoveTrustedDomainPatternResponse
	csilResp, csilErr := c.transport.Call(ctx, "ReactorcideUi", "remove-trusted-domain-pattern", EncodeRemoveTrustedDomainPatternRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeRemoveTrustedDomainPatternResponse(csilResp)
}
