// Code generated by csilgen. DO NOT EDIT.
// Source: <csil spec>
// Target: typescript-typesonly

/**
 * Shared error arm for every operation in both services.
 */
export interface ServiceError {
  code: string;
  message: string;
}

/**
 * One role/permission grant effective for the authenticated caller.
 */
export interface RoleSummary {
  scopeType: string;
  scopeId?: string;
  role: string;
}

/**
 * Identity + effective roles for a logged-in caller.
 */
export interface AuthenticatedIdentity {
  userId: string;
  subject: string;
  handle: string;
  domain: string;
  displayName: string;
  isGlobalAdmin: boolean;
  roles: RoleSummary[];
}

export interface GetAuthConfigRequest {
}

export interface GetAuthConfigResponse {
  authMode: string;
  bootstrapAdminAvailable: boolean;
  hasGlobalAdmin: boolean;
}

export interface BeginLoginRequest {
  identityHint?: string;
}

export interface BeginLoginResponse {
  redirectUrl: string;
  attemptToken: string;
}

export interface CompleteLoginRequest {
  attemptToken: string;
  encryptedToken: string;
}

export interface CompleteLoginResponse {
  sessionToken: string;
  expiresAt: string;
  identity: AuthenticatedIdentity;
}

export interface AuthenticateRequest {
}

export interface AuthenticateResponse {
  authenticated: boolean;
  identity?: AuthenticatedIdentity;
}

export interface LogoutRequest {
}

export interface LogoutResponse {
  ok: boolean;
}

export interface BootstrapAdminRequest {
  bootstrapToken: string;
}

export interface BootstrapAdminResponse {
  sessionToken: string;
  expiresAt: string;
}

/**
 * Capability booleans, computed by the coordinator against the permission
 * matrix for the caller + (optional) org/project scope. The webapp renders
 * conditionally on these; the coordinator remains the sole authorizer.
 */
export interface GetCapabilitiesRequest {
  orgId?: string;
  projectId?: string;
}

export interface GetCapabilitiesResponse {
  viewPrivate: boolean;
  cancelJob: boolean;
  killJob: boolean;
  retryJob: boolean;
  createProject: boolean;
  deleteProject: boolean;
  manageWebhookSecrets: boolean;
  manageVcsCredentials: boolean;
  manageSecrets: boolean;
  manageGroups: boolean;
  manageWorkers: boolean;
  manageProjectSettings: boolean;
  manageTrustedIdentities: boolean;
  manageGlobalSettings: boolean;
  isGlobalAdmin: boolean;
  isOrgAdmin: boolean;
  isProjectOwner: boolean;
}

/**
 * Organizations own all tenant-scoped Reactorcide resources.
 */
export interface OrgSummary {
  orgId: string;
  name: string;
  displayName: string;
  status: string;
  isDefault: boolean;
  isPrivate: boolean;
}

export interface ListOrgsRequest {
}

export interface ListOrgsResponse {
  orgs: OrgSummary[];
}

export interface CreateOrgRequest {
  name: string;
  displayName?: string;
  isPrivate?: boolean;
}

export interface CreateOrgResponse {
  org: OrgSummary;
}

export interface UpdateOrgRequest {
  name: string;
  displayName?: string;
  isPrivate?: boolean;
  status?: string;
}

export interface UpdateOrgResponse {
  org: OrgSummary;
}

export interface SetDefaultOrgRequest {
  name: string;
}

export interface SetDefaultOrgResponse {
  org: OrgSummary;
}

export interface DeleteOrgRequest {
  name: string;
  replacement: string;
  confirm: boolean;
}

export interface DeleteOrgResponse {
  replacement: OrgSummary;
}

export interface ExecutionProfileSummary {
  name: string;
  denySecrets: boolean;
  secretPathAllowlist: string[];
  runtimeCapabilities: string[];
  mayRunAsRoot: boolean;
  allowedWorkerClasses: string[];
  timeoutCeilingSeconds?: number;
  resourceCeilings: any;
  cacheNamespace?: string;
  artifactNamespace?: string;
  trustedCacheWrites: boolean;
}

export interface ListExecutionProfilesRequest {
  organization: string;
}

export interface ListExecutionProfilesResponse {
  profiles: ExecutionProfileSummary[];
}

export interface PutExecutionProfileRequest {
  organization: string;
  profile: ExecutionProfileSummary;
}

export interface PutExecutionProfileResponse {
  profile: ExecutionProfileSummary;
}

export interface DeleteExecutionProfileRequest {
  organization: string;
  name: string;
}

export interface DeleteExecutionProfileResponse {
  deleted: boolean;
}

export interface WorkerClassSummary {
  name: string;
  protected: boolean;
  poolIds: string[];
}

export interface ListWorkerClassesRequest {
  organization: string;
}

export interface ListWorkerClassesResponse {
  workerClasses: WorkerClassSummary[];
}

export interface PutWorkerClassRequest {
  organization: string;
  workerClass: WorkerClassSummary;
}

export interface PutWorkerClassResponse {
  workerClass: WorkerClassSummary;
}

export interface DeleteWorkerClassRequest {
  organization: string;
  name: string;
}

export interface DeleteWorkerClassResponse {
  deleted: boolean;
}

export interface SetWorkerClassPoolRequest {
  organization: string;
  workerClass: string;
  poolId: string;
  granted: boolean;
}

export interface SetWorkerClassPoolResponse {
  ok: boolean;
}

export interface CreateCiApprovalRequest {
  organization: string;
  project: string;
  prNumber: number;
  headRepository: string;
  headSha: string;
  baseSha: string;
  policyRevision: string;
  workflowScope: string;
  executionProfile: string;
  approverSubject: string;
  expiresAt?: string;
}

export interface CreateCiApprovalResponse {
  approvalId: string;
}

export interface ProjectSummary {
  projectId: string;
  orgId: string;
  name: string;
  description: string;
  repoUrl: string;
  isPrivate: boolean;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ListProjectsRequest {
  orgId?: string;
}

export interface ListProjectsResponse {
  projects: ProjectSummary[];
}

export interface ProjectDetail {
  projectId: string;
  orgId: string;
  name: string;
  description: string;
  repoUrl: string;
  isPrivate: boolean;
  enabled: boolean;
  targetBranches: string[];
  allowedEventTypes: string[];
  defaultCiSourceType: string;
  defaultCiSourceUrl: string;
  defaultCiSourceRef: string;
  defaultRunnerImage: string;
  defaultJobCommand: string;
  defaultTimeoutSeconds: number;
  defaultQueueName: string;
  checkoutMode: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetProjectRequest {
  projectId: string;
}

export interface GetProjectResponse {
  project: ProjectDetail;
}

export interface CreateProjectRequest {
  orgId: string;
  name: string;
  description?: string;
  repoUrl: string;
  isPrivate?: boolean;
  targetBranches?: string[];
  allowedEventTypes?: string[];
  checkoutMode?: string;
}

export interface CreateProjectResponse {
  project: ProjectDetail;
}

export interface UpdateProjectRequest {
  projectId: string;
  name?: string;
  description?: string;
  isPrivate?: boolean;
  enabled?: boolean;
  targetBranches?: string[];
  allowedEventTypes?: string[];
  defaultRunnerImage?: string;
  defaultJobCommand?: string;
  defaultTimeoutSeconds?: number;
  defaultQueueName?: string;
  checkoutMode?: string;
}

export interface UpdateProjectResponse {
  project: ProjectDetail;
}

export interface DeleteProjectRequest {
  projectId: string;
}

export interface DeleteProjectResponse {
  deleted: boolean;
}

/**
 * The CI policy document, as a type rather than an opaque blob. Mirrors
 * internal/cipolicy.Policy exactly. Storage has always been JSONB and
 * put-ci-policy has always canonicalized on save, so nothing about the
 * stored form changes here -- only that the wire carries the structure
 * instead of a JSON string a client would have to parse and validate itself.
 */
export interface CiPolicySubjectMatch {
  any: string[];
}

/**
 * Grants selected workflow nodes trusted base-CI authority inside a head-CI
 * workflow. Only coordinator policy can carry this grant.
 */
export interface CiPolicyNodeAuthority {
  nodes: string[];
  ciSource?: string;
  profile?: string;
  workers?: string;
}

export interface CiPolicyUse {
  ciSource?: string;
  profile?: string;
  workers?: string;
  baseNodes?: CiPolicyNodeAuthority[];
}

export interface CiPolicyDefaults {
  ciSource?: string;
  profile?: string;
}

export interface CiPolicyRule {
  id: string;
  actors?: CiPolicySubjectMatch;
  workflows?: string[];
  paths?: string[];
  events?: string[];
  baseBranches?: string[];
  headRepository?: string;
  approval?: CiPolicySubjectMatch;
  use: CiPolicyUse;
}

export interface CiPolicyDocument {
  version: number;
  defaults?: CiPolicyDefaults;
  headCi: CiPolicyRule[];
}

export interface CiPolicyDetail {
  policyId: string;
  projectId: string;
  revision: string;
  document: CiPolicyDocument;
  createdAt: string;
  updatedAt: string;
  updatedBy?: string;
}

export interface GetCiPolicyRequest {
  projectId: string;
}

export interface GetCiPolicyResponse {
  policy: CiPolicyDetail;
}

export interface PutCiPolicyRequest {
  projectId: string;
  document: CiPolicyDocument;
  expectedRevision?: string;
}

export interface PutCiPolicyResponse {
  policy: CiPolicyDetail;
}

export interface DeleteCiPolicyRequest {
  projectId: string;
  expectedRevision?: string;
}

export interface DeleteCiPolicyResponse {
  deleted: boolean;
}

export interface GroupSummary {
  groupId: string;
  orgId: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListGroupsRequest {
  orgId: string;
}

export interface ListGroupsResponse {
  groups: GroupSummary[];
}

export interface CreateGroupRequest {
  orgId: string;
  name: string;
  description?: string;
}

export interface CreateGroupResponse {
  group: GroupSummary;
}

export interface UpdateGroupRequest {
  groupId: string;
  name?: string;
  description?: string;
}

export interface UpdateGroupResponse {
  group: GroupSummary;
}

export interface DeleteGroupRequest {
  groupId: string;
}

export interface DeleteGroupResponse {
  deleted: boolean;
}

export interface AddGroupMemberRequest {
  groupId: string;
  userId: string;
}

export interface AddGroupMemberResponse {
  added: boolean;
}

export interface RemoveGroupMemberRequest {
  groupId: string;
  userId: string;
}

export interface RemoveGroupMemberResponse {
  removed: boolean;
}

/**
 * A single group member, with just enough user info to render a member
 * list (see internal/store/models.User's fields exposed via GetUserByID).
 */
export interface GroupMemberEntry {
  userId: string;
  username: string;
}

export interface ListGroupMembersRequest {
  groupId: string;
}

export interface ListGroupMembersResponse {
  members: GroupMemberEntry[];
}

export interface RoleAssignment {
  assignmentId: string;
  principalType: string;
  principalId: string;
  scopeType: string;
  scopeId?: string;
  role: string;
  createdAt: string;
  createdBy?: string;
}

export interface ListRoleAssignmentsRequest {
  scopeType?: string;
  scopeId?: string;
  principalId?: string;
}

export interface ListRoleAssignmentsResponse {
  assignments: RoleAssignment[];
}

export interface AssignRoleRequest {
  principalType: string;
  principalId: string;
  scopeType: string;
  scopeId?: string;
  role: string;
}

export interface AssignRoleResponse {
  assignment: RoleAssignment;
}

export interface RevokeRoleRequest {
  assignmentId: string;
}

export interface RevokeRoleResponse {
  revoked: boolean;
}

/**
 * Webhook secret metadata only. The secret value is write-only: it is
 * accepted on add-webhook-secret and never returned by any op.
 */
export interface WebhookSecretSummary {
  id: string;
  projectId: string;
  provider: string;
  name: string;
  isActive: boolean;
  lastUsedAt?: string;
  createdAt: string;
  deactivatedAt?: string;
}

export interface ListWebhookSecretsRequest {
  projectId: string;
}

export interface ListWebhookSecretsResponse {
  secrets: WebhookSecretSummary[];
}

export interface AddWebhookSecretRequest {
  projectId: string;
  provider: string;
  name: string;
  value: string;
}

export interface AddWebhookSecretResponse {
  secret: WebhookSecretSummary;
}

export interface DeactivateWebhookSecretRequest {
  id: string;
}

export interface DeactivateWebhookSecretResponse {
  secret: WebhookSecretSummary;
}

export interface DeleteWebhookSecretRequest {
  id: string;
}

export interface DeleteWebhookSecretResponse {
  deleted: boolean;
}

/**
 * VCS credential metadata only; same rotation shape as webhook secrets.
 */
export interface VcsCredentialSummary {
  id: string;
  projectId: string;
  provider: string;
  name: string;
  isActive: boolean;
  lastUsedAt?: string;
  createdAt: string;
  deactivatedAt?: string;
}

export interface ListVcsCredentialsRequest {
  projectId: string;
}

export interface ListVcsCredentialsResponse {
  credentials: VcsCredentialSummary[];
}

export interface AddVcsCredentialRequest {
  projectId: string;
  provider: string;
  name: string;
  value: string;
}

export interface AddVcsCredentialResponse {
  credential: VcsCredentialSummary;
}

export interface DeactivateVcsCredentialRequest {
  id: string;
}

export interface DeactivateVcsCredentialResponse {
  credential: VcsCredentialSummary;
}

export interface DeleteVcsCredentialRequest {
  id: string;
}

export interface DeleteVcsCredentialResponse {
  deleted: boolean;
}

/**
 * Secrets are write-only through the UI: set/delete/list-paths only. No op
 * ever returns a secret value.
 */
export interface SetSecretRequest {
  orgId: string;
  path: string;
  key: string;
  value: string;
}

export interface SetSecretResponse {
  ok: boolean;
}

export interface DeleteSecretRequest {
  orgId: string;
  path: string;
  key: string;
}

export interface DeleteSecretResponse {
  deleted: boolean;
}

export interface SecretPathEntry {
  path: string;
  keys: string[];
}

export interface ListSecretPathsRequest {
  orgId: string;
  pathPrefix?: string;
}

export interface ListSecretPathsResponse {
  paths: SecretPathEntry[];
}

/**
 * Secret grants authorize a job to resolve secrets under a path pattern;
 * field names mirror internal/store/models.SecretGrant.
 */
export interface SecretGrant {
  grantId: string;
  orgId: string;
  projectId?: string;
  name: string;
  secretPathMatch: string;
  secretPathPattern: string;
  jobNameMatch: string;
  jobNamePattern?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListSecretGrantsRequest {
  orgId: string;
}

export interface ListSecretGrantsResponse {
  grants: SecretGrant[];
}

export interface CreateSecretGrantRequest {
  orgId: string;
  projectId?: string;
  name: string;
  secretPathMatch: string;
  secretPathPattern: string;
  jobNameMatch?: string;
  jobNamePattern?: string;
  description?: string;
}

export interface CreateSecretGrantResponse {
  grant: SecretGrant;
}

export interface UpdateSecretGrantRequest {
  grantId: string;
  name?: string;
  secretPathMatch?: string;
  secretPathPattern?: string;
  jobNameMatch?: string;
  jobNamePattern?: string;
  description?: string;
}

export interface UpdateSecretGrantResponse {
  grant: SecretGrant;
}

export interface DeleteSecretGrantRequest {
  grantId: string;
}

export interface DeleteSecretGrantResponse {
  deleted: boolean;
}

/**
 * Cancel is graceful (SIGTERM + CLEANUP phase); kill is immediate/forced.
 */
export interface CancelJobRequest {
  jobId: string;
}

export interface CancelJobResponse {
  jobId: string;
  status: string;
}

export interface KillJobRequest {
  jobId: string;
}

export interface KillJobResponse {
  jobId: string;
  status: string;
}

export interface CancelWorkflowRequest {
  workflowInstanceId: string;
}

export interface CancelWorkflowResponse {
  workflowInstanceId: string;
  status: string;
}

/**
 * Retry re-submits a failed/cancelled job or workflow. RetryJob clones a
 * single job in place (same workflow node, if any) into a brand-new job
 * row; RetryWorkflow starts a fresh workflow instance from a failed/
 * cancelled one (old instance untouched); RetryUnsuccessfulJobs bulk-
 * applies RetryJob to every failed/cancelled member job of a workflow, in
 * place. See internal/jobcontrol/retry.go.
 */
export interface RetryJobRequest {
  jobId: string;
}

export interface RetryJobResponse {
  jobId: string;
  status: string;
}

export interface RetryWorkflowRequest {
  workflowInstanceId: string;
}

export interface RetryWorkflowResponse {
  workflowInstanceId: string;
  status: string;
}

export interface RetryUnsuccessfulJobsRequest {
  workflowInstanceId: string;
}

export interface RetryUnsuccessfulJobsResponse {
  jobIds: string[];
  retriedCount: number;
  skippedCount: number;
}

/**
 * Global settings are a k/v store; value is opaque CBOR/JSON-ish data.
 */
export interface GlobalSettingEntry {
  key: string;
  value: any;
  updatedAt: string;
}

export interface GetGlobalSettingsRequest {
}

export interface GetGlobalSettingsResponse {
  newProjectsPrivate: boolean;
  settings: GlobalSettingEntry[];
}

export interface UpdateGlobalSettingsRequest {
  newProjectsPrivate?: boolean;
  settings?: GlobalSettingEntry[];
}

export interface UpdateGlobalSettingsResponse {
  newProjectsPrivate: boolean;
  settings: GlobalSettingEntry[];
}

/**
 * Trusted identity admission list: exact `[handle@]domain` selectors.
 */
export interface TrustedIdentity {
  domain: string;
  handle: string;
  source: string;
  createdAt: string;
}

export interface ListTrustedIdentitiesRequest {
}

export interface ListTrustedIdentitiesResponse {
  identities: TrustedIdentity[];
}

export interface AddTrustedIdentityRequest {
  domain: string;
  handle?: string;
}

export interface AddTrustedIdentityResponse {
  identity: TrustedIdentity;
}

export interface RemoveTrustedIdentityRequest {
  domain: string;
  handle?: string;
}

export interface RemoveTrustedIdentityResponse {
  removed: boolean;
}

/**
 * Trusted domain admission patterns: RE2 regexes over the login domain.
 */
export interface TrustedDomainPattern {
  patternId: string;
  pattern: string;
  description?: string;
  createdBy?: string;
  createdAt: string;
}

export interface ListTrustedDomainPatternsRequest {
}

export interface ListTrustedDomainPatternsResponse {
  patterns: TrustedDomainPattern[];
}

export interface AddTrustedDomainPatternRequest {
  pattern: string;
  description?: string;
}

export interface AddTrustedDomainPatternResponse {
  pattern: TrustedDomainPattern;
}

export interface RemoveTrustedDomainPatternRequest {
  patternId: string;
}

export interface RemoveTrustedDomainPatternResponse {
  removed: boolean;
}

/**
 * Scalar-only characteristic value -- used for queues (job/queue
 * characteristics are always scalar, never lists, per
 * "Characteristics & matching").
 */
export type CharacteristicScalar = string | number | boolean;

export interface CharacteristicEntry {
  key: string;
  value: CharacteristicScalar;
}

/**
 * Worker characteristic values may additionally be a homogeneous list
 * (worker-only) -- structurally identical to reactorcide-worker.csil's
 * CharacteristicValue, independently defined here (this file's own
 * generated package) rather than shared across an `include`, same
 * rationale as this file's own ServiceError mirror.
 */
export type WorkerCharacteristicValue = string | number | boolean | string[] | number[] | boolean[];

export interface WorkerCharacteristicEntry {
  key: string;
  value: WorkerCharacteristicValue;
}

export interface QueueSummary {
  queueId: string;
  queueUuid: string;
  characteristics: CharacteristicEntry[];
  displayName: string;
  isDefault: boolean;
  backlogCount: number;
}

export interface ListQueuesRequest {
}

export interface ListQueuesResponse {
  queues: QueueSummary[];
}

/**
 * CreateQueue lets an operator pre-create a queue (define characteristics +
 * display name up front). Characteristics are immutable once created --
 * there is no update-characteristics op, only rename-queue for the display
 * name.
 */
export interface CreateQueueRequest {
  characteristics: CharacteristicEntry[];
  displayName?: string;
}

export interface CreateQueueResponse {
  queue: QueueSummary;
}

export interface RenameQueueRequest {
  queueId: string;
  displayName: string;
}

export interface RenameQueueResponse {
  queue: QueueSummary;
}

/**
 * DeleteQueue cancels every non-terminal job routed to the queue (via the
 * existing cancel path) before removing the row. The seeded default queue
 * (is_default) may never be deleted -- rejected with invalid_argument.
 */
export interface DeleteQueueRequest {
  queueId: string;
}

export interface DeleteQueueResponse {
  deleted: boolean;
  cancelledJobIds: string[];
}

export interface WorkerSummary {
  workerId: string;
  poolId: string;
  workerKey: string;
  hostname?: string;
  os: string;
  arch: string;
  characteristics: WorkerCharacteristicEntry[];
  workerVersion?: string;
  status: string;
  lastSeenAt?: string;
  activeLeaseCount: number;
}

export interface ListWorkersRequest {
  poolId?: string;
}

export interface ListWorkersResponse {
  workers: WorkerSummary[];
}

/**
 * SetWorkerStatus is the quarantine/disable/re-activate admin control:
 * status must be one of active/quarantined/disabled. A non-active worker's
 * RequestJob calls are refused no future job offers (internal/workerapi's
 * RequestJob checks worker status before matching).
 */
export interface SetWorkerStatusRequest {
  workerId: string;
  status: string;
}

export interface SetWorkerStatusResponse {
  worker: WorkerSummary;
}

/**
 * DrainWorker asks a worker to stop accepting new work without disabling it
 * outright: modeled as the "quarantined" status (RequestJob already offers
 * no further jobs to a non-active worker) plus a heartbeat drain directive
 * so a worker still finishing existing leases learns to shut down once they
 * complete -- see internal/workerapi/service.go's Heartbeat.
 */
export interface DrainWorkerRequest {
  workerId: string;
}

export interface DrainWorkerResponse {
  worker: WorkerSummary;
}

export interface WorkerPoolSummary {
  poolId: string;
  orgId?: string;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListPoolsRequest {
  orgId?: string;
}

export interface ListPoolsResponse {
  pools: WorkerPoolSummary[];
}

export interface CreatePoolRequest {
  orgId?: string;
  name: string;
  description?: string;
}

export interface CreatePoolResponse {
  pool: WorkerPoolSummary;
}

export interface UpdatePoolRequest {
  poolId: string;
  name?: string;
  description?: string;
}

export interface UpdatePoolResponse {
  pool: WorkerPoolSummary;
}

export interface DeletePoolRequest {
  poolId: string;
}

export interface DeletePoolResponse {
  deleted: boolean;
}

/**
 * Enrollment token metadata only -- list/deactivate never return the raw
 * token or its hash. SECURITY: create-enrollment-token is the only op that
 * ever returns the raw value, exactly once at creation; it is stored
 * hash-only and no op (including list-enrollment-tokens) ever returns it
 * again.
 */
export interface EnrollmentTokenSummary {
  tokenId: string;
  poolId: string;
  name?: string;
  isActive: boolean;
  lastUsedAt?: string;
  createdAt: string;
  deactivatedAt?: string;
}

export interface CreateEnrollmentTokenRequest {
  poolId: string;
  name?: string;
}

/**
 * SECURITY: token is the raw enrollment token, returned exactly once here.
 * Only its SHA-256 hash is ever persisted (internal/workerauth); no other
 * op returns it again, and it must never be logged.
 */
export interface CreateEnrollmentTokenResponse {
  token: string;
  summary: EnrollmentTokenSummary;
}

export interface ListEnrollmentTokensRequest {
  poolId: string;
}

export interface ListEnrollmentTokensResponse {
  tokens: EnrollmentTokenSummary[];
}

export interface DeactivateEnrollmentTokenRequest {
  tokenId: string;
}

export interface DeactivateEnrollmentTokenResponse {
  summary: EnrollmentTokenSummary;
}

/**
 * Graph-ready job resource metrics. All values are integer-scaled by unit.
 * Timestamps are RFC3339 UTC text, matching other UI service timestamps.
 */
export interface GetJobMetricsRequest {
  jobId: string;
  fromTime?: string;
  toTime?: string;
  cursor?: string;
  metrics: string[];
  maxPoints: number;
  view?: string;
  component?: string;
}

export interface JobMetricLabel {
  key: string;
  value: string;
}

export interface JobMetricUnavailable {
  metricPrefix: string;
  reason: string;
}

export interface JobMetricPoint {
  observedAt: string;
  value: number;
  min?: number;
  max?: number;
}

export interface JobMetricSeries {
  name: string;
  unit: string;
  labels: JobMetricLabel[];
  points: JobMetricPoint[];
}

export interface GetJobMetricsResponse {
  series: JobMetricSeries[];
  unavailable: JobMetricUnavailable[];
  complete: boolean;
  nextCursor?: string;
  components: string[];
}

export interface GetJobLogsRequest {
  jobId: string;
  stream: string;
  cursor?: string;
  maxEntries?: number;
}

export interface JobLogEntry {
  timestamp: string;
  stream: string;
  level: string;
  message: string;
}

export interface GetJobLogsResponse {
  entries: JobLogEntry[];
  nextCursor?: string;
  hasMore?: boolean;
  complete?: boolean;
}

/**
 * One job as the UI lists and renders it. Field names match models.Job's
 * JSON so the existing REST consumers read the same shape.
 */
export interface JobSummary {
  jobId: string;
  name: string;
  description: string;
  status: string;
  lastError: string;
  createdAt: string;
  updatedAt: string;
  startedAt?: string;
  completedAt?: string;
  exitCode?: number;
  sourceUrl: string;
  sourceRef: string;
  sourceType: string;
  sourcePath: string;
  runnerImage: string;
  queueName: string;
  priority: number;
  parentJobId?: string;
  projectId?: string;
  workflowId?: string;
  workflowNodeName: string;
  ciOrigin: string;
  executionProfile: string;
  workerClass: string;
}

export interface ListJobsRequest {
  status?: string;
  projectId?: string;
  workflowId?: string;
  queueName?: string;
  limit?: number;
  offset?: number;
}

export interface ListJobsResponse {
  jobs: JobSummary[];
  total: number;
  limit: number;
  offset: number;
}

export interface GetJobRequest {
  jobId: string;
}

export interface GetJobResponse {
  job: JobSummary;
}

/**
 * One node of a workflow's DAG. depends_on is what a graph view needs; it
 * has always existed on the row and was never exposed by any API.
 */
export interface WorkflowNodeSummary {
  nodeId: string;
  name: string;
  displayName: string;
  status: string;
  dependsOn: string[];
  condition: string;
  jobId?: string;
  decisionReason: string;
  itemIndex?: number;
  completedAt?: string;
  ciOrigin: string;
  executionProfile: string;
  workerClass: string;
}

export interface WorkflowSummaryDetail {
  workflowId: string;
  kind: string;
  name: string;
  status: string;
  projectId?: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  queueName: string;
  vcsRepo: string;
  prNumber?: number;
  commitSha: string;
  jobCount: number;
  runningCount: number;
  completedCount: number;
  failedCount: number;
  skippedCount: number;
  looseJobId?: string;
  looseJobExit?: number;
  decisionSummary: string;
  parentJobId?: string;
  rootWorkflowId?: string;
  parentWorkflowId?: string;
  originJobId?: string;
  originType: string;
  triggerType: string;
  ciOrigin: string;
  executionProfile: string;
  workerClass: string;
}

export interface ListWorkflowsRequest {
  status?: string;
  projectId?: string;
  limit?: number;
  offset?: number;
}

export interface ListWorkflowsResponse {
  workflows: WorkflowSummaryDetail[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * get-workflow returns the nodes inline. A workflow, even a large one, is
 * small next to everything else the UI already transfers, so a second round
 * trip to fetch its DAG buys nothing.
 */
export interface GetWorkflowRequest {
  workflowId: string;
}

export interface GetWorkflowResponse {
  workflow: WorkflowSummaryDetail;
  nodes: WorkflowNodeSummary[];
  jobs: JobSummary[];
}

export interface EnumChoice {
  value: string;
  label: string;
  description: string;
}

/**
 * Each field is one enumerated set a form control can bind to directly.
 * 
 * Every value here is a static vocabulary of the software itself, so this op
 * is open to anonymous callers. Deployment data -- worker classes, execution
 * profiles, queue names -- is deliberately NOT served here: those are
 * org-scoped and privileged, and list-worker-classes /
 * list-execution-profiles / list-queues already authorize them correctly. A
 * form that needs one of those calls the op that guards it.
 */
export interface DescribeFormMetadataRequest {
}

export interface DescribeFormMetadataResponse {
  eventTypes: EnumChoice[];
  checkoutModes: EnumChoice[];
  nodeConditions: EnumChoice[];
  jobStatuses: EnumChoice[];
  workflowStatuses: EnumChoice[];
  ciSourceTypes: EnumChoice[];
}

