{{- if and .Values.web.enabled .Values.web.gateway.enabled }}
{{- range .Values.web.gateway.domains }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "web.name" $ }}-{{ . | replace "." "-" | trunc 53 }}
  labels:
    {{- include "web.labels" $ | nindent 4 }}
  {{- with $.Values.web.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ $.Values.web.gateway.gatewayName }}
      {{- if $.Values.web.gateway.gatewayNamespace }}
      namespace: {{ $.Values.web.gateway.gatewayNamespace }}
      {{- end }}
      sectionName: {{ $.Values.web.gateway.sectionName | default "https" }}
  hostnames:
    - {{ . | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "web.name" $ }}
          port: {{ $.Values.web.service.port }}
{{- end }}
{{- end }}
