{{- if .Values.worker.enabled }}
# Role for worker to create and manage Kubernetes Jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "worker.name" . }}-job-manager
  labels:
    {{- include "worker.labels" . | nindent 4 }}
rules:
  # Permission to create and manage Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  # Permission to get pod logs and status for job execution
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "worker.name" . }}-job-manager
  labels:
    {{- include "worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "worker.name" . }}-job-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "worker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
