{{- $secretName := .Values.defaults.userSecretName }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $userId := "" }}
{{- $token := "" }}
{{- $tokenId := "" }}

{{- /* Check if user provided a userId in values */}}
{{- if .Values.defaults.userId }}
  {{- $userId = .Values.defaults.userId }}
{{- else if $existingSecret }}
  {{- /* Preserve existing userId from secret */}}
  {{- $userId = index $existingSecret.data "user-id" | default "" }}
  {{- if $userId }}
    {{- $userId = $userId | b64dec }}
  {{- end }}
{{- end }}

{{- /* Generate new UUID if we still don't have one */}}
{{- if not $userId }}
  {{- $userId = uuidv4 }}
{{- end }}

{{- /* Preserve existing token and tokenId if present */}}
{{- if $existingSecret }}
  {{- $tokenData := index $existingSecret.data "token" | default "" }}
  {{- if $tokenData }}
    {{- $token = $tokenData | b64dec }}
  {{- end }}
  {{- $tokenIdData := index $existingSecret.data "token-id" | default "" }}
  {{- if $tokenIdData }}
    {{- $tokenId = $tokenIdData | b64dec }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  user-id: {{ $userId | quote }}
  {{- if $token }}
  token: {{ $token | quote }}
  {{- end }}
  {{- if $tokenId }}
  token-id: {{ $tokenId | quote }}
  {{- end }}
