// Package corndogs contains generated service clients.
//
// Code generated by csilgen; DO NOT EDIT.
package corndogs

import (
	"context"
	"fmt"
)

// ClientError is returned by a generated client call: a structured error the
// service returned (Code/Message), or a transport-level failure (Err).
type ClientError struct {
	Code    int64
	Message string
	Err     error
}

func (e *ClientError) Error() string {
	if e.Err != nil {
		return "transport error: " + e.Err.Error()
	}
	return fmt.Sprintf("service error %d: %s", e.Code, e.Message)
}

// Transport is the caller-supplied byte carrier: it performs the call named by
// (service, op) with the already-encoded request bytes and returns the response
// bytes, or an error. The generated client owns (de)serialization via the codec;
// the carrier only moves bytes, so it can be HTTP, a queue, or an in-process loop.
type Transport interface {
	Call(ctx context.Context, service string, op string, req []byte) ([]byte, error)
}

// CorndogsClient is a typed client for the CorndogsService service. The client owns
// (de)serialization via the generated codec; the transport only moves bytes.
type CorndogsClient struct {
	transport Transport
}

func NewCorndogsClient(transport Transport) *CorndogsClient {
	return &CorndogsClient{transport: transport}
}

func (c *CorndogsClient) SubmitTask(ctx context.Context, req SubmitTaskRequest) (SubmitTaskResponse, error) {
	var csilZero SubmitTaskResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "SubmitTask", EncodeSubmitTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeSubmitTaskResponse(csilResp)
}

func (c *CorndogsClient) GetTaskStateByID(ctx context.Context, req GetTaskStateByIDRequest) (GetTaskStateByIDResponse, error) {
	var csilZero GetTaskStateByIDResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetTaskStateByID", EncodeGetTaskStateByIDRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetTaskStateByIDResponse(csilResp)
}

func (c *CorndogsClient) GetNextTask(ctx context.Context, req GetNextTaskRequest) (GetNextTaskResponse, error) {
	var csilZero GetNextTaskResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetNextTask", EncodeGetNextTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetNextTaskResponse(csilResp)
}

func (c *CorndogsClient) UpdateTask(ctx context.Context, req UpdateTaskRequest) (UpdateTaskResponse, error) {
	var csilZero UpdateTaskResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "UpdateTask", EncodeUpdateTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeUpdateTaskResponse(csilResp)
}

func (c *CorndogsClient) CompleteTask(ctx context.Context, req CompleteTaskRequest) (CompleteTaskResponse, error) {
	var csilZero CompleteTaskResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "CompleteTask", EncodeCompleteTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCompleteTaskResponse(csilResp)
}

func (c *CorndogsClient) CancelTask(ctx context.Context, req CancelTaskRequest) (CancelTaskResponse, error) {
	var csilZero CancelTaskResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "CancelTask", EncodeCancelTaskRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCancelTaskResponse(csilResp)
}

func (c *CorndogsClient) CleanUpTimedOut(ctx context.Context, req CleanUpTimedOutRequest) (CleanUpTimedOutResponse, error) {
	var csilZero CleanUpTimedOutResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "CleanUpTimedOut", EncodeCleanUpTimedOutRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeCleanUpTimedOutResponse(csilResp)
}

func (c *CorndogsClient) GetQueues(ctx context.Context, req GetQueuesRequest) (GetQueuesResponse, error) {
	var csilZero GetQueuesResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetQueues", EncodeGetQueuesRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetQueuesResponse(csilResp)
}

func (c *CorndogsClient) GetQueueTaskCounts(ctx context.Context, req GetQueueTaskCountsRequest) (GetQueueTaskCountsResponse, error) {
	var csilZero GetQueueTaskCountsResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetQueueTaskCounts", EncodeGetQueueTaskCountsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetQueueTaskCountsResponse(csilResp)
}

func (c *CorndogsClient) GetTaskStateCounts(ctx context.Context, req GetTaskStateCountsRequest) (GetTaskStateCountsResponse, error) {
	var csilZero GetTaskStateCountsResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetTaskStateCounts", EncodeGetTaskStateCountsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetTaskStateCountsResponse(csilResp)
}

func (c *CorndogsClient) GetQueueAndStateCounts(ctx context.Context, req GetQueueAndStateCountsRequest) (GetQueueAndStateCountsResponse, error) {
	var csilZero GetQueueAndStateCountsResponse
	csilResp, csilErr := c.transport.Call(ctx, "corndogs", "GetQueueAndStateCounts", EncodeGetQueueAndStateCountsRequest(req))
	if csilErr != nil {
		return csilZero, csilErr
	}
	return DecodeGetQueueAndStateCountsResponse(csilResp)
}
