// Package corndogs contains the self-contained canonical-CBOR codec.
//
// Code generated by csilgen; DO NOT EDIT.
package corndogs

import (
	"fmt"
	"math"
)

// cborValue is a minimal canonical-CBOR value tree: a closed set of variants the
// generated codec builds and walks. The marker method keeps the set closed.
type cborValue interface{ isCbor() }

type cborUint uint64
type cborInt int64
type cborBool bool
type cborFloat float64
type cborNull struct{}
type cborText string
type cborBytes []byte
type cborArray []cborValue

// cborEntry is one map key/value pair; cborMap keeps entries ordered (a CBOR map is
// an ordered list of pairs), so the encoder controls the wire order explicitly.
type cborEntry struct {
	key cborValue
	val cborValue
}
type cborMap []cborEntry
type cborTag struct {
	num   uint64
	inner cborValue
}

func (cborUint) isCbor()  {}
func (cborInt) isCbor()   {}
func (cborBool) isCbor()  {}
func (cborFloat) isCbor() {}
func (cborNull) isCbor()  {}
func (cborText) isCbor()  {}
func (cborBytes) isCbor() {}
func (cborArray) isCbor() {}
func (cborMap) isCbor()   {}
func (cborTag) isCbor()   {}

// cborEncode serializes a value tree to canonical CBOR bytes.
func cborEncode(v cborValue) []byte {
	var out []byte
	cborEnc(v, &out)
	return out
}

func cborHead(major byte, n uint64, out *[]byte) {
	mt := major << 5
	switch {
	case n < 24:
		*out = append(*out, mt|byte(n))
	case n < 0x100:
		*out = append(*out, mt|24, byte(n))
	case n < 0x10000:
		*out = append(*out, mt|25, byte(n>>8), byte(n))
	case n < 0x100000000:
		*out = append(*out, mt|26, byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	default:
		*out = append(*out, mt|27,
			byte(n>>56), byte(n>>48), byte(n>>40), byte(n>>32),
			byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	}
}

func cborEnc(v cborValue, out *[]byte) {
	switch x := v.(type) {
	case cborUint:
		cborHead(0, uint64(x), out)
	case cborInt:
		if x >= 0 {
			cborHead(0, uint64(x), out)
		} else {
			cborHead(1, uint64(-(int64(x) + 1)), out)
		}
	case cborBool:
		if bool(x) {
			*out = append(*out, 0xf5)
		} else {
			*out = append(*out, 0xf4)
		}
	case cborNull:
		*out = append(*out, 0xf6)
	case cborFloat:
		bits := math.Float64bits(float64(x))
		*out = append(*out, 0xfb,
			byte(bits>>56), byte(bits>>48), byte(bits>>40), byte(bits>>32),
			byte(bits>>24), byte(bits>>16), byte(bits>>8), byte(bits))
	case cborText:
		s := []byte(x)
		cborHead(3, uint64(len(s)), out)
		*out = append(*out, s...)
	case cborBytes:
		cborHead(2, uint64(len(x)), out)
		*out = append(*out, x...)
	case cborArray:
		cborHead(4, uint64(len(x)), out)
		for _, e := range x {
			cborEnc(e, out)
		}
	case cborMap:
		cborHead(5, uint64(len(x)), out)
		for _, e := range x {
			cborEnc(e.key, out)
			cborEnc(e.val, out)
		}
	case cborTag:
		cborHead(6, x.num, out)
		cborEnc(x.inner, out)
	}
}

// cborDecode parses a full CBOR item and rejects trailing bytes, so a payload that
// is not exactly one value is an error rather than a silently-truncated read.
func cborDecode(b []byte) (cborValue, error) {
	pos := 0
	v, err := cborDec(b, &pos)
	if err != nil {
		return nil, err
	}
	if pos != len(b) {
		return nil, fmt.Errorf("csil cbor: %d trailing bytes", len(b)-pos)
	}
	return v, nil
}

func cborReadArg(b []byte, pos *int, low byte) (uint64, error) {
	if low < 24 {
		*pos++
		return uint64(low), nil
	}
	switch low {
	case 24:
		if *pos+2 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		v := uint64(b[*pos+1])
		*pos += 2
		return v, nil
	case 25:
		if *pos+3 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		v := uint64(b[*pos+1])<<8 | uint64(b[*pos+2])
		*pos += 3
		return v, nil
	case 26:
		if *pos+5 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		var v uint64
		for i := 1; i <= 4; i++ {
			v = v<<8 | uint64(b[*pos+i])
		}
		*pos += 5
		return v, nil
	case 27:
		if *pos+9 > len(b) {
			return 0, fmt.Errorf("csil cbor: truncated argument")
		}
		var v uint64
		for i := 1; i <= 8; i++ {
			v = v<<8 | uint64(b[*pos+i])
		}
		*pos += 9
		return v, nil
	default:
		return 0, fmt.Errorf("csil cbor: reserved additional info %d", low)
	}
}

func cborDec(b []byte, pos *int) (cborValue, error) {
	if *pos >= len(b) {
		return nil, fmt.Errorf("csil cbor: unexpected end of input")
	}
	ib := b[*pos]
	major := ib >> 5
	low := ib & 0x1f
	if major == 7 {
		switch low {
		case 20:
			*pos++
			return cborBool(false), nil
		case 21:
			*pos++
			return cborBool(true), nil
		case 22, 23:
			*pos++
			return cborNull{}, nil
		case 26:
			bits, err := cborReadArg(b, pos, low)
			if err != nil {
				return nil, err
			}
			return cborFloat(float64(math.Float32frombits(uint32(bits)))), nil
		case 27:
			bits, err := cborReadArg(b, pos, low)
			if err != nil {
				return nil, err
			}
			return cborFloat(math.Float64frombits(bits)), nil
		default:
			return nil, fmt.Errorf("csil cbor: unsupported simple value %d", low)
		}
	}
	arg, err := cborReadArg(b, pos, low)
	if err != nil {
		return nil, err
	}
	switch major {
	case 0:
		return cborUint(arg), nil
	case 1:
		if arg > uint64(math.MaxInt64) {
			return nil, fmt.Errorf("csil cbor: negative integer out of range")
		}
		return cborInt(-1 - int64(arg)), nil
	case 2:
		n := int(arg)
		if *pos+n > len(b) {
			return nil, fmt.Errorf("csil cbor: truncated byte string")
		}
		slice := make([]byte, n)
		copy(slice, b[*pos:*pos+n])
		*pos += n
		return cborBytes(slice), nil
	case 3:
		n := int(arg)
		if *pos+n > len(b) {
			return nil, fmt.Errorf("csil cbor: truncated text string")
		}
		s := string(b[*pos : *pos+n])
		*pos += n
		return cborText(s), nil
	case 4:
		n := int(arg)
		items := make(cborArray, 0, n)
		for i := 0; i < n; i++ {
			item, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	case 5:
		n := int(arg)
		entries := make(cborMap, 0, n)
		for i := 0; i < n; i++ {
			k, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			val, err := cborDec(b, pos)
			if err != nil {
				return nil, err
			}
			entries = append(entries, cborEntry{k, val})
		}
		return entries, nil
	case 6:
		inner, err := cborDec(b, pos)
		if err != nil {
			return nil, err
		}
		return cborTag{num: arg, inner: inner}, nil
	default:
		return nil, fmt.Errorf("csil cbor: unexpected major type %d", major)
	}
}

// cborEncArray maps a typed slice to a CBOR array via the per-element encoder.
func cborEncArray[E any](xs []E, f func(E) cborValue) cborValue {
	items := make(cborArray, 0, len(xs))
	for _, x := range xs {
		items = append(items, f(x))
	}
	return items
}

// cborEncMap maps a typed map to a CBOR map. Go map iteration is unordered, so the
// inner map's entry order is not canonicalized; the record's own keys (laid down at
// generation time) are what the cross-language wire contract pins.
func cborEncMap[K comparable, V any](m map[K]V, kf func(K) cborValue, vf func(V) cborValue) cborValue {
	entries := make(cborMap, 0, len(m))
	for k, v := range m {
		entries = append(entries, cborEntry{kf(k), vf(v)})
	}
	return entries
}

func cborDecArray[E any](v cborValue, f func(cborValue) (E, error)) ([]E, error) {
	arr, err := cborAsArray(v)
	if err != nil {
		return nil, err
	}
	out := make([]E, 0, len(arr))
	for _, e := range arr {
		x, err := f(e)
		if err != nil {
			return nil, err
		}
		out = append(out, x)
	}
	return out, nil
}

func cborDecMap[K comparable, V any](v cborValue, kf func(cborValue) (K, error), vf func(cborValue) (V, error)) (map[K]V, error) {
	entries, err := cborAsMap(v)
	if err != nil {
		return nil, err
	}
	out := make(map[K]V, len(entries))
	for _, e := range entries {
		k, err := kf(e.key)
		if err != nil {
			return nil, err
		}
		val, err := vf(e.val)
		if err != nil {
			return nil, err
		}
		out[k] = val
	}
	return out, nil
}

func cborMapGet(v cborValue, key string) (cborValue, bool) {
	if m, ok := v.(cborMap); ok {
		for _, e := range m {
			if k, ok := e.key.(cborText); ok && string(k) == key {
				return e.val, true
			}
		}
	}
	return nil, false
}

func cborRequire(v cborValue, key string) (cborValue, error) {
	if x, ok := cborMapGet(v, key); ok {
		return x, nil
	}
	return nil, fmt.Errorf("csil cbor: missing field %q", key)
}

func cborAsI64(v cborValue) (int64, error) {
	switch x := v.(type) {
	case cborUint:
		if uint64(x) > uint64(math.MaxInt64) {
			return 0, fmt.Errorf("csil cbor: integer overflows int64")
		}
		return int64(x), nil
	case cborInt:
		return int64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected integer, got %T", v)
	}
}

func cborAsU64(v cborValue) (uint64, error) {
	switch x := v.(type) {
	case cborUint:
		return uint64(x), nil
	case cborInt:
		if x < 0 {
			return 0, fmt.Errorf("csil cbor: negative integer where unsigned expected")
		}
		return uint64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected unsigned integer, got %T", v)
	}
}

func cborAsF64(v cborValue) (float64, error) {
	switch x := v.(type) {
	case cborFloat:
		return float64(x), nil
	case cborUint:
		return float64(x), nil
	case cborInt:
		return float64(x), nil
	default:
		return 0, fmt.Errorf("csil cbor: expected float, got %T", v)
	}
}

func cborAsBool(v cborValue) (bool, error) {
	if b, ok := v.(cborBool); ok {
		return bool(b), nil
	}
	return false, fmt.Errorf("csil cbor: expected bool, got %T", v)
}

func cborAsText(v cborValue) (string, error) {
	if s, ok := v.(cborText); ok {
		return string(s), nil
	}
	return "", fmt.Errorf("csil cbor: expected text, got %T", v)
}

func cborAsBytes(v cborValue) ([]byte, error) {
	if b, ok := v.(cborBytes); ok {
		return []byte(b), nil
	}
	return nil, fmt.Errorf("csil cbor: expected byte string, got %T", v)
}

func cborAsArray(v cborValue) ([]cborValue, error) {
	if a, ok := v.(cborArray); ok {
		return []cborValue(a), nil
	}
	return nil, fmt.Errorf("csil cbor: expected array, got %T", v)
}

func cborAsMap(v cborValue) (cborMap, error) {
	if m, ok := v.(cborMap); ok {
		return m, nil
	}
	return nil, fmt.Errorf("csil cbor: expected map, got %T", v)
}

// csilEncTask builds the canonical CBOR value tree for a Task.
func csilEncTask(csilV Task) cborValue {
	csilEntries := make(cborMap, 0, 9)
	csilEntries = append(csilEntries, cborEntry{cborText("uuid"), cborText(csilV.Uuid)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("payload"), cborBytes(csilV.Payload)})
	csilEntries = append(csilEntries, cborEntry{cborText("timeout"), cborInt(csilV.Timeout)})
	csilEntries = append(csilEntries, cborEntry{cborText("priority"), cborInt(csilV.Priority)})
	csilEntries = append(csilEntries, cborEntry{cborText("submit_time"), cborInt(csilV.SubmitTime)})
	csilEntries = append(csilEntries, cborEntry{cborText("update_time"), cborInt(csilV.UpdateTime)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	csilEntries = append(csilEntries, cborEntry{cborText("auto_target_state"), cborText(csilV.AutoTargetState)})
	return csilEntries
}

// csilDecTask reconstructs a Task from a decoded CBOR value tree.
func csilDecTask(csilRoot cborValue) (Task, error) {
	var csilOut Task
	{
		csilField, csilErr := cborRequire(csilRoot, "uuid")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Uuid = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "auto_target_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AutoTargetState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "submit_time")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.SubmitTime = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "update_time")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.UpdateTime = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "timeout")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Timeout = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "payload")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBytes)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Payload = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "priority")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Priority = csilVal
	}
	return csilOut, nil
}

// EncodeTask encodes a Task to canonical CSIL CBOR bytes.
func EncodeTask(csilV Task) []byte {
	return cborEncode(csilEncTask(csilV))
}

// DecodeTask decodes canonical CSIL CBOR bytes into a Task.
func DecodeTask(csilData []byte) (Task, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero Task
		return csilZero, csilErr
	}
	return csilDecTask(csilRoot)
}

// csilEncSubmitTaskRequest builds the canonical CBOR value tree for a SubmitTaskRequest.
func csilEncSubmitTaskRequest(csilV SubmitTaskRequest) cborValue {
	csilEntries := make(cborMap, 0, 6)
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("payload"), cborBytes(csilV.Payload)})
	csilEntries = append(csilEntries, cborEntry{cborText("timeout"), cborInt(csilV.Timeout)})
	csilEntries = append(csilEntries, cborEntry{cborText("priority"), cborInt(csilV.Priority)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	csilEntries = append(csilEntries, cborEntry{cborText("auto_target_state"), cborText(csilV.AutoTargetState)})
	return csilEntries
}

// csilDecSubmitTaskRequest reconstructs a SubmitTaskRequest from a decoded CBOR value tree.
func csilDecSubmitTaskRequest(csilRoot cborValue) (SubmitTaskRequest, error) {
	var csilOut SubmitTaskRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "auto_target_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AutoTargetState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "timeout")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Timeout = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "payload")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBytes)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Payload = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "priority")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Priority = csilVal
	}
	return csilOut, nil
}

// EncodeSubmitTaskRequest encodes a SubmitTaskRequest to canonical CSIL CBOR bytes.
func EncodeSubmitTaskRequest(csilV SubmitTaskRequest) []byte {
	return cborEncode(csilEncSubmitTaskRequest(csilV))
}

// DecodeSubmitTaskRequest decodes canonical CSIL CBOR bytes into a SubmitTaskRequest.
func DecodeSubmitTaskRequest(csilData []byte) (SubmitTaskRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero SubmitTaskRequest
		return csilZero, csilErr
	}
	return csilDecSubmitTaskRequest(csilRoot)
}

// csilEncSubmitTaskResponse builds the canonical CBOR value tree for a SubmitTaskResponse.
func csilEncSubmitTaskResponse(csilV SubmitTaskResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecSubmitTaskResponse reconstructs a SubmitTaskResponse from a decoded CBOR value tree.
func csilDecSubmitTaskResponse(csilRoot cborValue) (SubmitTaskResponse, error) {
	var csilOut SubmitTaskResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeSubmitTaskResponse encodes a SubmitTaskResponse to canonical CSIL CBOR bytes.
func EncodeSubmitTaskResponse(csilV SubmitTaskResponse) []byte {
	return cborEncode(csilEncSubmitTaskResponse(csilV))
}

// DecodeSubmitTaskResponse decodes canonical CSIL CBOR bytes into a SubmitTaskResponse.
func DecodeSubmitTaskResponse(csilData []byte) (SubmitTaskResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero SubmitTaskResponse
		return csilZero, csilErr
	}
	return csilDecSubmitTaskResponse(csilRoot)
}

// csilEncGetTaskStateByIDRequest builds the canonical CBOR value tree for a GetTaskStateByIDRequest.
func csilEncGetTaskStateByIDRequest(csilV GetTaskStateByIDRequest) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("uuid"), cborText(csilV.Uuid)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	return csilEntries
}

// csilDecGetTaskStateByIDRequest reconstructs a GetTaskStateByIDRequest from a decoded CBOR value tree.
func csilDecGetTaskStateByIDRequest(csilRoot cborValue) (GetTaskStateByIDRequest, error) {
	var csilOut GetTaskStateByIDRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "uuid")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Uuid = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	return csilOut, nil
}

// EncodeGetTaskStateByIDRequest encodes a GetTaskStateByIDRequest to canonical CSIL CBOR bytes.
func EncodeGetTaskStateByIDRequest(csilV GetTaskStateByIDRequest) []byte {
	return cborEncode(csilEncGetTaskStateByIDRequest(csilV))
}

// DecodeGetTaskStateByIDRequest decodes canonical CSIL CBOR bytes into a GetTaskStateByIDRequest.
func DecodeGetTaskStateByIDRequest(csilData []byte) (GetTaskStateByIDRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetTaskStateByIDRequest
		return csilZero, csilErr
	}
	return csilDecGetTaskStateByIDRequest(csilRoot)
}

// csilEncGetTaskStateByIDResponse builds the canonical CBOR value tree for a GetTaskStateByIDResponse.
func csilEncGetTaskStateByIDResponse(csilV GetTaskStateByIDResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecGetTaskStateByIDResponse reconstructs a GetTaskStateByIDResponse from a decoded CBOR value tree.
func csilDecGetTaskStateByIDResponse(csilRoot cborValue) (GetTaskStateByIDResponse, error) {
	var csilOut GetTaskStateByIDResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeGetTaskStateByIDResponse encodes a GetTaskStateByIDResponse to canonical CSIL CBOR bytes.
func EncodeGetTaskStateByIDResponse(csilV GetTaskStateByIDResponse) []byte {
	return cborEncode(csilEncGetTaskStateByIDResponse(csilV))
}

// DecodeGetTaskStateByIDResponse decodes canonical CSIL CBOR bytes into a GetTaskStateByIDResponse.
func DecodeGetTaskStateByIDResponse(csilData []byte) (GetTaskStateByIDResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetTaskStateByIDResponse
		return csilZero, csilErr
	}
	return csilDecGetTaskStateByIDResponse(csilRoot)
}

// csilEncGetNextTaskRequest builds the canonical CBOR value tree for a GetNextTaskRequest.
func csilEncGetNextTaskRequest(csilV GetNextTaskRequest) cborValue {
	csilEntries := make(cborMap, 0, 5)
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	csilEntries = append(csilEntries, cborEntry{cborText("override_timeout"), cborInt(csilV.OverrideTimeout)})
	csilEntries = append(csilEntries, cborEntry{cborText("override_current_state"), cborText(csilV.OverrideCurrentState)})
	csilEntries = append(csilEntries, cborEntry{cborText("override_auto_target_state"), cborText(csilV.OverrideAutoTargetState)})
	return csilEntries
}

// csilDecGetNextTaskRequest reconstructs a GetNextTaskRequest from a decoded CBOR value tree.
func csilDecGetNextTaskRequest(csilRoot cborValue) (GetNextTaskRequest, error) {
	var csilOut GetNextTaskRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "override_timeout")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.OverrideTimeout = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "override_current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.OverrideCurrentState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "override_auto_target_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.OverrideAutoTargetState = csilVal
	}
	return csilOut, nil
}

// EncodeGetNextTaskRequest encodes a GetNextTaskRequest to canonical CSIL CBOR bytes.
func EncodeGetNextTaskRequest(csilV GetNextTaskRequest) []byte {
	return cborEncode(csilEncGetNextTaskRequest(csilV))
}

// DecodeGetNextTaskRequest decodes canonical CSIL CBOR bytes into a GetNextTaskRequest.
func DecodeGetNextTaskRequest(csilData []byte) (GetNextTaskRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetNextTaskRequest
		return csilZero, csilErr
	}
	return csilDecGetNextTaskRequest(csilRoot)
}

// csilEncGetNextTaskResponse builds the canonical CBOR value tree for a GetNextTaskResponse.
func csilEncGetNextTaskResponse(csilV GetNextTaskResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecGetNextTaskResponse reconstructs a GetNextTaskResponse from a decoded CBOR value tree.
func csilDecGetNextTaskResponse(csilRoot cborValue) (GetNextTaskResponse, error) {
	var csilOut GetNextTaskResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeGetNextTaskResponse encodes a GetNextTaskResponse to canonical CSIL CBOR bytes.
func EncodeGetNextTaskResponse(csilV GetNextTaskResponse) []byte {
	return cborEncode(csilEncGetNextTaskResponse(csilV))
}

// DecodeGetNextTaskResponse decodes canonical CSIL CBOR bytes into a GetNextTaskResponse.
func DecodeGetNextTaskResponse(csilData []byte) (GetNextTaskResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetNextTaskResponse
		return csilZero, csilErr
	}
	return csilDecGetNextTaskResponse(csilRoot)
}

// csilEncCompleteTaskRequest builds the canonical CBOR value tree for a CompleteTaskRequest.
func csilEncCompleteTaskRequest(csilV CompleteTaskRequest) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("uuid"), cborText(csilV.Uuid)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	return csilEntries
}

// csilDecCompleteTaskRequest reconstructs a CompleteTaskRequest from a decoded CBOR value tree.
func csilDecCompleteTaskRequest(csilRoot cborValue) (CompleteTaskRequest, error) {
	var csilOut CompleteTaskRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "uuid")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Uuid = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	return csilOut, nil
}

// EncodeCompleteTaskRequest encodes a CompleteTaskRequest to canonical CSIL CBOR bytes.
func EncodeCompleteTaskRequest(csilV CompleteTaskRequest) []byte {
	return cborEncode(csilEncCompleteTaskRequest(csilV))
}

// DecodeCompleteTaskRequest decodes canonical CSIL CBOR bytes into a CompleteTaskRequest.
func DecodeCompleteTaskRequest(csilData []byte) (CompleteTaskRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CompleteTaskRequest
		return csilZero, csilErr
	}
	return csilDecCompleteTaskRequest(csilRoot)
}

// csilEncCompleteTaskResponse builds the canonical CBOR value tree for a CompleteTaskResponse.
func csilEncCompleteTaskResponse(csilV CompleteTaskResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecCompleteTaskResponse reconstructs a CompleteTaskResponse from a decoded CBOR value tree.
func csilDecCompleteTaskResponse(csilRoot cborValue) (CompleteTaskResponse, error) {
	var csilOut CompleteTaskResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeCompleteTaskResponse encodes a CompleteTaskResponse to canonical CSIL CBOR bytes.
func EncodeCompleteTaskResponse(csilV CompleteTaskResponse) []byte {
	return cborEncode(csilEncCompleteTaskResponse(csilV))
}

// DecodeCompleteTaskResponse decodes canonical CSIL CBOR bytes into a CompleteTaskResponse.
func DecodeCompleteTaskResponse(csilData []byte) (CompleteTaskResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CompleteTaskResponse
		return csilZero, csilErr
	}
	return csilDecCompleteTaskResponse(csilRoot)
}

// csilEncUpdateTaskRequest builds the canonical CBOR value tree for a UpdateTaskRequest.
func csilEncUpdateTaskRequest(csilV UpdateTaskRequest) cborValue {
	csilEntries := make(cborMap, 0, 8)
	csilEntries = append(csilEntries, cborEntry{cborText("uuid"), cborText(csilV.Uuid)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("payload"), cborBytes(csilV.Payload)})
	csilEntries = append(csilEntries, cborEntry{cborText("timeout"), cborInt(csilV.Timeout)})
	csilEntries = append(csilEntries, cborEntry{cborText("priority"), cborInt(csilV.Priority)})
	csilEntries = append(csilEntries, cborEntry{cborText("new_state"), cborText(csilV.NewState)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	csilEntries = append(csilEntries, cborEntry{cborText("auto_target_state"), cborText(csilV.AutoTargetState)})
	return csilEntries
}

// csilDecUpdateTaskRequest reconstructs a UpdateTaskRequest from a decoded CBOR value tree.
func csilDecUpdateTaskRequest(csilRoot cborValue) (UpdateTaskRequest, error) {
	var csilOut UpdateTaskRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "uuid")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Uuid = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "auto_target_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AutoTargetState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "timeout")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Timeout = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "new_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.NewState = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "payload")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsBytes)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Payload = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "priority")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Priority = csilVal
	}
	return csilOut, nil
}

// EncodeUpdateTaskRequest encodes a UpdateTaskRequest to canonical CSIL CBOR bytes.
func EncodeUpdateTaskRequest(csilV UpdateTaskRequest) []byte {
	return cborEncode(csilEncUpdateTaskRequest(csilV))
}

// DecodeUpdateTaskRequest decodes canonical CSIL CBOR bytes into a UpdateTaskRequest.
func DecodeUpdateTaskRequest(csilData []byte) (UpdateTaskRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero UpdateTaskRequest
		return csilZero, csilErr
	}
	return csilDecUpdateTaskRequest(csilRoot)
}

// csilEncUpdateTaskResponse builds the canonical CBOR value tree for a UpdateTaskResponse.
func csilEncUpdateTaskResponse(csilV UpdateTaskResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecUpdateTaskResponse reconstructs a UpdateTaskResponse from a decoded CBOR value tree.
func csilDecUpdateTaskResponse(csilRoot cborValue) (UpdateTaskResponse, error) {
	var csilOut UpdateTaskResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeUpdateTaskResponse encodes a UpdateTaskResponse to canonical CSIL CBOR bytes.
func EncodeUpdateTaskResponse(csilV UpdateTaskResponse) []byte {
	return cborEncode(csilEncUpdateTaskResponse(csilV))
}

// DecodeUpdateTaskResponse decodes canonical CSIL CBOR bytes into a UpdateTaskResponse.
func DecodeUpdateTaskResponse(csilData []byte) (UpdateTaskResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero UpdateTaskResponse
		return csilZero, csilErr
	}
	return csilDecUpdateTaskResponse(csilRoot)
}

// csilEncCancelTaskRequest builds the canonical CBOR value tree for a CancelTaskRequest.
func csilEncCancelTaskRequest(csilV CancelTaskRequest) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("uuid"), cborText(csilV.Uuid)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("current_state"), cborText(csilV.CurrentState)})
	return csilEntries
}

// csilDecCancelTaskRequest reconstructs a CancelTaskRequest from a decoded CBOR value tree.
func csilDecCancelTaskRequest(csilRoot cborValue) (CancelTaskRequest, error) {
	var csilOut CancelTaskRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "uuid")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Uuid = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "current_state")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.CurrentState = csilVal
	}
	return csilOut, nil
}

// EncodeCancelTaskRequest encodes a CancelTaskRequest to canonical CSIL CBOR bytes.
func EncodeCancelTaskRequest(csilV CancelTaskRequest) []byte {
	return cborEncode(csilEncCancelTaskRequest(csilV))
}

// DecodeCancelTaskRequest decodes canonical CSIL CBOR bytes into a CancelTaskRequest.
func DecodeCancelTaskRequest(csilData []byte) (CancelTaskRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CancelTaskRequest
		return csilZero, csilErr
	}
	return csilDecCancelTaskRequest(csilRoot)
}

// csilEncCancelTaskResponse builds the canonical CBOR value tree for a CancelTaskResponse.
func csilEncCancelTaskResponse(csilV CancelTaskResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	if csilV.Task != nil {
		csilEntries = append(csilEntries, cborEntry{cborText("task"), csilEncTask((*csilV.Task))})
	}
	return csilEntries
}

// csilDecCancelTaskResponse reconstructs a CancelTaskResponse from a decoded CBOR value tree.
func csilDecCancelTaskResponse(csilRoot cborValue) (CancelTaskResponse, error) {
	var csilOut CancelTaskResponse
	if csilField, csilOk := cborMapGet(csilRoot, "task"); csilOk {
		csilVal, csilErr := (csilDecTask)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Task = &csilVal
	}
	return csilOut, nil
}

// EncodeCancelTaskResponse encodes a CancelTaskResponse to canonical CSIL CBOR bytes.
func EncodeCancelTaskResponse(csilV CancelTaskResponse) []byte {
	return cborEncode(csilEncCancelTaskResponse(csilV))
}

// DecodeCancelTaskResponse decodes canonical CSIL CBOR bytes into a CancelTaskResponse.
func DecodeCancelTaskResponse(csilData []byte) (CancelTaskResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CancelTaskResponse
		return csilZero, csilErr
	}
	return csilDecCancelTaskResponse(csilRoot)
}

// csilEncCleanUpTimedOutRequest builds the canonical CBOR value tree for a CleanUpTimedOutRequest.
func csilEncCleanUpTimedOutRequest(csilV CleanUpTimedOutRequest) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("at_time"), cborInt(csilV.AtTime)})
	return csilEntries
}

// csilDecCleanUpTimedOutRequest reconstructs a CleanUpTimedOutRequest from a decoded CBOR value tree.
func csilDecCleanUpTimedOutRequest(csilRoot cborValue) (CleanUpTimedOutRequest, error) {
	var csilOut CleanUpTimedOutRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "at_time")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.AtTime = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	return csilOut, nil
}

// EncodeCleanUpTimedOutRequest encodes a CleanUpTimedOutRequest to canonical CSIL CBOR bytes.
func EncodeCleanUpTimedOutRequest(csilV CleanUpTimedOutRequest) []byte {
	return cborEncode(csilEncCleanUpTimedOutRequest(csilV))
}

// DecodeCleanUpTimedOutRequest decodes canonical CSIL CBOR bytes into a CleanUpTimedOutRequest.
func DecodeCleanUpTimedOutRequest(csilData []byte) (CleanUpTimedOutRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CleanUpTimedOutRequest
		return csilZero, csilErr
	}
	return csilDecCleanUpTimedOutRequest(csilRoot)
}

// csilEncCleanUpTimedOutResponse builds the canonical CBOR value tree for a CleanUpTimedOutResponse.
func csilEncCleanUpTimedOutResponse(csilV CleanUpTimedOutResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("timed_out"), cborInt(csilV.TimedOut)})
	return csilEntries
}

// csilDecCleanUpTimedOutResponse reconstructs a CleanUpTimedOutResponse from a decoded CBOR value tree.
func csilDecCleanUpTimedOutResponse(csilRoot cborValue) (CleanUpTimedOutResponse, error) {
	var csilOut CleanUpTimedOutResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "timed_out")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.TimedOut = csilVal
	}
	return csilOut, nil
}

// EncodeCleanUpTimedOutResponse encodes a CleanUpTimedOutResponse to canonical CSIL CBOR bytes.
func EncodeCleanUpTimedOutResponse(csilV CleanUpTimedOutResponse) []byte {
	return cborEncode(csilEncCleanUpTimedOutResponse(csilV))
}

// DecodeCleanUpTimedOutResponse decodes canonical CSIL CBOR bytes into a CleanUpTimedOutResponse.
func DecodeCleanUpTimedOutResponse(csilData []byte) (CleanUpTimedOutResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero CleanUpTimedOutResponse
		return csilZero, csilErr
	}
	return csilDecCleanUpTimedOutResponse(csilRoot)
}

// csilEncGetQueuesRequest builds the canonical CBOR value tree for a GetQueuesRequest.
func csilEncGetQueuesRequest(csilV GetQueuesRequest) cborValue {
	csilEntries := make(cborMap, 0, 0)
	return csilEntries
}

// csilDecGetQueuesRequest reconstructs a GetQueuesRequest from a decoded CBOR value tree.
func csilDecGetQueuesRequest(csilRoot cborValue) (GetQueuesRequest, error) {
	var csilOut GetQueuesRequest
	return csilOut, nil
}

// EncodeGetQueuesRequest encodes a GetQueuesRequest to canonical CSIL CBOR bytes.
func EncodeGetQueuesRequest(csilV GetQueuesRequest) []byte {
	return cborEncode(csilEncGetQueuesRequest(csilV))
}

// DecodeGetQueuesRequest decodes canonical CSIL CBOR bytes into a GetQueuesRequest.
func DecodeGetQueuesRequest(csilData []byte) (GetQueuesRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueuesRequest
		return csilZero, csilErr
	}
	return csilDecGetQueuesRequest(csilRoot)
}

// csilEncGetQueuesResponse builds the canonical CBOR value tree for a GetQueuesResponse.
func csilEncGetQueuesResponse(csilV GetQueuesResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("queues"), cborEncArray(csilV.Queues, func(csilElem string) cborValue { return cborText(csilElem) })})
	csilEntries = append(csilEntries, cborEntry{cborText("total_task_count"), cborInt(csilV.TotalTaskCount)})
	return csilEntries
}

// csilDecGetQueuesResponse reconstructs a GetQueuesResponse from a decoded CBOR value tree.
func csilDecGetQueuesResponse(csilRoot cborValue) (GetQueuesResponse, error) {
	var csilOut GetQueuesResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "queues")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) ([]string, error) { return cborDecArray(csilV, cborAsText) })(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queues = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "total_task_count")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.TotalTaskCount = csilVal
	}
	return csilOut, nil
}

// EncodeGetQueuesResponse encodes a GetQueuesResponse to canonical CSIL CBOR bytes.
func EncodeGetQueuesResponse(csilV GetQueuesResponse) []byte {
	return cborEncode(csilEncGetQueuesResponse(csilV))
}

// DecodeGetQueuesResponse decodes canonical CSIL CBOR bytes into a GetQueuesResponse.
func DecodeGetQueuesResponse(csilData []byte) (GetQueuesResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueuesResponse
		return csilZero, csilErr
	}
	return csilDecGetQueuesResponse(csilRoot)
}

// csilEncGetQueueTaskCountsRequest builds the canonical CBOR value tree for a GetQueueTaskCountsRequest.
func csilEncGetQueueTaskCountsRequest(csilV GetQueueTaskCountsRequest) cborValue {
	csilEntries := make(cborMap, 0, 0)
	return csilEntries
}

// csilDecGetQueueTaskCountsRequest reconstructs a GetQueueTaskCountsRequest from a decoded CBOR value tree.
func csilDecGetQueueTaskCountsRequest(csilRoot cborValue) (GetQueueTaskCountsRequest, error) {
	var csilOut GetQueueTaskCountsRequest
	return csilOut, nil
}

// EncodeGetQueueTaskCountsRequest encodes a GetQueueTaskCountsRequest to canonical CSIL CBOR bytes.
func EncodeGetQueueTaskCountsRequest(csilV GetQueueTaskCountsRequest) []byte {
	return cborEncode(csilEncGetQueueTaskCountsRequest(csilV))
}

// DecodeGetQueueTaskCountsRequest decodes canonical CSIL CBOR bytes into a GetQueueTaskCountsRequest.
func DecodeGetQueueTaskCountsRequest(csilData []byte) (GetQueueTaskCountsRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueueTaskCountsRequest
		return csilZero, csilErr
	}
	return csilDecGetQueueTaskCountsRequest(csilRoot)
}

// csilEncGetQueueTaskCountsResponse builds the canonical CBOR value tree for a GetQueueTaskCountsResponse.
func csilEncGetQueueTaskCountsResponse(csilV GetQueueTaskCountsResponse) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("queue_counts"), cborEncMap(csilV.QueueCounts, func(csilK string) cborValue { return cborText(csilK) }, func(csilV int64) cborValue { return cborInt(csilV) })})
	csilEntries = append(csilEntries, cborEntry{cborText("total_task_count"), cborInt(csilV.TotalTaskCount)})
	return csilEntries
}

// csilDecGetQueueTaskCountsResponse reconstructs a GetQueueTaskCountsResponse from a decoded CBOR value tree.
func csilDecGetQueueTaskCountsResponse(csilRoot cborValue) (GetQueueTaskCountsResponse, error) {
	var csilOut GetQueueTaskCountsResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "queue_counts")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) (StringInt64Map, error) {
			csilInner, csilErr := (func(csilV cborValue) (map[string]int64, error) { return cborDecMap(csilV, cborAsText, cborAsI64) })(csilV)
			return StringInt64Map(csilInner), csilErr
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.QueueCounts = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "total_task_count")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.TotalTaskCount = csilVal
	}
	return csilOut, nil
}

// EncodeGetQueueTaskCountsResponse encodes a GetQueueTaskCountsResponse to canonical CSIL CBOR bytes.
func EncodeGetQueueTaskCountsResponse(csilV GetQueueTaskCountsResponse) []byte {
	return cborEncode(csilEncGetQueueTaskCountsResponse(csilV))
}

// DecodeGetQueueTaskCountsResponse decodes canonical CSIL CBOR bytes into a GetQueueTaskCountsResponse.
func DecodeGetQueueTaskCountsResponse(csilData []byte) (GetQueueTaskCountsResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueueTaskCountsResponse
		return csilZero, csilErr
	}
	return csilDecGetQueueTaskCountsResponse(csilRoot)
}

// csilEncGetTaskStateCountsRequest builds the canonical CBOR value tree for a GetTaskStateCountsRequest.
func csilEncGetTaskStateCountsRequest(csilV GetTaskStateCountsRequest) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	return csilEntries
}

// csilDecGetTaskStateCountsRequest reconstructs a GetTaskStateCountsRequest from a decoded CBOR value tree.
func csilDecGetTaskStateCountsRequest(csilRoot cborValue) (GetTaskStateCountsRequest, error) {
	var csilOut GetTaskStateCountsRequest
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	return csilOut, nil
}

// EncodeGetTaskStateCountsRequest encodes a GetTaskStateCountsRequest to canonical CSIL CBOR bytes.
func EncodeGetTaskStateCountsRequest(csilV GetTaskStateCountsRequest) []byte {
	return cborEncode(csilEncGetTaskStateCountsRequest(csilV))
}

// DecodeGetTaskStateCountsRequest decodes canonical CSIL CBOR bytes into a GetTaskStateCountsRequest.
func DecodeGetTaskStateCountsRequest(csilData []byte) (GetTaskStateCountsRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetTaskStateCountsRequest
		return csilZero, csilErr
	}
	return csilDecGetTaskStateCountsRequest(csilRoot)
}

// csilEncGetTaskStateCountsResponse builds the canonical CBOR value tree for a GetTaskStateCountsResponse.
func csilEncGetTaskStateCountsResponse(csilV GetTaskStateCountsResponse) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("count"), cborInt(csilV.Count)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("state_counts"), cborEncMap(csilV.StateCounts, func(csilK string) cborValue { return cborText(csilK) }, func(csilV int64) cborValue { return cborInt(csilV) })})
	return csilEntries
}

// csilDecGetTaskStateCountsResponse reconstructs a GetTaskStateCountsResponse from a decoded CBOR value tree.
func csilDecGetTaskStateCountsResponse(csilRoot cborValue) (GetTaskStateCountsResponse, error) {
	var csilOut GetTaskStateCountsResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "count")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Count = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "state_counts")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) (StringInt64Map, error) {
			csilInner, csilErr := (func(csilV cborValue) (map[string]int64, error) { return cborDecMap(csilV, cborAsText, cborAsI64) })(csilV)
			return StringInt64Map(csilInner), csilErr
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.StateCounts = csilVal
	}
	return csilOut, nil
}

// EncodeGetTaskStateCountsResponse encodes a GetTaskStateCountsResponse to canonical CSIL CBOR bytes.
func EncodeGetTaskStateCountsResponse(csilV GetTaskStateCountsResponse) []byte {
	return cborEncode(csilEncGetTaskStateCountsResponse(csilV))
}

// DecodeGetTaskStateCountsResponse decodes canonical CSIL CBOR bytes into a GetTaskStateCountsResponse.
func DecodeGetTaskStateCountsResponse(csilData []byte) (GetTaskStateCountsResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetTaskStateCountsResponse
		return csilZero, csilErr
	}
	return csilDecGetTaskStateCountsResponse(csilRoot)
}

// csilEncQueueAndStateCounts builds the canonical CBOR value tree for a QueueAndStateCounts.
func csilEncQueueAndStateCounts(csilV QueueAndStateCounts) cborValue {
	csilEntries := make(cborMap, 0, 3)
	csilEntries = append(csilEntries, cborEntry{cborText("count"), cborInt(csilV.Count)})
	csilEntries = append(csilEntries, cborEntry{cborText("queue"), cborText(csilV.Queue)})
	csilEntries = append(csilEntries, cborEntry{cborText("state_counts"), cborEncMap(csilV.StateCounts, func(csilK string) cborValue { return cborText(csilK) }, func(csilV int64) cborValue { return cborInt(csilV) })})
	return csilEntries
}

// csilDecQueueAndStateCounts reconstructs a QueueAndStateCounts from a decoded CBOR value tree.
func csilDecQueueAndStateCounts(csilRoot cborValue) (QueueAndStateCounts, error) {
	var csilOut QueueAndStateCounts
	{
		csilField, csilErr := cborRequire(csilRoot, "queue")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Queue = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "count")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsI64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Count = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "state_counts")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) (StringInt64Map, error) {
			csilInner, csilErr := (func(csilV cborValue) (map[string]int64, error) { return cborDecMap(csilV, cborAsText, cborAsI64) })(csilV)
			return StringInt64Map(csilInner), csilErr
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.StateCounts = csilVal
	}
	return csilOut, nil
}

// EncodeQueueAndStateCounts encodes a QueueAndStateCounts to canonical CSIL CBOR bytes.
func EncodeQueueAndStateCounts(csilV QueueAndStateCounts) []byte {
	return cborEncode(csilEncQueueAndStateCounts(csilV))
}

// DecodeQueueAndStateCounts decodes canonical CSIL CBOR bytes into a QueueAndStateCounts.
func DecodeQueueAndStateCounts(csilData []byte) (QueueAndStateCounts, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero QueueAndStateCounts
		return csilZero, csilErr
	}
	return csilDecQueueAndStateCounts(csilRoot)
}

// csilEncGetQueueAndStateCountsRequest builds the canonical CBOR value tree for a GetQueueAndStateCountsRequest.
func csilEncGetQueueAndStateCountsRequest(csilV GetQueueAndStateCountsRequest) cborValue {
	csilEntries := make(cborMap, 0, 0)
	return csilEntries
}

// csilDecGetQueueAndStateCountsRequest reconstructs a GetQueueAndStateCountsRequest from a decoded CBOR value tree.
func csilDecGetQueueAndStateCountsRequest(csilRoot cborValue) (GetQueueAndStateCountsRequest, error) {
	var csilOut GetQueueAndStateCountsRequest
	return csilOut, nil
}

// EncodeGetQueueAndStateCountsRequest encodes a GetQueueAndStateCountsRequest to canonical CSIL CBOR bytes.
func EncodeGetQueueAndStateCountsRequest(csilV GetQueueAndStateCountsRequest) []byte {
	return cborEncode(csilEncGetQueueAndStateCountsRequest(csilV))
}

// DecodeGetQueueAndStateCountsRequest decodes canonical CSIL CBOR bytes into a GetQueueAndStateCountsRequest.
func DecodeGetQueueAndStateCountsRequest(csilData []byte) (GetQueueAndStateCountsRequest, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueueAndStateCountsRequest
		return csilZero, csilErr
	}
	return csilDecGetQueueAndStateCountsRequest(csilRoot)
}

// csilEncGetQueueAndStateCountsResponse builds the canonical CBOR value tree for a GetQueueAndStateCountsResponse.
func csilEncGetQueueAndStateCountsResponse(csilV GetQueueAndStateCountsResponse) cborValue {
	csilEntries := make(cborMap, 0, 1)
	csilEntries = append(csilEntries, cborEntry{cborText("queue_and_state_counts"), cborEncMap(csilV.QueueAndStateCounts, func(csilK string) cborValue { return cborText(csilK) }, func(csilV QueueAndStateCounts) cborValue { return csilEncQueueAndStateCounts(csilV) })})
	return csilEntries
}

// csilDecGetQueueAndStateCountsResponse reconstructs a GetQueueAndStateCountsResponse from a decoded CBOR value tree.
func csilDecGetQueueAndStateCountsResponse(csilRoot cborValue) (GetQueueAndStateCountsResponse, error) {
	var csilOut GetQueueAndStateCountsResponse
	{
		csilField, csilErr := cborRequire(csilRoot, "queue_and_state_counts")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (func(csilV cborValue) (QueueAndStateCountsMap, error) {
			csilInner, csilErr := (func(csilV cborValue) (map[string]QueueAndStateCounts, error) {
				return cborDecMap(csilV, cborAsText, csilDecQueueAndStateCounts)
			})(csilV)
			return QueueAndStateCountsMap(csilInner), csilErr
		})(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.QueueAndStateCounts = csilVal
	}
	return csilOut, nil
}

// EncodeGetQueueAndStateCountsResponse encodes a GetQueueAndStateCountsResponse to canonical CSIL CBOR bytes.
func EncodeGetQueueAndStateCountsResponse(csilV GetQueueAndStateCountsResponse) []byte {
	return cborEncode(csilEncGetQueueAndStateCountsResponse(csilV))
}

// DecodeGetQueueAndStateCountsResponse decodes canonical CSIL CBOR bytes into a GetQueueAndStateCountsResponse.
func DecodeGetQueueAndStateCountsResponse(csilData []byte) (GetQueueAndStateCountsResponse, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero GetQueueAndStateCountsResponse
		return csilZero, csilErr
	}
	return csilDecGetQueueAndStateCountsResponse(csilRoot)
}

// csilEncServiceError builds the canonical CBOR value tree for a ServiceError.
func csilEncServiceError(csilV ServiceError) cborValue {
	csilEntries := make(cborMap, 0, 2)
	csilEntries = append(csilEntries, cborEntry{cborText("code"), cborUint(csilV.Code)})
	csilEntries = append(csilEntries, cborEntry{cborText("message"), cborText(csilV.Message)})
	return csilEntries
}

// csilDecServiceError reconstructs a ServiceError from a decoded CBOR value tree.
func csilDecServiceError(csilRoot cborValue) (ServiceError, error) {
	var csilOut ServiceError
	{
		csilField, csilErr := cborRequire(csilRoot, "code")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsU64)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Code = csilVal
	}
	{
		csilField, csilErr := cborRequire(csilRoot, "message")
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilVal, csilErr := (cborAsText)(csilField)
		if csilErr != nil {
			return csilOut, csilErr
		}
		csilOut.Message = csilVal
	}
	return csilOut, nil
}

// EncodeServiceError encodes a ServiceError to canonical CSIL CBOR bytes.
func EncodeServiceError(csilV ServiceError) []byte {
	return cborEncode(csilEncServiceError(csilV))
}

// DecodeServiceError decodes canonical CSIL CBOR bytes into a ServiceError.
func DecodeServiceError(csilData []byte) (ServiceError, error) {
	csilRoot, csilErr := cborDecode(csilData)
	if csilErr != nil {
		var csilZero ServiceError
		return csilZero, csilErr
	}
	return csilDecServiceError(csilRoot)
}
