// Package corndogs contains generated service interfaces.
//
// Code generated by csilgen; DO NOT EDIT.
package corndogs

import (
	"context"
)

// CorndogsService defines the service interface
type CorndogsService interface {
	SubmitTask(ctx context.Context, req SubmitTaskRequest) (SubmitTaskResponse, error)
	GetTaskStateByID(ctx context.Context, req GetTaskStateByIDRequest) (GetTaskStateByIDResponse, error)
	GetNextTask(ctx context.Context, req GetNextTaskRequest) (GetNextTaskResponse, error)
	UpdateTask(ctx context.Context, req UpdateTaskRequest) (UpdateTaskResponse, error)
	CompleteTask(ctx context.Context, req CompleteTaskRequest) (CompleteTaskResponse, error)
	CancelTask(ctx context.Context, req CancelTaskRequest) (CancelTaskResponse, error)
	CleanUpTimedOut(ctx context.Context, req CleanUpTimedOutRequest) (CleanUpTimedOutResponse, error)
	GetQueues(ctx context.Context, req GetQueuesRequest) (GetQueuesResponse, error)
	GetQueueTaskCounts(ctx context.Context, req GetQueueTaskCountsRequest) (GetQueueTaskCountsResponse, error)
	GetTaskStateCounts(ctx context.Context, req GetTaskStateCountsRequest) (GetTaskStateCountsResponse, error)
	GetQueueAndStateCounts(ctx context.Context, req GetQueueAndStateCountsRequest) (GetQueueAndStateCountsResponse, error)
}
