// Package corndogs contains generated types.
//
// Code generated by csilgen; DO NOT EDIT.
package corndogs

// StringInt64Map is a type alias
type StringInt64Map map[string]int64

// Task represents a structured data type
type Task struct {
	Uuid            string `json:"uuid" yaml:"uuid"`
	Queue           string `json:"queue" yaml:"queue"`
	CurrentState    string `json:"current_state" yaml:"current_state"`
	AutoTargetState string `json:"auto_target_state" yaml:"auto_target_state"`
	SubmitTime      int64  `json:"submit_time" yaml:"submit_time"`
	UpdateTime      int64  `json:"update_time" yaml:"update_time"`
	Timeout         int64  `json:"timeout" yaml:"timeout"`
	Payload         []byte `json:"payload" yaml:"payload"`
	Priority        int64  `json:"priority" yaml:"priority"`
}

// SubmitTaskRequest represents a structured data type
type SubmitTaskRequest struct {
	Queue           string `json:"queue" yaml:"queue"`
	CurrentState    string `json:"current_state" yaml:"current_state"`
	AutoTargetState string `json:"auto_target_state" yaml:"auto_target_state"`
	Timeout         int64  `json:"timeout" yaml:"timeout"`
	Payload         []byte `json:"payload" yaml:"payload"`
	Priority        int64  `json:"priority" yaml:"priority"`
}

// SubmitTaskResponse represents a structured data type
type SubmitTaskResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// GetTaskStateByIDRequest represents a structured data type
type GetTaskStateByIDRequest struct {
	Uuid  string `json:"uuid" yaml:"uuid"`
	Queue string `json:"queue" yaml:"queue"`
}

// GetTaskStateByIDResponse represents a structured data type
type GetTaskStateByIDResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// GetNextTaskRequest represents a structured data type
type GetNextTaskRequest struct {
	Queue                   string `json:"queue" yaml:"queue"`
	CurrentState            string `json:"current_state" yaml:"current_state"`
	OverrideTimeout         int64  `json:"override_timeout" yaml:"override_timeout"`
	OverrideCurrentState    string `json:"override_current_state" yaml:"override_current_state"`
	OverrideAutoTargetState string `json:"override_auto_target_state" yaml:"override_auto_target_state"`
}

// GetNextTaskResponse represents a structured data type
type GetNextTaskResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// CompleteTaskRequest represents a structured data type
type CompleteTaskRequest struct {
	Uuid         string `json:"uuid" yaml:"uuid"`
	Queue        string `json:"queue" yaml:"queue"`
	CurrentState string `json:"current_state" yaml:"current_state"`
}

// CompleteTaskResponse represents a structured data type
type CompleteTaskResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// UpdateTaskRequest represents a structured data type
type UpdateTaskRequest struct {
	Uuid            string `json:"uuid" yaml:"uuid"`
	Queue           string `json:"queue" yaml:"queue"`
	CurrentState    string `json:"current_state" yaml:"current_state"`
	AutoTargetState string `json:"auto_target_state" yaml:"auto_target_state"`
	Timeout         int64  `json:"timeout" yaml:"timeout"`
	NewState        string `json:"new_state" yaml:"new_state"`
	Payload         []byte `json:"payload" yaml:"payload"`
	Priority        int64  `json:"priority" yaml:"priority"`
}

// UpdateTaskResponse represents a structured data type
type UpdateTaskResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// CancelTaskRequest represents a structured data type
type CancelTaskRequest struct {
	Uuid         string `json:"uuid" yaml:"uuid"`
	Queue        string `json:"queue" yaml:"queue"`
	CurrentState string `json:"current_state" yaml:"current_state"`
}

// CancelTaskResponse represents a structured data type
type CancelTaskResponse struct {
	Task *Task `json:"task,omitempty" yaml:"task,omitempty"`
}

// CleanUpTimedOutRequest represents a structured data type
type CleanUpTimedOutRequest struct {
	AtTime int64  `json:"at_time" yaml:"at_time"`
	Queue  string `json:"queue" yaml:"queue"`
}

// CleanUpTimedOutResponse represents a structured data type
type CleanUpTimedOutResponse struct {
	TimedOut int64 `json:"timed_out" yaml:"timed_out"`
}

// GetQueuesRequest represents a structured data type
type GetQueuesRequest struct {
}

// GetQueuesResponse represents a structured data type
type GetQueuesResponse struct {
	Queues         []string `json:"queues" yaml:"queues"`
	TotalTaskCount int64    `json:"total_task_count" yaml:"total_task_count"`
}

// GetQueueTaskCountsRequest represents a structured data type
type GetQueueTaskCountsRequest struct {
}

// GetQueueTaskCountsResponse represents a structured data type
type GetQueueTaskCountsResponse struct {
	QueueCounts    StringInt64Map `json:"queue_counts" yaml:"queue_counts"`
	TotalTaskCount int64          `json:"total_task_count" yaml:"total_task_count"`
}

// GetTaskStateCountsRequest represents a structured data type
type GetTaskStateCountsRequest struct {
	Queue string `json:"queue" yaml:"queue"`
}

// GetTaskStateCountsResponse represents a structured data type
type GetTaskStateCountsResponse struct {
	Queue       string         `json:"queue" yaml:"queue"`
	Count       int64          `json:"count" yaml:"count"`
	StateCounts StringInt64Map `json:"state_counts" yaml:"state_counts"`
}

// QueueAndStateCounts represents a structured data type
type QueueAndStateCounts struct {
	Queue       string         `json:"queue" yaml:"queue"`
	Count       int64          `json:"count" yaml:"count"`
	StateCounts StringInt64Map `json:"state_counts" yaml:"state_counts"`
}

// QueueAndStateCountsMap is a type alias
type QueueAndStateCountsMap map[string]QueueAndStateCounts

// GetQueueAndStateCountsRequest represents a structured data type
type GetQueueAndStateCountsRequest struct {
}

// GetQueueAndStateCountsResponse represents a structured data type
type GetQueueAndStateCountsResponse struct {
	QueueAndStateCounts QueueAndStateCountsMap `json:"queue_and_state_counts" yaml:"queue_and_state_counts"`
}

// ServiceError represents a structured data type
type ServiceError struct {
	Code    uint64 `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}
